### ISSUE TITLE
Rename Github Org

### ISSUE THREAD

**Issue by hufman** [BimmerGestalt/AAIdrive#213]
I think it would be valuable to move AndroidAutoIdrive and related projects to a separate Github Org, but what should it be named?

**Comment by ThiloLangbeinHUK** [comment]
WhatABigCarMakerWasUnableToDo ß

**Comment by berseker** [comment]
i think that's connected to https://github.com/hufman/AndroidAutoIdrive/issues/212 :D

**Comment by bogdan-calapod** [comment]
Why not simply `AndroidAutoIdrive` ? I see many github projects going that route 🤔

**Comment by hufman** [comment]
Do you mean, name it the same as the project? This would make sense too, and then just have one big move combined with renaming the project from #75.

There are a few other repos that I'd also move to the organization: the BMWConnectedAnalysis documentation, the IDriveConnectKit(Android) libraries, and the planned IDriveConnectAddons plugin apps.

Perhaps the project itself could be named AAIdrive, representing its roots as bringing Android Auto features to IDrive and retaining the mindshare of the AAI initialism that it has been commonly referred to by, and also remaining at the top of any alphabetical lists, while the libraries and Github organization and Store Release organization could be IDriveConnect?

**Comment by hufman** [comment]
No updates yet, I don't want to move anything until the 1.3 release.

**Comment by hufman** [comment]
The app has been renamed from my personal Github account to BimmerGestalt/AAIdrive.
This also allows the CrowdIn translations to use a bot user instead of my own user for translation PRs, and so I now get emails when they are created :D
