### ISSUE TITLE
Reimplement Calendar car app

### ISSUE THREAD

**Issue by hufman** [BimmerGestalt/AAIdrive#279]
With Connected being replaced with MyBMW, the Calendar app and the ability to navigate to upcoming appointments is going away. This ability is provided by Android Auto, and so it would fit in the purview of Android Auto Idrive.

**Comment by hufman** [comment]
In early version is available in the [calendar branch](https://github.com/BimmerGestalt/AAIdrive/tree/calendar), and here's a [test build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-calendar-nomap-sentry-release.apk) to try out before I merge to the main branch!

**Comment by berseker** [comment]
> In early version is available in the [calendar branch](https://github.com/BimmerGestalt/AAIdrive/tree/calendar), and here's a [test build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-calendar-nomap-sentry-release.apk) to try out before I merge to the main branch!

I tried today this test build, I can confirm that  (check the comment & the screenshot organized this way)

1 | 2
3 | 4

1) the app shows up (BMW Calendario, so it takes the Italian Language app name

2) scrolling between dates works flawlessly
it highlights also the holidays with an "halo" under the day number (as instance, December 8Th is an Catholic Holiday)

3 & 4) it is not connected to the Google Calendar (but maybe it is not supposed to, at least at this stage ;), I quickly tried to add an appointment \ reminder for my Mum birthday to try just for curiosity

![image](https://user-images.githubusercontent.com/1159431/143924781-239561e1-48c5-4df6-9cde-a2347bffc199.png)

in any case, excellent job as always :)

**Comment by hufman** [comment]
Hmmm! That's disappointing, it works very well for me and my Samsung Calendar (which Google Calendar sees the same events). The fact that it sees the holidays means that it has the READ_CALENDAR permission, so it's not that...
Do you have several calendars in Google Calendar, and do some of them at least show up? I wonder what the pattern is, since your Holiday calendar shows up.

**Comment by berseker** [comment]
I checked and the app I'm using is MIUI Calendar 12.5.1-data, so maybe It works weird as all the MIUI apps do :) i confirm i gave the permissions. The app Is linked to my Google Calendar(s) more than One account. Actually if you see the screenshot, December 5 have Also the "halo" thing as It has inside something but After clicking on It, nothing shows up.. i'll do more tests and let you know.

**Comment by Marc2480** [comment]
I don't seem to get any entries in the calendar, using Samsung email (1 exchange and 1 imap account)  on a S20 ... Any specific setting needed apart from granting access to AAI ? (running build 1.3.1.24 Calendar)

thanks, Marc

**Comment by jezikk82** [comment]
On first usage you should be prompt to give access to android calendar default app. Check if you have in default calendar entries from Samsung email app. 

e.g. I have exchange app in Workspace (email&calendar) and this calendar evens are not seen, as this spaces are independent.

**Comment by hufman** [comment]
Thank you all so much for testing!
I'm not sure what options there are for supporting Mi Calendar... I do see that it has its own Content Provider to provide access to its events, but the API contract is undocumented and very different from the native Android Calendar Content Provider, and unlikely to be guaranteed between versions. Is there a setting in Mi Calendar to synchronize their calendar with other apps? The original BMW Connected Calendar would not support it either, it only has code to query the system calendar.

I'm also not sure how Samsung email will integrate with it; as long as it's pushing the events to the system calendar so that they are visible in Google Calendar on the phone, it should work fine. My Samsung S9 uses the native Google Account Sync to fill things in the system calendar, which then shows up in Samsung Calendar. I did not add any filtering options in AAIdrive for now, so all events that are viewable should show up. The Work Profile calendar is indeed entirely separate and can't be seen from the main apps.

If AAIdrive Calendar doesn't have permission, it'll show a button in the phone UI to grant it and it'll show a one-time popup in the car app to request access. You'll probably have already granted this, which should be all you need to do.

The app name is hardcoded into the BMW app resources, so I'm delighted that it has a translated name! I don't think any other car app has a translated name like that!
I don't know of a way to show the day view in the sidebar while in the month view: that screen is entirely managed by the car, and all I do is provide a list of highlighted days for the month that the car says it is showing.
I'd like to hear more about the bug about the selected day being different when going back to the month view, I tried to [support this](https://github.com/BimmerGestalt/AAIdrive/blob/21dd771f8bb3e85dae5781d5cf7bcfe0a615bfe7/app/src/main/java/me/hufman/androidautoidrive/carapp/calendar/views/CalendarMonthView.kt#L39) feature. In fact, it seems very sticky for me, so that it goes back to the last selected day even when exiting the app and going back into it.
Please also tell me more about the month view showing an event on December 5th but no event showing in the day view. The code to find events for the Day view purposely looks a day ahead and behind to catch events that cross midnight (technically it won't show events in the Day view if you click into the middle of a week-long event, which aren't going to be super relevant to navigation but still fixable if that's preferred).
The Day view might support adding an icon or something; the BMW Calendar code says that there's a field for an ID of an image from the icon pack, which didn't work for either attempt I tried, but I haven't yet tried sending an actual image in this field which does work in other lists in the car. I planned to explore this after merging this branch to the main branch.

**Comment by berseker** [comment]
about "Please also tell me more about the month view showing an event on December 5th but no event showing in the day view. " i noticed that the halo is simply the one always present in the "selected" day :/  
today I tried both only Miui Calendar & even Google Calendar but suddenly completely stopped working for me (the calendar worked but neither the holidays were shown today).. I surely manager to broke something, I'll try again some testings in the next days and give you some reports

**Comment by hufman** [comment]
How do you like the wording on this note, if the Mi Calendar is installed on the phone?
![image](https://user-images.githubusercontent.com/1592375/144163235-b14b51aa-265d-4444-a1a1-abcb09073108.png)

**Comment by jezikk82** [comment]
Maybe it would be better something like this: 

_Events from **Vendor Specific** calendar apps (e.g. Mi Calendar) or from **Work Profile** that are not sync with default Android Calendar may not show up in the car. 

The car will show the events that are visible in Google Calendar only (including shared calendars)._

**Comment by hufman** [comment]
How about this? The description at the top always shows up, indicating that Google Calendar will be the definitive view, and the Mi Calendar notice only shows up if Mi Calendar is installed.
![image](https://user-images.githubusercontent.com/1592375/144260449-c6e4ef79-5631-4dea-b478-ca97adaf0ef5.png)

**Comment by jezikk82** [comment]
Quick question, is it possible to present only calendars where I see details ? In Gcalc I have some read-only calendars where I only see free/busy and no detail and on daily bases it's not needed to present in the car. 

So would be nice to have option to show only selected calendars from Gcalc or if not possible to present only the event that have title/details. Thanks.

**Comment by hufman** [comment]
In my test (and peeking in some Android code) it should hide events from calendars that aren't selected to display in Google Calendar.
I can also add an option to hide events without details or location easily enough! Thanks for the suggestion!

**Comment by hufman** [comment]
![image](https://user-images.githubusercontent.com/1592375/144697712-91ccceea-07f7-4e88-a1b1-bc2736355e8f.png)

**Comment by jezikk82** [comment]
> In my test (and peeking in some Android code) it should hide events from calendars that aren't selected to display in Google Calendar. I can also add an option to hide events without details or location easily enough! Thanks for the suggestion!

In my case not showing calendars that are unselected works fine. Adding the toggle to hide events without details would be nice and would solve the problem. Not sure about hidding events without location, as sometime I create tasks in calendar without location.

**Comment by hufman** [comment]
I implemented this toggle to hide any events that have neither a description or a location, so if one of those fields is provided it will still show the event.

**Comment by jezikk82** [comment]
Great, will test it over the weekend

**Comment by jezikk82** [comment]
I tested the latest commits but unfortunately for me the calendar doesn't work any more. No matter the toggle to hide event without location/details is on or off.  App shows the calendar permission granted but in car no events. 

Previously it was working almost fine. 

Still there is a situation that when I enter details at that day and press back button on idrive controller, the selected day is usually 1st day of the month or first Sunday of the month. 

Request: 
- on details page you have link under date on top of the view, but now when you press it i see some empty page, maybe it would be nice to link that date to move to next date details page.

**Comment by jezikk82** [comment]
https://youtu.be/aubJHFo2vgE

**Comment by jezikk82** [comment]
`Did you ever see the highlighted halo in the Month view, as shown in the pictures from berseker?`

No i haven't seen.

I'll check tomorrow both versions and let you know.

**Comment by jezikk82** [comment]
I checked version with roll-backed commit 7f099d3 works fine. Below are 2 movies showing the working calendar with and without hiding empty events. Unfortunately, no halo even on Christmas Days (24-26 Dec). 

https://youtu.be/XRAtZnOEtog
https://youtu.be/KzOwn9GU9vw

Version with that commit fails

**Comment by berseker** [comment]
>  Did you ever see the highlighted halo in the Month view, as shown in the pictures from berseker?
actually also myself after that first "quick test" i did not manage to see the "holidays" again . not sure which is the reason

**Comment by hufman** [comment]
@jezikk82 thank you for the test! Can you clarify which commit shows the working Day view and which one does not show any events in the Day view? The option to hide empty events came after that 7f099d3 Day View change, so that's promising...

Please try out cloning the repo down again and remove the Ignore line from [this test file](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/androidTest/java/me/hufman/androidautoidrive/CalendarTest.kt#L13) and uncomment some of the debugging from the [query module](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/java/me/hufman/androidautoidrive/calendar/CalendarProvider.kt#L138) and try out running the CalendarTest from your IDE. You can edit the CalendarTest to query with a null day parameter to simulate the month view. Perhaps add an extra logging line above the splitEventIntoDays loop to see if it's finding events there and they're somehow making it into the loop for some reason. It should add lines to your Logcat tab (filterable by the word Calendar) with what events it found.

Thank you for your patience in helping with the project!

**Comment by jezikk82** [comment]
I only rolled back single commit no 7f099d3. So in 2 files mentioned there i have old content.

Will try tomorrow CalendarTest and let you know.

**Comment by hufman** [comment]
I encountered a crash, and it seems that sometimes the phone's CalendarProvider can unexpectedly return null strings for the title, description, or location strings. I just added a guard for that behavior, and perhaps it might fix the problem you were seeing.

**Comment by jezikk82** [comment]
I'm extremely busy now and didn't have time to test what you stated. Today I made a quick test of what you committed and I don't work for me. I see only full day event, no other. Doesn't matter if the toggle to hide is on or off. Will share some pics later showing the problem.

**Comment by hufman** [comment]
I appreciate the time you spend helping test this project!
That looks like progress, since you hadn't seen the Highlighted Days halos before! Do I understand you are running the tip of the main branch but with 7f099d3 reverted in your build? That commit is meant to make sure that, if a day is highlighted in the month view (such as your Dec 17), then it will show up in the day view. Of course, those short events you demonstrate should show up anyways, so there's still something behaving wrong there. The [toggle will affect](https://github.com/BimmerGestalt/AAIdrive/blob/2c7e4056afdb8ac29a2c39c886b6e82372a6d2a4/app/src/main/java/me/hufman/androidautoidrive/calendar/CalendarProvider.kt#L132) whether an empty event is shown in the Month view too, not just the Day view, they _should_ always match.
Does the "p.s." mean that I fixed that bug you were encountering?

**Comment by jezikk82** [comment]
Today's testes I performed on clean version from github. 
No, previously I havent seen Highlighted Days halos, now it's present on days that have all day events. 
Yes, you fixed the but I demonstrated on previous video when going back from day view highlighted was not the right day.

As soon as I get some free time will try to check with 7f099d3 reverted and let you know.

**Comment by jezikk82** [comment]
By chance I think I found root cause of the problem, actually two problems. 

1. In Google calendar I have couple of different calendars, not only from Google but from others apps as well. What I did is to mark all of them as visible in GCalendar and made an event in all of them one by one. That way I discovered that only events from subscribed GCalendar Holiday events and week numbers are presented and from alphabetically first calendar on the list. In my case of it's a calendar from some app I dont use so much. Checked it twice and adding events from GCalendar and choosing that calendar make event visible in the car. 
Not sure how You were taking events before, but It was working for me before the 7f099d3. I showed that in this video: https://www.youtube.com/watch?v=KzOwn9GU9vw

Two link that may be useful:
https://stackoverflow.com/questions/14423189/how-to-get-calendar-event-by-date-range-or-month-in-android/15331996#15331996
https://stackoverflow.com/questions/61012807/android-calendar-provider-does-not-return-latest-data

2. Toggle to hide events without details is not working as expected as well. On Dec 17 I have some events, I edited them to use the calendar I stated before as I see them in the car. 
- Browns event are synced from read only calendar and Title is "BUSY" no details. However in car they are presented without title (see video above) - toggle remove that entries. 
- Blue are mine, some of them have Teams meeting details, other have addresses in it and **some have only title and times** This last set it also hidden when toggle is on.

**Comment by jezikk82** [comment]
Any progress ?

I looked at https://developer.android.com/guide/topics/providers/calendar-provider#kotlin but can't find in AAID where to modify to ask for all subscribed calendars.

**Comment by hufman** [comment]
I haven't been able to think of anything. I recently added a change to require a title to be considered detailed enough to show in the car, which you may have seen.

The single line in AAIdrive that asks for calendar events [is here](https://github.com/BimmerGestalt/AAIdrive/blob/82165b820d4aa86fb317d7712078f5434659e86b/app/src/main/java/me/hufman/androidautoidrive/calendar/CalendarProvider.kt#L126). It uses an official [helper function](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/provider/CalendarContract.java#1917) to query all events from the Instances table. This function automatically adds a query parameter of `visible=1`, which I believe would properly show all events for visible calendars and not include unchecked calendars. You could try copying this helper function and modifying it to not add this visible parameter, and maybe it will help find more events from your phone.

The change in 7f099d3 is to, when viewing the day view, to query the entire month and then filter for any events that have the correct day, as opposed to previously querying for events specifically by day, to handle the case where events span across the day. Because the same query is now being queried for both month and day view, any highlighted days in the month view should have events in the day view.

Have you checked in ADB Logcat to see if your phone is logging any crashes? Technically, when trying to [set an icon](https://github.com/BimmerGestalt/AAIdrive/blob/82165b820d4aa86fb317d7712078f5434659e86b/app/src/main/java/me/hufman/androidautoidrive/carapp/calendar/views/CalendarDayView.kt#L80) for an event in the day view, I'm sending an RHMIResourceIdentifier while the official BMW Connected Calendar used to just send an integer, and perhaps your car is returning an exception and mine is just ignoring it? I just pushed up a change to remove this code and match the original Calendar app's behavior, just in case.

**Comment by masteralarm** [comment]
It this intended to be running on iDrive4, too? 
Currently, it seems broken (at least in my car/setup):

![2048-966-max](https://user-images.githubusercontent.com/1875852/147099495-9729eb80-a454-485d-a25d-7556a838c12b.jpg)

**Comment by masteralarm** [comment]
Had the chance to test it with the ID4 XML file, but still the same situation.
I will try to get the log output next time.

**Comment by hufman** [comment]
Very interesting! Thank you for the log snippet!
Would you be able to swap out MyBMW for BMW Connected 6.4, manually grant it the Calendar permission through the Android settings, and see how the official BMW Connected Calendar behaves? I deciphered the Calendar app protocol by reading the decompiled code from BMW Connected, but I didn't see any special handling for ID4 in there and I wonder what I'm missing...

**Comment by masteralarm** [comment]
Alright, I will test it. Anything in particular I should do, like saving logcat messages again?

Side note: From my previous experiences, neither the BMW calendar apps from the Connected and Classic versions of the app were perfect, but the one from the BMW Connected Classic app worked better. It showed all my calendars from my phone (and even let me select/deselect every calender via the options menu in iDrive). The one from the newer Connected app only showed my Google calendar.
Both had in common that the left side-menu was a bit broken, the bottom menu entry (used for scrolling I think) was not visible but selectable.

**Comment by hufman** [comment]
Capturing logcat messages isn't necessary for testing BMW Calendar, it has its logs muted. If you have a rooted phone, an advanced technique would be to install and run `tcpdump -i lo` to capture the car traffic, but probably not necessary.
That's curious that Classic's Calendar was more functional! I'll peek in that codebase to see if it has any clues! I'd be most interested to see if the new BMW Connected Calendar works properly in your ID4, and I'd appreciate an overview (perhaps a video?) of how BMW Classic Calendar works. Thank you so much for your patience and assistance!

**Comment by masteralarm** [comment]
Here is a video showing the behavior of the original calendar app from the BMW Connected app:

https://user-images.githubusercontent.com/1875852/148662516-f9db8caa-6b7a-4837-a55d-68dbf518636c.mp4

And here is a demo of the Connected Classic's calendar app:

https://user-images.githubusercontent.com/1875852/148662548-525b4f31-e0bc-4653-883e-ea6651419adc.mp4

**Comment by hufman** [comment]
I just added a phone interface section to show what calendars and events the app can see, hopefully it helps debug the calendar visibility problems!

**Comment by jezikk82** [comment]
Hi, I just tested new release and it confirm what I manage to find earlier. It only takes one "default???" calendar (now it's xiaomi default) not the GCal and other subscribed calendars. All the calendars except Contact are marked as visible in GCalendar app. 

That's interesting as well, as I don't have a Xiaomi Calendar app on my phone installed. It as removed with xiaomi debloater just after I bought the phone. Previously the "default??" calendar was from some project management app I tested, but after complete removal and clean-up with ADB it changed to xiaomi calendar DB (previously removed). Strange behaviour.  

Maybe the best way would be to mark which calendars include in the car as you already have most of the  ui for it. (same swipe behaviour as with music apps)

![Screenshot_2022-01-14-11-34-46-606_me hufman androidautoidrive](https://user-images.githubusercontent.com/7836767/149502481-8e7edfb1-9a19-4c6e-8632-54f3760ec97f.jpg)

**Comment by hufman** [comment]
That's fascinating! I just pushed up [a branch](https://github.com/BimmerGestalt/AAIdrive/tree/calendar_accounts) that adds a debug row showing what sync provider each calendar comes from, check it out! Please feel free to experiment with this code and explore the data further.
I'm reluctant to add a separate customization of what calendars to view: This adds several extra user interaction steps and a complicated data storage model, which is tricky to keep in sync with the default data, in order to make its behavior diverge from the phone's native view of the data. I'd much rather have it work automatically, by figuring out the weird incompatibility with your (or perhaps, any?) Huawei phone.

**Comment by jezikk82** [comment]
Quick check:

![Screenshot_2022-01-14-21-57-56-414_me hufman androidautoidrive](https://user-images.githubusercontent.com/7836767/149584602-4e5c3a4a-34be-423a-9ec8-e05fb7fd3e6b.jpg)

hope that can help you somehow to discover what's going on with at least Huawei/Xiaomi phones. 

I also would like to see the event from calendars I have marked in GCalendar without any extra layer, but if there are some problems in querying/implementation maybe that's a workaround.

**Comment by hufman** [comment]
Closing this implementation ticket as complete, and split off the remaining bugs to be tracked separately.
