### ISSUE TITLE
GMaps/Spotify warning - missing API key

### ISSUE THREAD

**Issue by jezikk82** [BimmerGestalt/AAIdrive#285]
Hey, 

I think it's a good idea to add info about missing GMAP API key on the map page if you build the maps variant and **in the app on the MAP tab and in the car if possible**. Same should be applicable to Spotify as well. 

Friend of mine built the newest version and came to me to help to solve the gmaps not working. He was super sure he has the gmap api key set, but after long investigation I discovered that on some update the gradle file was overwritten by the master and he lost his api keys.

**Comment by hufman** [comment]
Yes this is a good idea.
