### ISSUE TITLE
[Future Req] Add VIN based car details to the app

### ISSUE THREAD

**Issue by jezikk82** [BimmerGestalt/AAIdrive#340]
You can find free vin decoder (https://decoder.bvzine.com/) on the net, so maybe it would be nice to implement possibility to read such date and cache them in the app. 

My proposal would be:
1. MVP: read from web (manually triggered by user, captcha on user site) and present in the app all vin related information
- Store them in cached data in app 
- option to change car (e.g. remember 2, 3, 5 cars date with possibility to change that manually). 
2. Next step: integrate VIN related info with actual car stats tab  based on the connected car vin. (possibility to change car manually to view different car's data). Combination of this 2 sets would give very detailed info about the car. 
 
What do you think about it ?
Please share your though and possible use cases you'd like to see in future.  

Please vote if you'd like such future.

**Comment by LACNR** [comment]
I personally don't see the usage of that as the app is mainly to have enhanced in-car entertainment to use apps and other features. And if anyone wants to know his equipment list can do that on various trusted websites, even on official BMW Equipment, Accessoires and Parts retailers. But that would be a one time thing I mean who wants/needs to know their cars equipment daily?

Didn't want to be negative on your idea as it is gererally useful if someone wants to buy a BMW or once see what options the owned car has but I feel like it is kinda off the pace what hufman intended to make possible with this artwork sent from heaven. :)

**Comment by jezikk82** [comment]
As I said it can be some side-future for the app. Idea came from a friend of my friend who I was helping with the app. He has couple of BMWs (from really old to new once) and sometime he doesn't know details of the cars and also would like a option to gather stats about e.g. odometer, fuel consumption of the compatible cars with option to export in future. 

That's why I asked the community if You also see some similar use cases that we can be added in future to the app. 
I agree that for now we have more important future to get working.

**Comment by LACNR** [comment]
I mean there are many website to get all the details via the VIN, I don't think this App needs it especially since it is compatible with BMW 2014+.

About the other Information, when the App is Connected with the cars is does readout various values RPM, Oil Temps, Engine Temp and whatnot :)
Maybe this helps your friend already :)

**Comment by hufman** [comment]
I think this feature would not fit in the core Android Auto for IDrive concept, but could be built as a separate Companion App idea that integrates information from the CDS. It could perhaps be combined with the more performance-oriented gauge display app idea that you had.

**Comment by hufman** [comment]
Moved this idea to the Addons ideas list
