### ISSUE TITLE
App kann nicht installiert werden 

### ISSUE THREAD

**Issue by TobifromGermany** [BimmerGestalt/AAIdrive#375]
Ich kann seit einigen Wochen nicht mehr das neuste Update Sentry Build installieren. Meine Einstellungem für fremde Apps installieren stimmen aber noch...

Die aktuelle Version Build Version: 1.3rc2-56-b54121f 25.07.2021 22:57:58
was ich installiert habe läuft aber problemlos, also kein großes Problem.

**Comment by hufman** [comment]
What error are you receiving?
I do know that Android considers the 1.3 release to be a lower version than the 1.3rc series, so it prompted me to uninstall the previous version to install the new version. Are you encountering this issue, perhaps?

**Comment by TobifromGermany** [comment]
Nach dem ich das Sentry Build downloade und installieren kommt diese Meldung... 
![Screenshot_20210828-192949_Package installer](https://user-images.githubusercontent.com/83277764/131224519-fb636531-f32a-4ae6-8963-ad831af06eec.jpg)

**Comment by hufman** [comment]
Very curious! Try uninstalling the old version of the app anyways.

**Comment by TobifromGermany** [comment]
Das hat funktioniert 👍🏻

**Comment by hufman** [comment]
Glad to help! ♥️
