### ISSUE TITLE
Spotify Web API crashes on API<26

### ISSUE THREAD

**Issue by hufman** [BimmerGestalt/AAIdrive#380]
A recent Spotify Web API client update is using a newer Java Time API that isn't available on older phones, and the analytics has noticed (at least) two Android Nougat users are encountering a crash due to this. An attempted workaround in 351971a seems to have not fully fixed it, but the library author is [amenable](https://github.com/adamint/spotify-web-api-kotlin/pull/291) to releasing a version that doesn't use the new Java Time API.
This tracking issue is to remind me to update to the new library version when it is released.

**Comment by adamint** [comment]
@hufman thought I'd give a personal update asap. 
Version 3.8.2 of spotify-api-kotlin-android is being synced to central and should be available within the next few hours. Could you let me know if you run into any additional bugs around any java 8 apis?
The relevant code change is [here](https://github.com/adamint/spotify-web-api-kotlin/commit/d526b9288ada5879d1fbf02dbb3bdcd918f0297a#diff-fc0b6b1b2ed3151cd076b858986afef950f8e5e797afe3b706ccf86620806d32).

**Comment by hufman** [comment]
Great, I'll let you know!

**Comment by hufman** [comment]
This should be fixed by 4324247
