### ISSUE TITLE
AAI Bluetooth Apps not supported on ID4

### ISSUE THREAD

**Issue by yasin-mesut** [BimmerGestalt/AAIdrive#383]
Hey there,

I'm just curious about having the possibility to run Bluetooth Apps on my car or not. I own a 2016 BMW with entry_nav ID4 (I've seen a few issues here where other users have even older models with supporting BT Apps). I haven't been able to properly connect my phone (Android 11) to the car via USB for a long time (even before Connected App 6.4). I always get something like 'not supported' during Connected Drive assistant in my car. However, since myBMW App supports BT Apps, I'm curious about how to get this working with my car - if possible. Is there anything special my car should have to support in order to get BT Apps running? I've just stumbled about AAI and am really keen about to get it running.

**Comment by hufman** [comment]
I believe the main requirement for Bluetooth Apps is ID5/ID6L, and your car's ID4 probably only supports USB. Another requirement is that the Bluetooth settings for your phone within the car should show a [Bluetooth checkbox like so](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res/drawable/pic_btapp_bmw.jpg). AAIdrive will detect whether the required SPP connection (Bluetooth Serial Port Profile) is available and show a checkbox indicating whether Bluetooth Apps are supported, and I don't believe this SPP availability can change during the life of the headunit.

As for your phone being 'not supported', is your phone set to Charge Only over USB or have you flipped it to File Transfer? My test Pixel 2 defaults to Charge Only and I need to flip this setting to get the connection to continue.

**Comment by yasin-mesut** [comment]
Alright, I see. According to your information, especially the image, I don't have BT apps in my car. Sad, thought this would be possible due to enhanced BT.

Anyways. I'm using a Galaxy Note 10 with Android 11 and as soon as I plug the USB cord in it jumps to charge. However, I always change it to file transfer. I never get something else shown except of 'not supported' but what I get is a rebooting MMI of my BMW a few minutes later while being plugged in with my phone being on file transfer mode. No idea what the issue is in here. Not only that AAI isn't working, I can't even get the prerequisite to work properly.

**Comment by hufman** [comment]
Indeed, it looks like [Enhanced Bluetooth](https://www.bimmer-tech.net/blog/item/56-bmw-enhanced-bluetooth) at that time mostly added music and the contacts and sms abilities over Bluetooth.

That is a very curious bug indeed! In my Galaxy S9, when I set it to File Transfer mode, the phone brings up a prompt to open the MyBMW, Mini, or Supra app (if multiple are installed) right as the phone's USB settings flips to Accessory mode (which displays as Charging mode, but AAIdrive will show a checkbox saying it's in Accessory mode). If the phone never flips away from File Transfer mode after you first change it, that's very unexpected indeed!
Have you tried a different USB cable? Maybe the one you have now only supports charging instead of full data transfer?

**Comment by yasin-mesut** [comment]
I'm currently using an original Samsung USB C cable. I've also tried a few other ones - none works. It's pretty frustrating actually sine I can not use connected drive apps. I've even asked BMW connected drive Hotline today - nothing worked, sadly.

**Comment by hufman** [comment]
Have you tried every USB port in the car? Some of them don't have data access, I think. Does the car recognize the phone for file storage, at least?

**Comment by TBGR** [comment]
> I'm currently using an original Samsung USB C cable. I've also tried a few other ones - none works. It's pretty frustrating actually sine I can not use connected drive apps. I've even asked BMW connected drive Hotline today - nothing worked, sadly.

NBTs are just sensitive to cables. I had to try 4 different cables before having a reliable connection with my Samsung. 2 of the cables were bundled with the Samsung phones and the other 2 with LG phones. Switched to a 3 euro Duracell cable and had no issues for a year. Also try opening the BMW Connected/My BMW app just as you plug in the phone if you don't see the permission prompt.

**Comment by yasin-mesut** [comment]
Well, it was working previously (like 2 years ago) with the same cable, so I'm curious if it's a cable issue. Also tested a few other cables yesterday - didn't work. Might also want to try a 3€ cable. 😂

Anyways. Do I need any specific online service? I've had some additional online services those 2 years ago (like the ones you have for the first 3 years). Not sure if it is related to this. But just buying BMW Online Service for around 60€ to just test? Would be annoying if it wouldn't work then.

**Comment by hufman** [comment]
That may be what happened, do you have the ConnectedDrive > BMW Apps > Connection Assistant in your ID4 vehicle?

I'm not sure if the subscription still works for ID4, other people have recently had problems adding BMW Apps to their ID4 cars with the subscription in #384 and #387 and so I can't confidently recommend buying the subscription.

**Comment by yasin-mesut** [comment]
Yes, I still have the connection assistant. What basically happened was:

2 years ago I updated to Android 10 and also updated my car software. Afterwards everything broke. Until then, it was fine. Somewhere around Dec. 12 I also lost my initial 3 year subscription so I wasn't sure about if the issue was related to Android,, BMW

**Comment by LACNR** [comment]
You need the BMW Connected App to be installed in order for the connectivity assistent authorize your device, if it doesn't work automatically, run in manually, upon that it should connect automatically.

As far as I know MyBMW is still not supportive with ID4, even though it does popup to have connected to the car via Bluetooth and USB eitherway.

Make sure your phone does allow auto-select top file transfer, newer Samsungs have the weird feature to disallow if not paid attention.

**Comment by TBGR** [comment]
@LACNR MyBMW has been working OK for the past month or two now.  No idea about any of the functionality of the app itself though, since i am running iDrive 4.0 retrofitted into a car that had CCC originally.

**Comment by LACNR** [comment]
I mean using MyBMW to have Spotify and such Apps didn't work previously because it didn't Support USB App Connectivity from the previous Connected Apps but instead only the Bluetooth protocol tunnel.

Did it change recently?

**Comment by hufman** [comment]
I believe MyBMW gained official support to run the Apps tunnel over USB at version 1.5.0, which was released in the middle of July this year.

**Comment by LACNR** [comment]
> I believe MyBMW gained official support to run the Apps tunnel over USB at version 1.5.0, which was released in the middle of July this year.

Really? I must have slept on that, I do have the latest 1.5.1 installed but didn't hear it supports the USB apps tunnel now. Gotta try and uninstall Connected to see :)

Thanks for the info!

**Comment by hufman** [comment]
I believe this issue has been resolved, let me know if you have any other questions!
