### ISSUE TITLE
Spotify app auth and background app popup support

### ISSUE THREAD

**Issue by jernauH** [BimmerGestalt/AAIdrive#385]
I’m unable to grant permissions to browse spotify library. I get the following message in the AAIDrive UI;

{“message”:”Explicit user authorization is required to use Spotify. The user has to complete the authors-flow to allow the app to use Spotify on their behalf”}

I get a notification stating Spotify connections AndroidAutoIdrive is connecting but nothing else, when I grant ability to search Spotify I get a web page pop-up that allows me to grant permissions but nothing for browse.

I’m running on a Poco X3 Pro, I believe I have set Spotify to run in the background properly and disabled battery management for Spotify

Any ideas on what I may be missing here?, many thanks

appologies app permissions were disabled for popups on background apps …. Sorry please close this issue

**Comment by hufman** [comment]
Oh excellent, I'm glad you figured it out! I'll try to figure out how to provide a better hint in the UI about this.

**Comment by hufman** [comment]
This branch was merged to the main branch here: 06d598e

**Comment by clerdson** [comment]
![Captura de Tela 2022-09-19 às 00 45 13 (2)](https://user-images.githubusercontent.com/31813027/190946725-58328bf3-a88f-4af6-b62b-0fb64288cf99.png)

**Comment by clerdson** [comment]
my frist experieence in @SpotifyApi

**Comment by hufman** [comment]
What is this screenshot about, and why is it on a year-closed thread? Are you building your own app to connect to the Spotify API? Check that your Spotify is allowed to run in the background, which is required for it to open the user authorization prompt.
