### ISSUE TITLE
[Feature Request] Add AAIDrive to share

### ISSUE THREAD

**Issue by fabssor** [BimmerGestalt/AAIdrive#393]
I very interesting feature Dame into My mind while using the navigation feature of AAIDrive:

For now often search adresses with GMaps and then copy paste the adress into the navigation textbox of AAIDrive to send the location to the car.

Would it be possible to add AAIDrive to the share functionality. Similar as MyBMW does it.
![Screenshot_20210904-091933.jpg](https://user-images.githubusercontent.com/30718590/132086375-998bfe55-25f9-44fe-b175-9a81834b8925.jpg)

The My BMW feature needs internet connection. Because of that I often find the AAIDrive feature more convinient when I am already in the car.

**Comment by hufman** [comment]
Good morning! I'm happy that you like the navigation integration, it's a tiny thing but I've found it incredibly handy.

I implemented basic Share functionality in July with 8afac08, specifically with the goal of handling the Share button from Google Maps. Similar to handling Navigation buttons from other phone apps, it only becomes available while connected to the car.
Do you see AAIdrive show up in the Share list while it is connected to the car? The AndroidManifest definition should register it to handle any text snippet.

**Comment by fabssor** [comment]
Ah sorry did not see this! Thank you I will close this one😀
