### ISSUE TITLE
Improve management of emoticons, smileys & symbols in Notifications

### ISSUE THREAD

**Issue by berseker** [BimmerGestalt/AAIdrive#414]
I do not know if this can be achieved or even if this is a "problem" with the app, in any case I noticed that in many notifications of Whatsapp \ Gmail \ other apps, when a symbol or a smiley is in the text or title, the notification is shown on the screen like below (that's a gmail notification from my bank)
![image](https://user-images.githubusercontent.com/1159431/134764195-1dc6da7d-2077-4b88-b6d5-4c4c8fcb50ca.png)
(sorry for the quality of the photo)

in this example, 
© is shown as :copyright:
there are many other cases, if needed I can try to make more screenshots of what I mean

I do not know if this is related to these unicodes https://apps.timwhitlock.info/emoji/tables/unicode

**Comment by hufman** [comment]
This is [intentional](https://github.com/BimmerGestalt/AAIdrive/issues/64), the car doesn't include emoji in its font and so the app converts them to their aliased form like you see here.
The copyright symbol, however, should be possible, so I'll look into showing that directly.

**Comment by hufman** [comment]
It looks like, besides the ©️ symbol, the emoji cleaning code will also replace ®️ symbol.

**Comment by berseker** [comment]
thank you, I actually made some searching activity prior to post but that #64 thread didn't show up. in any case please note that :wink: for instance, can be easily understood if you know English, but "international"ly it is easier to understand if you  put ";)" instead  ;)

**Comment by hufman** [comment]
You make a good point! I'll try to add some emotion handling to help out.
