### ISSUE TITLE
Task 'assembleGmapNonalyticsDebug' not found in project ':app'.

### ISSUE THREAD

**Issue by jezikk82** [BimmerGestalt/AAIdrive#422]
Hi @hufman 

I was not building for a while my own version of AAI and today I updated everything. That went ok, I merged my changes to new project and when trying to build I got following error: Task 'assembleGmapNonalyticsDebug' not found in project ':app'.

Can you help me ?

**Comment by jezikk82** [comment]
Sorry for bothering you, but I solved the problem.  I don't know why but the build variants where not sync, after refreshing and choosing different variant "gmapNonanalyticsFullDebug" Android Studio downloaded some missing components and build was successful.

**Comment by hufman** [comment]
Indeed, as part of preparing to upload to the Google Play Store, I had to make another variant. I've updated the developer guide with the new Gradle task to run.
