### ISSUE TITLE
MINI ID5 can't select track time location by touch 

### ISSUE THREAD

**Issue by Vasmares** [BimmerGestalt/AAIdrive#425]
Hi,

until I found this app I had an old iPhone in my car at any time to use the MINI ConnectedSpotify integration for iOS.
You solution for android is better in every way.

But a "feature" is really miss is being able to select / skip to the track location (playing time) by touching the track bar our dragging over the track bar.
Like this:
![screenshot-musicplayback](https://user-images.githubusercontent.com/10863304/135730830-dd298344-6d76-4438-bd41-ea9df0d35fb8.jpg)
(Screenshot from Github gallery for this project)

My MINI is an F54 with ID5 and the large touch screen. So I love using touch.

Is this something that is not implemented or just not working for me ?

**Comment by hufman** [comment]
You know, I didn't even know that was a possibility! I do see that the audioHmiState has a Progress Bar Action, so I'll look into how this would work!

**Comment by hufman** [comment]
It turns out that not even the Android BMW/Mini Connected app implemented this feature for the official music integrations, so this is the first time this feature is available on Android! Thanks for the suggestion, it was a joy to dig out the reverse engineering tools again 😄

**Comment by Vasmares** [comment]
glad to help :D
So this is already implemented ?
