### ISSUE TITLE
Implement MapBox mapping and navigation

### ISSUE THREAD

**Issue by hufman** [BimmerGestalt/AAIdrive#43]
MapBox should be implemented as an alternative map implementation alongside Google Maps. MapBox does not include a restriction on showing their maps in a car and has a very generous free tier, which means it can be enabled by default in the public builds. It also provides a modern 3D navigation view, unlike Google which disallows replicating the Google Navigation experience.

**Comment by unlive74** [comment]
How can I download a build with MapBox? Only Nomap build available. Or just fork and build it yourself?

**Comment by hufman** [comment]
A link to the Mapbox build has been added to the Readme, try it out!

**Comment by unlive74** [comment]
I've tried it and I've created issue #531 :)

**Comment by hufman** [comment]
Yes yes I've been reading your log for the last 30 minutes ;) <3
