### ISSUE TITLE
Screen mirroring with https://github.com/Genymobile/scrcpy

### ISSUE THREAD

**Issue by fata74** [BimmerGestalt/AAIdrive#435]
Hi and thak you for your app.Is it possible to implement this function as same Linux-Windows?
Bye

**Comment by joluga1948** [comment]
Hello Hufman, the application works for me, but the screen mirroring, now I get the icon with a car with Wi-Fi signal and before I had a blue circle and yes, I saw the screen and it was ALMOST COMPLETE, WHAT COULD IT BE DUE? I HAVE THE CAR WIFI ACTIVATED, BUT I HAVE NO CONNECTIVITY, LET'S SEE IF IT WILL BE THAT, THANK YOU.

**Comment by hufman** [comment]
I'm sorry, I don't understand what you mean. Can you upload a picture to show what you are seeing?

**Comment by joluga1948** [comment]
Hello, good morning, the mirroring screen, as in the photo, keeps looking, but the screen does not appear, instead the apps go well with their covers; one day I got the mirroring icon, like a blue or green circle and yes, the screen came out, almost complete, 10.25 ", now I get the stroller with a Wi-Fi signal, could it be that I have activated the Wi-Fi, in the car, but I don't have connectivity, only wifi appears, under bluetooth the vehicle is from 2016 with ENTRYNAV, thanks 
   
  
  
   
    El 03/05/2022 21:35 Walter Huf ***@***.***> escribió:
   
   
    
   
   
    
   
   
   I'm sorry, I don't understand what you mean. Can you upload a picture to show what you are seeing?

**Comment by joluga1948** [comment]
[20220504-140859-1.jpg](https://postimg.cc/9RSch5p6)[ ] [](url)

**Comment by joluga1948** [comment]
https://i.postimg.cc/7hbDxh20/20220504-094432-1.jpg

**Comment by joluga1948** [comment]
https://i.postimg.cc/7hbDxh20/20220504-094432-1.jpg[](url)
In the two previous images, the mirroring does not open, (multimedia) and in the last one, the apps open in connect drive, if the screen opens, what happens is that it is unstable, sometimes it disconnects, the apps quite well ,thank you

**Comment by hufman** [comment]
If you refer to the Screen Mirroring icon in the Multimedia list not responding, this might be a limitation with ID4. ID5 works better with the trick I'm doing for these fake app icons, so let's focus on the circle icon in the ConnectedDrive Apps list.
Can you share a picture of how it looks after you click into the circle icon from the Apps list? Can you share an screenshot of AAIDrive's Car Information tab? There seems to be an incompatibility with EntryEvo_ID5 when sending large images, both with Screen Mirroring and with the Widescreen Map.

**Comment by joluga1948** [comment]
https://postimg.cc/w3Cddzzc
https://postimg.cc/mzPK0X65
https://postimg.cc/LJmwH6bf
These captures refer, thanks

**Comment by joluga1948** [comment]
https://ibb.co/VqqqVBv
https://ibb.co/52sgt4M
Hello, this is full screen, what happens to me is that, after a short time it goes away or cuts off, you have to connect the cable again, give permission and voilá, but it is not stable, I don't know the reason, thanks

**Comment by joluga1948** [comment]
Hello, this is full screen, what happens to me is that, after a short time it goes away or cuts off, you have to connect the cable again, give permission and voilá, but it is not stable, I don't know the reason, thanks
https://ibb.co/52sgt4M
https://ibb.co/VqqqVBv

**Comment by joluga1948** [comment]
HELLO, ANOTHER THING THAT HAPPENS TO ME, IS THAT WHEN I PUT ANY APPLICATION, LIKE GOOGLE, FOR EXAMPLE, AFTER A FEW MINUTES, IT DISCONNECTS, IT WILL BE PERFECT TO BE ABLE TO SOLVE IT, AND THE BIMMER SCROBBLER APK COMES OUT TO CLOSE THE APPLICATION, THANKS
https://postimg.cc/phLwQSX1
https://postimg.cc/YvyYqGLG

**Comment by hufman** [comment]
Bimmer Scrobbler is for the specific usecase of announcing what song your car is playing to the Simple Scrobbler app, and is not applicable to most users. Feel free to uninstall it!

**Comment by joluga1948** [comment]
Hello Walter, these screens have come out, to my satisfaction, I don't know if they are new activations or they were there before, the 3D map thing, it's nice but I don't know how the routes are set and if it is stable, besides, I get two scren mirroring circles, one is for this map and the other, for the mobile, it is like that, congratulations and thanks
https://ibb.co/yfGNpMT
https://ibb.co/qRSPW0m
https://ibb.co/n1WBPVW
https://ibb.co/W5SstBd
https://ibb.co/yYcGmGd
https://ibb.co/LNnq52d

**Comment by bogdan-calapod** [comment]
@joluga1948  The map you're seeing is the new Mapbox implementation that @hufman recently released to the Play Store version. It uses a "google maps-like" view and can provide basic guidance (e.g. just a line on the streets you need to follow, no "next turn" direction yet). I find it's very useful when navigating into places you roughly know where they are but need a bit of a refresher from time to time. In city driving especially it really helps!

The second screen mirroring circle is the standard Screen Mirroring addon that you already tested

**Comment by joluga1948** [comment]
Ok, thank you very much, let's hope it continues to improve.

**Comment by hufman** [comment]
These features do not exist, please submit feature requests as new Github Issues. This thread is about a screen mirroring technique, and map discussions belong in separate threads.

**Comment by joluga1948** [comment]
To install AAIdrive, which application on the list is valid? I have 1.3.2 installed, 1.4 is newer, does it provide any more information? Thanks
https://postimg.cc/fSDj79G6
https://postimg.cc/vcQwT2Nv

**Comment by hufman** [comment]
The version you are running (1.3.2-119) is 119 changes after the release of 1.3.2, and so it contains almost all of the changes that are included in 1.4.
There are only a [very few](https://github.com/BimmerGestalt/AAIdrive/compare/410aae5...1.4) changes between the version you have and the 1.4 release.

**Comment by joluga1948** [comment]
Hello, are they substantive changes, important or is it not worth changing to version 1.4? Thank you so much.

**Comment by hufman** [comment]
I'd say the biggest change is the music search history feature, and I like the loading spinner when browsing the music library. There's some tiny tweaks to the map to more fully-fill the BMW screen.

Please stop commenting on this closed, unrelated bug report: Use the Discussions tab for general questions, or open a new issue for any bug reports.
