### ISSUE TITLE
Music control while using Screenmirroring

### ISSUE THREAD

**Issue by Tuerkay** [BimmerGestalt/AAIdrive#447]
since i´ve got my new Samsung phone, i´m finally able to use ID6 native screenmirroring. Now i can use Google Maps on my idrive which works better than RTTI.
Sadly when using Screenmirroring, i can´t skip music with my steering wheel buttons.

Is there any way to still control music while using sreenmirroring?

**Comment by hufman** [comment]
Alas, those settings didn't help me.
I looked up my options, and I believe I have the correct options: `S6CP | Preparation Apple CarPlay` and `S6NW | Telephony With Wireless Charging`, but not the Hotspot. I have seen a screenshot of someone's Mini Countryman with the Wifi checkbox filled in, not sure what is different about their car...

**Comment by Tuerkay** [comment]
Last thing i can think about is iLevel. I´m not quite sure but i think you need at least software iLevel 18-03 on your entryNav2.
Could also be that it was 18-03 for carplay full screen. Not sure right now, since i´m not using Carplay and haven´t worked on Minis with ID5.
might be a stupid idea but did you try "update services" (a few times) in the ConnectedDrive section of the iDrive?
Maybe someone in the Bimmerfest forum might be able to help you.

**Comment by hufman** [comment]
Thank you for the tips, I'll try asking around in various forums.
But about your original concern, I think I can close this because it's regarding the official BMW Screen Mirroring functionality.
