### ISSUE TITLE
Screen mirroring

### ISSUE THREAD

**Issue by xaviugs** [BimmerGestalt/AAIdrive#455]
Hello, 

I'm using your extension for mirroring my mobile. Is possible to mirroring my mobile display using the full screen of my idrive car?

Thanks a lot.

**Comment by hufman** [comment]
I'm glad you're enjoying it! Because of the way that the screen mirroring pretends to be a car app, it is impossible (as far as I know) to remove the car's menu elements around the edges of the screen.
