### ISSUE TITLE
SmallIcon is missing for several notifications since Android 11

### ISSUE THREAD

**Issue by chriss158** [BimmerGestalt/AAIdrive#456]
The small icon is missing for notifications which are created with the Home Assistant Companion App (https://github.com/home-assistant/android) on Android 12.
Other apps like FairMail, WhatsApp do work. But I have absolutely no clue why it should not work for the home assistant app.

SmallIcon is set in the MessagingService here: https://github.com/home-assistant/android/blob/edc41424a0b3b842932cacdb8dc90f85e0e53aa7/app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt#L710

The small icon is set and also seen in the notification itself. But not in the car. I've noticed this issue since i switched to the pixel 6 pro with android 12 coming from android 10. Maybe this is a problem introduced with android 12.

I'm using the latest AAIdrive (1.3.1) and also the latest (and for testing purpose some older versions) HomeAssistant Companion App.

Let me know if i can do something on the Home Assistant Companion app, as i'm quite active there. 

Screenshots:
![PXL_20211105_194514380](https://user-images.githubusercontent.com/12832850/140570291-3da8b3df-d75d-4b6f-817e-d78c9f1cd136.jpg)
![Screenshot_20211105-204325](https://user-images.githubusercontent.com/12832850/140570296-ddbe287c-7f00-462e-8247-d80c68a51098.png)

**Comment by hufman** [comment]
Good morning, glad to hear that you are enjoying it! While I am also a Home Assistant user, I haven't tried out the app yet, so thanks for testing!

What I suspect is happening is that Android 11 locked down the ability for apps to view what other apps are installed on the phone and to get their names and icons. I had understood this to mostly mean the actual app icon, but it might also mean their app resources too. I'll try to set up the Home Assistant app in a simulated Android 11+ phone and check out what's happening!

**Comment by chriss158** [comment]
Thanks for taking the time to look at the issue 👍 

I don't know if this was introduced with Android 11. I did the jump from 10 > 12. So i first noticed this issue with Android 12. 

> What I suspect is happening is that Android 11 locked down the ability for apps to view what other apps are installed on the phone and to get their names and icons. I had understood this to mostly mean the actual app icon, but it might also mean their app resources too. I'll try to set up the Home Assistant app in a simulated Android 11+ phone and check out what's happening!

Yes i think so too. 
Today i noticed that the Blink app also does not have an icon. 
Maybe some apps do not set an specific icon (App icon?!). Now AAIDrive tries to get the notification icon (which maybe does not work because of now  with A12 missing permissions). And then AAIDrive will fallback to use the app icon, which is not set.

**Comment by hufman** [comment]
That's quite possible! I was thinking about what you said about FairMail and WhatsApp showing icons, and I believe that would explain it. Here's my [parsing code](https://github.com/BimmerGestalt/AAIdrive/blob/9acbe8aa6c44c3c7fc9c3b3166a0de9db4e5c2a1/app/src/main/java/me/hufman/androidautoidrive/notifications/NotificationParser.kt#L82) (apologies for the convoluted code)

The list icon can show several things: As an initial fallback it tries to load the notification's smallIcon. Next, if the notification has an image attached, it will use any discovered image as the side icon, which isn't the case here. Then, if the notification is coming from a messaging app, it will load up the icon representing that person, which is how FairMail and WhatsApp are working.
One more thing to confirm: If you click into the notification, do you see the icon and app name along the top of the window? The app's icon and name is displayed at the top of the details screen, instead of the list screen, but would be subject to the same app visibility restrictions that I think is affecting smallIcon.

There is a way to define a [list of apps](https://github.com/BimmerGestalt/AAIdrive/blob/9acbe8aa6c44c3c7fc9c3b3166a0de9db4e5c2a1/app/src/main/AndroidManifest.xml#L28-L60) that the system will reveal to the app. It may be the case that I can configure it to reveal all installed apps for the Github release. I don't think I would be allowed to post such a version to the store, however.

**Comment by chriss158** [comment]
> One more thing to confirm: If you click into the notification, do you see the icon and app name along the top of the window? The app's icon and name is displayed at the top of the details screen, instead of the list screen, but would be subject to the same app visibility restrictions that I think is affecting smallIcon.

Yup the icon is shown.

> There is a way to define a list of apps that the system will reveal to the app. It may be the case that I can configure it to reveal all installed apps for the Github release. I don't think I would be allowed to post such a version to the store, however.

Just tried that, but it didn't work, but maybe i did it wrong? 
![image](https://user-images.githubusercontent.com/12832850/140992967-9e0d86be-95d2-475f-bd67-982347e15d37.png)

**Comment by hufman** [comment]
Oh very curious!! If the app icon and name is displayed, then the package visibility is indeed allowing it.
That change to specifically grant access to the HA app looks correct, which further indicates that it's not the Android 11 package visibility change. Thank you for investigating!
I'll set up an emulator and poke deeper.

**Comment by chriss158** [comment]
I think you are right that it is due to the package visibility restriction introduced in Android 11, because it does work if i add the permission `QUERY_ALL_PACKAGES`.  But as you said thats not an solution, because of the play store restrictions.

**Comment by chriss158** [comment]
THANKS @hufman . Now it does work with the package query.
i used the debug version of the  Home Assistant app, which uses a different package  :man_facepalming: With the playstore version of home assistant it does of course work.

**Comment by hufman** [comment]
Ahaha that would make sense!
I would happily accept a PR with the `QUERY_ALL_PACKAGES` permission added to the [main manifest](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/AndroidManifest.xml) combined with a change to remove the permission from the [playstore manifest](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/play/AndroidManifest.xml). I think this will be the best solution until a [general fix](https://stackoverflow.com/q/69901436/169035) appears.

**Comment by hufman** [comment]
Excellent, thank you so much!

Unrelated:
As someone who works in the HA app, do you know if there is any API for other apps to control the Home Assistant app somehow? One [distant project idea](https://github.com/BimmerGestalt/IDriveConnectAddons#legacy-apps) is to repurpose the old Samsung Smartthings car app resources into a frontend for Home Assistant somehow. Let me know what you think!

**Comment by chriss158** [comment]
In fact, I've been thinking about taking this over. You have already implemented addon support for AAIDrive. So it should be perfectly possible to connect HomeAssistant.
Home Assistant itself (not the app) already offers a WebSocket API. This could be used for this purpose. 
The WebSocket API is currently being implemented in the Home Assistant app (https://github.com/home-assistant/android/pull/1884). Theoretically, this implementation of the API should be outsourced as a library, so that it can also be used for the Home Assistant integration in AAIDrive. 

Currently I have something similar built for me personally via app notifications. Works great :+1:

![aaidrive](https://user-images.githubusercontent.com/12832850/141016915-0fe5169f-86dc-4899-8d10-4a6d0fd4c7d2.gif)

**Comment by hufman** [comment]
@chriss158 Please look at [Hass Gestalt](https://github.com/BimmerGestalt/HassGestalt): I've implemented a Home Assistant OAuth and Websocket client and worked it into a car app over the last few weeks! I think it just needs a little more polish but it's shaping up pretty well for me so far, let me know what you think!

**Comment by chriss158** [comment]
> @chriss158 Please look at [Hass Gestalt](https://github.com/BimmerGestalt/HassGestalt): I've implemented a Home Assistant OAuth and Websocket client and worked it into a car app over the last few weeks! I think it just needs a little more polish but it's shaping up pretty well for me so far, let me know what you think!

Thats really **awesome**! Works great! Good work! 

I have many ideas in my head how to further improve the app. I have to write everything down and then create issues in the project. Maybe you should open the Discussions tab, so that we can talk there.

**Comment by hufman** [comment]
I look forward to hearing your suggestions :D

**Comment by chriss158** [comment]
> I look forward to hearing your suggestions :D

Sorry  for late reply. Have a look at the issue and the discussion tab 👍

**Comment by hufman** [comment]
I sincerely apologize, I hadn't actually configured email alerts for the repo, I replied to the discussion :)
