### ISSUE TITLE
Amazon Music playlist cover art

### ISSUE THREAD

**Issue by aphillips69** [BimmerGestalt/AAIdrive#458]
Hi,.

Just found your app and testing it. So much better than what BMW provide!

The issue I am finding with Amazon Music HD is that when playing individual track the coverart loads fine, but when playing one of their provided playlist no coverart is shown for each track.

Tested with Deezer and that works fine.

I assume searching for tracks, albums and playlist is not supported for these two apps? 

Thanks Alan.

**Comment by hufman** [comment]
Good morning, I'm happy to hear you are enjoying it!
That's very curious, that the coverart functionality would be different for different modes in the same app. I'll take a peek at what's happening and let you know!
Indeed the search functionality is autodetected based on the app, and very few music apps provide full search functionality for some reason, and instead rely on the Play From Search option.

**Comment by aphillips69** [comment]
Hey, yes great app, loving the extra functionality. I also need to do some more testing as getting some intermittent results, in some instances the cover art seems to work but not confirmed how or why yet. It seemed to work more consistently when app was in car mode, but I'll do some more testing and let you know. Alan Phillips.Optimal IT Solutions LimitedMobile: +44 7771 798 299 | Email: ***@***.***
-------- Original message --------From: Walter Huf ***@***.***> Date: 07/11/2021  17:34  (GMT+00:00) To: BimmerGestalt/AAIdrive ***@***.***> Cc: aphillips69 ***@***.***>, Author ***@***.***> Subject: Re: [BimmerGestalt/AAIdrive] Amazon Music playlist cover art (Issue #458) 
Good morning, I'm happy to hear you are enjoying it!
That's very curious, that the coverart functionality would be different for different modes in the same app. I'll take a peek at what's happening and let you know!
Indeed the search functionality is autodetected based on the app, and very few music apps provide full search functionality for some reason, and instead rely on the Play From Search option.

**Comment by aphillips69** [comment]
Hey,

Did a little more testing today.

General outcomes....

When using app car in mode with the pre-selected playlists it loads the coverart.
The app has to be in car mode or have the car mode setting on when it first connects to the car.

When using app with normal interface it doesn't load the cover art and when switching to car mode whilst still connected to the car that does not work either.

Hope that helps provide a bit more information.
