### ISSUE TITLE
Maps PhoneUI could trigger car navigation from a phone's Place Search

### ISSUE THREAD

**Issue by hufman** [BimmerGestalt/AAIdrive#46]

**Comment by hufman** [comment]
Navigation handler [dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/534/534.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.2-14-308a709-308a709215dca02b6ae3737bc1f24ba0947f7c97-nomap-nonalytics-release.apk)

**Comment by jezikk82** [comment]
Can you explain how to test it ?

**Comment by hufman** [comment]
This build adds the ability for the car to show up as a navigation link handler: certain Google Maps links can be sent to this app and it will start the car's navigation system to that destination.
I had originally planned to add a Place Search in this app to trigger the car's Notification, but I suppose the official Connected app already provided this.
The logic is easy enough to modify to support the Google Maps module, too.

**Comment by jezikk82** [comment]
I just checked and unfortunately I don't have this option in the app. Step to reproduce: start GMAPS -find place - share place - on the list there is no anAndroidAutoIDRive

**Comment by hufman** [comment]
Thank you for trying! It's only registered as a link handler, for certain Google Maps links that you find online which have a clear latlong or other query. The Google Maps Share functionality is separate and is much harder to parse into a location.

**Comment by hufman** [comment]
Working on a test branch with some new tricks, [try it out](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-gmap_popups-nomap-nonalytics-release.apk)! GMaps Notifications should popup in the car when they peek down from the phone's status bar, and you can now Share from GMaps to the car's navigation.
