### ISSUE TITLE
Request: Notification improvment

### ISSUE THREAD

**Issue by jezikk82** [BimmerGestalt/AAIdrive#468]
Hi,

Over time I see 2 potential notifications handling improvements:
1. When you have selected to present notification automatically (popup) add option to auto closure of the popup after X sec unless you take any action (e.g.rotate the idrive wheel)
2. Select app that present notifications in car, during longer trip you get a lot of different and not important notifications that disturb you while driving. DND is a partial solution (workaround) but it blocks almost everything.

**Comment by hufman** [comment]
Thank you for your suggestions!
There isn't a way to detect inputs on the popup screen, but I could easily always close the popup after 10 seconds or so.
As for customizing which apps can show popups, that request is already filed as #119 :+1:

**Comment by jezikk82** [comment]
At the bottom of the popup the is the envelop icon moving you to notification details in notification center. If you detect this that would be fine not to close if you move there, on other case would be fine to close the popup after 10 sec.
