### ISSUE TITLE
Unstable connection

### ISSUE THREAD

**Issue by WiesVHI** [BimmerGestalt/AAIdrive#471]
Hi all,

I downloaded AAIdrive primarly for the use of Spotify, but the app can't seem to keep a steady connection to the car.

F.e.: When I start the car (BMW X1) and go to media, all the apps are automatically loaded, but when I try to click on Spotify, nothing happens. I usually have to wait around 5 minutes until the Spotify app opens. At that time, I can browse and select new songs for a couple of seconds before the Spotify app "loses connection" again. All the songs in my current playlist will keep playing though - as the bluetooth connection itself is robust - but all the functions provided by the Spotify app are gone. I usually need to wait another 10 minutes for the Spotify app to start again before I can change the song; then the Spotify app "loses connection" again and so on and on ...

Has anyone had the same experience as I have, or does anyone know how to fix this?

Thanks in advance!

**Comment by hufman** [comment]
Hmmm that sounds similar to a problem I've heard from Huawei phones where the phone pauses AAIdrive shortly after connecting because it's in the background. To confirm, does the Spotify app in the car respond quickly if the screen is on and displaying AAIdrive? If so, you may need to adjust the battery saving options that your phone applies to AAIdrive.

**Comment by WiesVHI** [comment]
> Hmmm that sounds similar to a problem I've heard from Huawei phones where the phone pauses AAIdrive shortly after connecting because it's in the background. To confirm, does the Spotify app in the car respond quickly if the screen is on and displaying AAIdrive? If so, you may need to adjust the battery saving options that your phone applies to AAIdrive.

Hi,

Thanks for your reply! I disabled the battery optimization option for the AAIdrive app and the connection stability has indeed improved! Thanks for the great advice!

**Comment by hufman** [comment]
Great, I'm glad to hear that!
