### ISSUE TITLE
Request: Change tab to Car Info after successful connection. 

### ISSUE THREAD

**Issue by jezikk82** [BimmerGestalt/AAIdrive#477]
Is it possible to set AAId change active tab from default to Car Info after connection is established ?
Also, can the side panel be collapsed automatically at the same time ?

Where it can be done ?

Thx for info

**Comment by hufman** [comment]
I don't think this behavior would be ideal, that of switching to a different tab at some unpredictable time without user interaction.

If you'd want to try implementing it, you would first need to find a place in the UI code to observe the connection status and trigger the transition. For example, if you'd want to trigger it only while the Overview tab is open, you'd add something like this to the OverviewPageFragment:
```
viewModel.isCarConnected.observe(viewLifecycleOwner) {
    findNavController().navigate(R.id.nav_carinfo)
}
```

Alternatively, you could add it to NavHostActivity to move no matter what tab the user is in, perhaps in setupNavHeader, and it would look slightly different:
```
connectionViewModel.isCarConnected.observe(this) {
    findNavController(R.id.nav_host_fragment).navigate(R.id.nav_carinfo)
}
```

I believe this nav controller function will automatically close the sidebar, but you can manually call `(findViewById<View>(R.id.drawer_layout) as? DrawerLayout)?.close()` if not.
