### ISSUE TITLE
Google Maps should use Car Location by default

### ISSUE THREAD

**Issue by hufman** [BimmerGestalt/AAIdrive#48]
The car typically provides a GPS reading, and using it might be more accurate and would require one less permission prompt.

**Comment by ericgla** [comment]
There are quite a few people (myself included) who have retrofitted an NBT Evo (ID5/6) unit into an older car.  The downside to this retrofit is that the NBT Evo does not it's GPS signal internally via an antenna, they rely on the telematics module for GPS which is difficult to retrofit.

For these users it would be ideal to have the option of using the phone GPS position, not the car's position.

**Comment by hufman** [comment]
A test branch is up at car_gps while I decide on the final class types to commit to, in case someone wants to try it out!

**Comment by hufman** [comment]
@ericgla or anyone else in the situation of not having GPS in the car, could I ask you to install the [CDS Details app](https://github.com/BimmerGestalt/IDriveConnectAddons/releases/tag/latest_build) and tell me what the `navigation.GPSPosition` data point reads? I'd like to have the phone UI provide extra options if the car is detected to not have GPS, so I'd like to know what your data looks like :)
