### ISSUE TITLE
TIDAL artwork always showing the previous song cover

### ISSUE THREAD

**Issue by hufman** [BimmerGestalt/AAIdrive#502]
### Discussed in https://github.com/BimmerGestalt/AAIdrive/discussions/499

<div type='discussions-op-text'>

<sup>Originally posted by **E46Fanatic** January 12, 2022</sup>
Hello there.
First of all, a huge thanks for your work, this is nothing ahort of being just fantastic. Installed your app a few days ago and have been using it in my G31 and what a diference it makes!

I have one minor (but annoying) problem. So, i have enabled TIDAL in the AAIdrive app and when I play music, the art cover diaplayed is always of the previous song. There is no other other delay, the art changes with each song immediately, it just always shows the previous aong. Can I fix this somehow (or am I doing something wrong)? 

Also one question - I can still see in the apps list Spotify and it shows "Spotify" on my HUD when changing media source even if it plays TIDAL (I have actually disabled Spotify in the AAIdrive app). I suppose this is ok? Spotify is some kind of "main" app that the car can communicate with or something like that? 
Update: I think I have found your answer to this in another thread (in sense that Spotify is the only real app etc.) 

And one more minor question - the AAIdrive says that I have a NBTevo ID5, but I think I have ID6 in the 08/2017 G31, no? 

Would appreciate the help very much and thank you again, indeed. </div>

**Comment by hufman** [comment]
That is a curious bug @E46Fanatic! AAIdrive updates the coverart whenever the song metadata changes or the coverart switches between null and not-null. I suspect Tidal is sending the coverart for the previous song with the new song metadata, and then AAIdrive doesn't react when Tidal updates the new song's coverart.
Please try out [this branch's](https://github.com/BimmerGestalt/AAIdrive/tree/coverart_equality) [build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-coverart_equality-nomap-sentry-release.apk), which adds Bitmap equality checking and should resolve this. Let me know if it helps you!

**Comment by E46Fanatic** [comment]
> That is a curious bug @E46Fanatic! AAIdrive updates the coverart whenever the song metadata changes or the coverart switches between null and not-null. I suspect Tidal is sending the coverart for the previous song with the new song metadata, and then AAIdrive doesn't react when Tidal updates the new song's coverart. Please try out [this branch's](https://github.com/BimmerGestalt/AAIdrive/tree/coverart_equality) [build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-coverart_equality-nomap-sentry-release.apk), which adds Bitmap equality checking and should resolve this. Let me know if it helps you!

Thank you for your quick response. I installed this build and it helped, indeed! Now it works perfect, the proper cover of the song that is currently playing is shown!

One question - should I keep this build installed manually or when can I download the Google Play version (so that it updates automatically).

Thank you very much again! I really enjoy my BMW more with your app, this is fantastic.

**Comment by hufman** [comment]
Thank you for the confirmation! I merged it and clicked the button to push it up to the beta channel of the Play Store. You may need to opt in, if you haven't already, to be a Beta Tester to receive this version, and there may be a delay as the Play Store gets around to publishing it, but this fix should show up soon! You have to be a beta tester because the main release is paused while I finish final touches on the new Calendar feature.
Thank you for the testing and feedback!

**Comment by E46Fanatic** [comment]
> Thank you for the confirmation! I merged it and clicked the button to push it up to the beta channel of the Play Store. You may need to opt in, if you haven't already, to be a Beta Tester to receive this version, and there may be a delay as the Play Store gets around to publishing it, but this fix should show up soon! You have to be a beta tester because the main release is paused while I finish final touches on the new Calendar feature. Thank you for the testing and feedback!

Thank you for information!
Sure, glad it helped.

Thank you again for your work!
