### ISSUE TITLE
Connected Drive Services being Discontinued

### ISSUE THREAD

**Issue by sicktim** [BimmerGestalt/AAIdrive#504]
Hey, I understand that this app is reliant upon BMW Apps. However, the 2014+ claim is no longer valid since Connected Drive services are unable to be renewed due to the phase out of 3G networks (bmw will no longer renew). This gets rid of BMW Apps and subsequently your app. I used to have BMW Apps, but it has gone away. I hope there is a simple way to code it back in, but I can't find anything. Do you have any knowledge of how to reintroduce this feature or at least how to use your app in this situation?

I'm driving a 2015 BMW 2-series (F22).

**Comment by hufman** [comment]
Good morning! I too am disappointed by this change. As I understand it (from #475), the 6NR BMW Apps option can be coded into the car to remove the dependency on the subscription status. I don't know how to do this, and various forums seem to indicate that it's harder than just a Bimmercode session, but it appears to be a common remote coding activation to purchase. My 2015 car was a Mini, which didn't have telematics and so it came with 6NR from the factory, and so it would not have been affected by this 3G shutdown.
Let's continue discussion in #475 to keep all the threads centralized
