### ISSUE TITLE
Lost connection (when in calendar) and won't reconnect

### ISSUE THREAD

**Issue by E46Fanatic** [BimmerGestalt/AAIdrive#518]
Hi, so after updating my Samsung S10+ to Android 12, the app has been less stable (but mostly working, needed some restarts now and then etc). Today, I was playing with some apps in iDrive. When in Calendar, the Bluetooth connection (I think overall, because the screen mirroring, which I was using, was also lost) disconnected. Now I cannot connect with the AAIdrive app. Tried reinstalling the app, re-pairing the phone etc. The "App" in BT setting of the car is going ticked/unticked and the AAIdrive doesn't connect. Like it's trying to connect, but fails, and again and again.

In I drive, it also logged me out, I think. Because I switched off the car and on, and it briefly wrote "login" and went away instantly. And after that when pressing "options" in the connections menu, I can "log in", not "log out". Logged in, of course, still doesn't work. 

Otherwise, the Bluetooth connection works (like it should, but without "Apps", so without AAIdrive. So the MyBMW app is also working. 

Don't know if it was connected with being in "calendar" app in idrive, it might have been a coincidence, but I am providing as much information as possible. Also, before that I tried the "Update Services" in Drive, don't know whether it is relevant or not. 

Any idea what could be the problem? Or how to solve it? 

Thanks.

**Comment by hufman** [comment]
Good evening! Being in the Calendar app was indeed probably just coincidental (theoretically could have some extra memory pressure on the phone while searching through Calendar events, maaaybe).
The Apps icon in the car indicates the MyBMW tunnel status, not AAIdrive's connection status, so you'll want to try force-closing MyBMW and restarting it. It probably has some background connection service in a weird state, and the fresh start should help. Restarting the phone will have a similar effect, while also freeing up memory to delay future problems.
Let me know if that helps!

**Comment by E46Fanatic** [comment]
Good day, hufman!
Indeed, it may well have been a coincidence (and probably was). 
I tried restarting phone and car several times that night, didnt help.
Anyway, I uninstalled the AAIdrive and installed the older version (the one you uploaded when I had a problem with TIDAL artwork updates) and it worked normally the next morning - I dont know if the version difference solved it or my car/phone had a good night sleep. 
Will try the latest version from google play in a couple of days and will let you know if that one works or not. 
Thanks!

**Comment by hufman** [comment]
Let me know how it goes!

**Comment by hufman** [comment]
May I assume that you haven't experienced any problems since then? :)

**Comment by E46Fanatic** [comment]
Hello, sorry for not getting back to you, I remembered to update the app just yesterday and tried it today in my car, everything seems fine.
Thank you!

**Comment by hufman** [comment]
Thank you for the update! I'm happy it's working again!
