### ISSUE TITLE
No longer works with BMWs that have 3G modem

### ISSUE THREAD

**Issue by mbonus** [BimmerGestalt/AAIdrive#523]
This is certainly not an issue of the app, but now the BMW has sunset the 3G support for connected drive, there's no way for this app to work.  It has been intimated that you could use coding to add back the BMW connection assistant app, but I haven't seen any instructions on how to do that.

**Comment by hufman** [comment]
I am also concerned about this removal of functionality! However, I do not know how to code this functionality back into the car, so please watch on the [discussion thread](https://github.com/BimmerGestalt/AAIdrive/discussions/475) for future information.
