### ISSUE TITLE
Spotify - Now Playing List

### ISSUE THREAD

**Issue by j18hockey** [BimmerGestalt/AAIdrive#527]
First, I want to say I love your app. I'm not sure what I would do without the phone connection you created! Great job!

I've noticed that while playing music through Spotify some songs in a playlist don't appear to work. I see them via the iDrive menu or via the steering wheel controls, but I don't see these specific songs in the Spotify app (in the next up section). I know Spotify has a "hide unplayable songs" option. I wasn't sure if that could be related to the issue. 

I'm attaching 2 photos: a picture of the iDrive Spotify Now Playing list, a picture of the Spotify Now Playing list (android). In the images the song "Big Yellow Taxi" is the one that will not play (shows via the aaidrive interface but not in Spotify app).

I'm sorry if this is a repeat report; I wasn't able to find something close to what I was seeing. Thank you for everything you've done to create this great app!

Some other information
Device: Samsung S10+
Android: 12 
Spotify: 8.7.4.1056
aaidrive:1.3.2-37-1092d5a

![20220215_143543](https://user-images.githubusercontent.com/31166408/154139750-42e084a4-aaf5-4d40-8f77-67009346d9ff.jpg)
![Screenshot_20220215-143536_Spotify](https://user-images.githubusercontent.com/31166408/154139756-0df355eb-fc17-47bc-8812-a42502f01a17.jpg)

**Comment by hufman** [comment]
Thanks for the report!
What happens if you try to click the missing song? I suspect you are encountering #291, where a playlist song is shown but unavailable and so the skipToIndex has an offset based on the number of unavailable songs.

**Comment by j18hockey** [comment]
When I click the unavailable song it skips to the next. Sounds like 291 exactly. Sorry for the duplicate report!

**Comment by hufman** [comment]
Perfect, hopefully a solution can be figured out for this bug!
