### ISSUE TITLE
Map drops

### ISSUE THREAD

**Issue by unlive74** [BimmerGestalt/AAIdrive#536]
Thank you for this opportunity to test the maps. This is wonderful. First bug report: maps are falling. Sometimes with Spotify
view from 9:24 [logcat_02-22-2022_09-29-02.zip](https://github.com/BimmerGestalt/AAIdrive/files/8113718/logcat_02-22-2022_09-29-02.zip)

**Comment by unlive74** [comment]
I'll try tomorrow morning (it's already night now) to reboot the phone and try again. Strangely, when the cards dropped, there was no disconnect, just the cards logo disappeared in the ConnectedDrive menu and then appeared again.

**Comment by jezikk82** [comment]
Hi, I compiled my own version with added keys to mapbox but in the app/car I don't see any options about mapbox, only gmap. Can you add instruction on how to have gmap and mapbox in car.

**Comment by hufman** [comment]
Similar to the gmap build variant, the mapbox code adds a mapbox option to [the Build Variants panel](https://bimmergestalt.github.io/AAIdrive/images/developer-variants.png). They share the same unlabelled icon in the car and have roughly the same features and options, but the map and search results come from the respective gmaps or mapbox libraries. I do need to add an icon to the Map tab in the phone UI as a clue to what brand is providing the maps data.
Do you see the mapbox options in the Build Variants panel? You might need to use the File>Sync with Gradle option to update the list.

**Comment by jezikk82** [comment]
I see mapbox option in build variants. Will test it today. 

Is it/Will be possible to have both maps present in car ? So you can choose on the go, what to use.

**Comment by hufman** [comment]
No, supporting both map providers in the same build is not planned. Of the few people who are inclined and capable of building the gmap build, very few would also want to also include the lower-quality mapbox information.

**Comment by unlive74** [comment]
hmi.type: BMW ID6L
hmi.version: EntryEvo_ID5_2007_Release ID5_2007-510-2012A Build 33 - Rev:210125 2020-03-12 10:34:41
navi: false
tts: false
vehicle.type: F39

**Comment by unlive74** [comment]
hmi.type: BMW ID6L
hmi.version: EntryEvo_ID5_2007_Release ID5_2007-510-2012A Build 33 - Rev:210125 2020-03-12 10:34:41
navi: false
tts: false
vehicle.type: F39

**Comment by hufman** [comment]
I wonder, is it a memory pressure thing, causing MyBMW to lock up? My Galaxy S9 with 4GB of ram hasn't experienced this problem ever. Does it work slightly better after a fresh reboot of the phone?

**Comment by berseker** [comment]
![Screenshot_20220331-214141_AAIdrive_1](https://user-images.githubusercontent.com/1159431/161136263-4b75821b-da97-4c01-a740-682c24d3ef49.png)
I have the same behaviour reported by unlive74.. phone Is a redminote 7 by Xiaomi, 4gb ram

**Comment by unlive74** [comment]
By the way, I still use MyBMW 1.4.3, later builds periodically do not start a connection with the car until I launch the application on my smartphone. All greens are off. I think 4 Gb is critically small.

**Comment by bogdan-calapod** [comment]
> When viewing the map and playing in Spotify today, entrynav2 froze - the sound disappeared and the image of the map froze. At the same time, when I turned off the bluetooth on my Samsung s8, entrynav2 remained the same, only restarting entrynav2 helped. Maybe my old phone is running out of memory? [logcat_02-26-2022_11-34-01.zip](https://github.com/BimmerGestalt/AAIdrive/files/8147300/logcat_02-26-2022_11-34-01.zip) around 11:32

Also encountered this while using screen mirroring with Spotify in the background. I'm going to try with YouTube music - maybe there's some memory leak with Spotify?

Galaxy S21 5G
Android 12
OneUI 4.1 with 8 GB RAM + 8GB RAM Plus setting

**Comment by bogdan-calapod** [comment]
@unlive74 by any chance do you also have a SmartWatch linked to your phone? I'm thinking maybe the Bluetooth connection can't handle a watch and the idrive connection in parallel?

**Comment by bogdan-calapod** [comment]
Hmm, I'm on My BMW 2.3.3 (latest) and except from when running screen mirroring or the new integrated map I've never had OOM errors

**Comment by berseker** [comment]
I have same issues of unlive74, i have usually a MiBand4 Always connected with the phone. I noticed that of i use mirroring or Mapbox only, usually i have no issues. Of i listen my MP3 collection with musicolet at the same time, 90 % of times i get some freezing as described by unlive74, or sometimes the music goes on but the system Is freezed ( no Song swiching, no cover changing on id6 tiles, no possibility to change connected app..) Sorry but up until now my phone does not have root anymore so i struggle to get good output from logcat

**Comment by bogdan-calapod** [comment]
@berseker I'm seeing the same behavior, even with YouTube Music, might be something related to playing music whilst doing casting causing a memory leak?

**Comment by bogdan-calapod** [comment]
@unlive74 @berseker by any chance do you also use widgets on your home screen?

I have quite some widgets set up, maybe they fill up the memory and the os prioritizes them for some reason?

@hufman do you use many widgets on your home screen?

**Comment by hufman** [comment]
I use no home screen widgets on my Galaxy S9

**Comment by berseker** [comment]
I use only the Google search bar widget.. in any case i really would like to help more but i noticed that my phone not rooted basically gives me a logcat of a Few seconds , It doesnt show any history.. do you have suggestions to give me? (Or i must root the phone?)

**Comment by hufman** [comment]
The logcat buffer size can be adjusted from within the [Developer Tools section of the Settings](https://pspdfkit.com/blog/2018/how-to-increase-the-logcat-buffer-size/#via-the-ui).
Have you noticed any correlation between the Widescreen mode of the map and the crash chances? I wonder if (especially for @unlive74's headunit crash) the JPG file size is using up too much memory in the infotainment system, and perhaps it might crash less often if the JPG is smaller and not-widescreen. Perhaps @berseker's car has a slightly newer version and so it only restarts the Bluetooth connection of his car in this situation instead of locking up entirely.

**Comment by unlive74** [comment]
I have 2 widgets - weather and google search. The size of the map does'nt affect the freezes, the map hangs in the same way, sometimes it happens if spotify or another music source is turned off. Soon I'll need to go to the dealer, I'll ask him to update the program in my Entrynav2, maybe it will help. Although the correct and logical step is to change the phone, 4 Gb is too small.

**Comment by berseker** [comment]
As far as i can are, unlive74 hmi release Is more recent than mine

**Comment by bogdan-calapod** [comment]
Went for a short drive with the older screen mirroring apk (the one with the smaller display view) with YouTube (not music) in background and after disabling the Samsung adaptive battery. 

Happy to report that I haven't experienced any background crashes.

**Comment by bogdan-calapod** [comment]
So I drove around a couple of hours with waze via screen mirroring (small window) and it worked just fine, meanwhile the large map or large version of screen mirroring always locks up after a couple of minutes or so - I feel like the problem is related to processing the larger image somehow 🤔

**Comment by unlive74** [comment]
@bogdan-calapod And what happens in those few minutes before the app freezes? It seems to me if the problem is in large files, then this should happen faster?

**Comment by bogdan-calapod** [comment]
Music stops if it is playing, and afterwards it seems that the car gets really confused and can't connect to any Bluetooth devices anymore unless a reboot is done. 

Disconnecting works but reconnecting keeps sending `Another Bluetooth operation is in progress` messages until I stop the car and leave it off for a couple of minutes so that iDrive reboots.

By large files, are you referring to the large "view", as in the larger transfer that the phone has to do to the car ? 

The fact that the car also locks up makes me think that there's something going wrong on the car side as well, somehow. Maybe the amount of data is too much for the car's Bluetooth to handle ?

@hufman would it make sense that USB Apps connection would *not* cause issues if the problem is the large "file size" ? I'm going to test this out tomorrow 🤔

**Comment by hufman** [comment]
I'm not sure! Both the map and the screen mirroring send higher quality JPGs over USB, so the filesize theory would suggest it should happen faster over USB. Otherwise it's the same protocol and same commands that are being sent to the car...

**Comment by bogdan-calapod** [comment]
So if it happens faster with the large map over USB, or if it happens over USB even with the small mirroring screen, it would mean that one possible solution would be to lower the JPEG quality, right ? 

I'll test out today and get back with results

**Comment by bogdan-calapod** [comment]
I'm seeing the same behavior on USB as well 😕

**Comment by bogdan-calapod** [comment]
Disabled wide screen map and 3d buildings and it worked great for a 30min drive, whereas before it would lock up - so it's clearly something to do with processing the larger JPEG image

**Comment by hufman** [comment]
Try out this [experiment build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-map_delay-mapbox-sentry-release.apk) which adds a 30ms delay after each frame, to see if that gives enough time for the car to flush out whatever buffers and not crash. It should be a negligible change, especially over Bluetooth!

**Comment by unlive74** [comment]
I tried this assembly - 10 minutes I enjoyed life, then - everything is as usual. :(

**Comment by bogdan-calapod** [comment]
Seems to work a bit better for me, at least for a short drive. Only thing I see is that the map window is a bit smaller now compared to the store version 
![Uploading 20220419_145020.jpg…]()

**Comment by hufman** [comment]
Thank you for the help testing! I am still entirely unable to reproduce this bug :( Do we think that the slight delay in framerate causes enough of a benefit to be merged to the main branch? Does the normal build last the same 10 minutes or much shorter? Does it work better if you close the window every so often and go back to the map?

The map size difference is because the store version has the bmw_xl branch currently, while this map_delay branch is right off of the main branch.

**Comment by bogdan-calapod** [comment]
For me it doesn't seem to make a big difference, but if it helps with performance in some cases while not changing anything in others, I'd say it's a good idea to merge it.

Does the same change apply to screen mirroring, or would that add-on need to be updated separately?

**Comment by bogdan-calapod** [comment]
So the lockup issue is somewhere in the maps part of the app? I'm seeing the same lockup with the latest screen mirroring apk (the one that made the display bigger) but it works perfectly for pretty long drives with the original smaller display version.

In my testing I've only seen the issue in the maps with the wide-screen option turned on, so I'm thinking the bug would be in the RHMIDimensions library?

**Comment by hufman** [comment]
That's an interesting correlation! Screen Mirroring doesn't have the widescreen option, always going as big as possible, and it's interesting that Screen Mirroring only started having troubles after getting bigger, while the not-widescreen map never has troubles.
The change to expand Screen Mirroring didn't fully involve a change in RHMIDimensions, it mainly just [started applying negative-padding](https://github.com/BimmerGestalt/IDriveConnectAddons/commit/f4347f2) like the map does.
I'm still leaning towards something about the jpg or image size. Does the problem seem related to image complexity and JPG quality? Does it happen more often over USB (which has a higher JPG quality and thus byte size), or with satellite view (very complex image)? If not, it might be only related to decoded image size in some way.

**Comment by bogdan-calapod** [comment]
I couldn't see any corellation between the amount of detail in the image and the crash rate - @unlive74 what is your experience?

**Comment by hufman** [comment]
Try out [this test build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-map_withoutpadding-mapbox-sentry-release.apk) that reduces the screen height and doesn't display under the top statusbar of the car. It's about 60px of reduced height, multiplied by the width of the screen, and might change how often the car headunit crashes.
@bogdan-calapod what IDrive version are you running? I'm still trying to figure out a pattern, so I know whether to add this workaround automatically or what.

**Comment by berseker** [comment]
I tested the same as bogdan & I can confirm that with "small" map (not fullscreen), via bluetooth only, also listening MP3 music via Musicolet all the time, I drove around 45 km without any issues with normal map, satellite image map, 3d buildings on & off. So as per my experience, there is something strange with fullscreen map going on

my test was run with release 1.3.2-119-ec19e73-custom_dimensions 13 apr 2022 03:11:11

@hufman you posted while I was writing. I will try this new build & report

**Comment by bogdan-calapod** [comment]
I'm on EntryEvo_ID5_1907_Release (would be nice to be able to copy this from the car info screen 😅) I think it's the same as the one @berseker runs, as we had similar behaviors multiple times

**Comment by unlive74** [comment]
Now I tested the build 1.3.2-119-1879e2c-map_withoutpadding. I removed the 3D buildings, leaving only traffic.The fullscreen map fell immediately - literally 10 seconds after the start. After that, there was a problem with establishing a bluetooth connection: it wasn't possible to connect with "apps" - rebooting the phone didn't help, it was solved after removing the bluetooth connection and re-pairing. And by the way, this is not the first time I have to do this shamanism after the cards freeze. The small card worked fine for about an hour.

**Comment by bogdan-calapod** [comment]
Same here - worked for ~2 minutes in wide-screen mode and then crashed. Half width map seems more stable (went for a pretty short drive so can't say it won't crash, but for 10 minutes it worked okay

**Comment by bogdan-calapod** [comment]
@berseker what phone are you using? Any special settings?

**Comment by berseker** [comment]
Xiaomi Redminote 7 with custom android 11 rom (arrowOS)

**Comment by hufman** [comment]
I added a warning in the Phone UI if the car is detected with EntryEvo, saying that widescreen mode might be unstable, which should be enough of a disclaimer to unblock the release. I haven't heard of any other models that are having these troubles, even with Mapbox saying there are currently 120 monthly users.

**Comment by hufman** [comment]
@berseker If I read your messages right, those screenshots with the cut-off compass are from your test with map_withoutpadding, which makes sense to me. The bmw_xl branch has the tweak for the sidebar width, which was included in custom_dimensions but not map_withoutpadding.

**Comment by berseker** [comment]
@hufman yes sorry for the confusion, I confirm the last screenshots have been taken from release 1.3.2-119-1879e2c-map_withoutpadding 20 apr 2022 20:32:44

**Comment by unlive74** [comment]
Yesterday I assembled a build with google maps, today I tested it. The widescreen map crashes 1-2 minutes after the start, but the symptoms are different: if mapbox hangs EntryNav when it crashes, then google maps freezes and reconnects bluetooth - within a minute the connection is restored.
A couple of remarks - it's bad that you can't tilt the map. And the size of the map on my screen...
![20220425_092516](https://user-images.githubusercontent.com/75434533/165075494-f203c003-86e7-42a7-8026-7226fe3e7ab4.jpg)
![20220425_093102](https://user-images.githubusercontent.com/75434533/165075516-5a30ee96-4e1e-4cc0-8ebe-d39ee568ba4a.jpg)

**Comment by hufman** [comment]
Indeed, I mostly stopped development on the gmaps variant since mapbox will be used by many more people, and the bmw_xl branch has yet to be merged. I'm planning to merge it this week though!

**Comment by berseker** [comment]
> I used it for around 20km (short trip) but without issues. I will further test since it seems it works only for me ;D I noticed only some minor "adjustments" that may be fixed, see below picture.
> 
> ![image](https://user-images.githubusercontent.com/1159431/164505124-801e37a1-28f3-4249-8742-dd8e62f4f0d1.png)

I confirm I still did not had a single crash with version  1.3.2-119-1879e2c-map_withoutpadding 20 apr 2022 20:32:44 used mostly in fullscreen mode via bluetooth.

usually when I had issues, I got crashes sometimes instantly at time of map opening

**Comment by bogdan-calapod** [comment]
After running the Force Stop Apps app I have driven about 15 minutes with the wide-screen map on and it didn't crash. Will test out a bit more tomorrow.
