### ISSUE TITLE
Spotify Navigate menu

### ISSUE THREAD

**Issue by KdiKomunismo** [BimmerGestalt/AAIdrive#549]
Hi there, in the last update (1.3.2-77) Spotify Navigate menu changed in a way that makes it impossible to find your library.
I'm using Spotify last version (8.7.8. 1206) on a Mi 9t, and a 2017 bmw 418d with id5

**Comment by hufman** [comment]
Hmmm there haven't been any changes in that section of code for a while, can you share a screenshot or video that demonstrates the issue you are seeing?

**Comment by hufman** [comment]
Interesting! Mine doesn't show a change (you can test without going out to the car by clicking the Spotify icon in the Music app of the phone UI).
What version of Spotify are you using, and do you have Spotify Premium? My Spotify Premium on version 8.5.72.800 shows the expected entries (Recently Played, Your Library, Browse).

**Comment by TBGR** [comment]
I see this  new behavior when I haven't connected the phone to my hotspot.

**Comment by KdiKomunismo** [comment]
> Interesting! Mine doesn't show a change (you can test without going out to the car by clicking the Spotify icon in the Music app of the phone UI). What version of Spotify are you using, and do you have Spotify Premium? My Spotify Premium on version 8.5.72.800 shows the expected entries (Recently Played, Your Library, Browse).

I see the same in the music app (see attachment).
I have Spotify premium, version 8.7.8.1206

![IMG_20220307_223950](https://user-images.githubusercontent.com/78843133/157122293-ba5db838-bcd2-4448-b8ff-f1e4aa761444.jpg)

**Comment by hufman** [comment]
That's very curious, because the last change to any of the music app logic (such as the Spotify api) was [January 13](https://github.com/BimmerGestalt/AAIdrive/commits/main/app/src/main/java/me/hufman/androidautoidrive/music), and so reverting the version should not have mattered. I'll watch to see if my Spotify updates to this new 8.7 version soon so I can see what's going on!

**Comment by daniel1v** [comment]
I am experiencing the same issue with the latest nightly of aai. With the official Playstore version, everything works fine for me.

Unfortunately I cannot say, when it started, because I didn't update for several weeks.

**Comment by DominikS66** [comment]
Same problem here. I will test different versions.

**Comment by KdiKomunismo** [comment]
Don't know if it's related, but I'm also noticing way more disconnections than before.
I usually had one or two disconnections every couple of hours, now I have 5-6 in the same time

**Comment by hufman** [comment]
I'm very confused on why switching the version of AAIdrive would change anything. The current production Play Store release is built from bd04b8e from Feb9 (the beta version is 9e14a19 from March2), which both were after any change to the music code on [January 13](https://github.com/BimmerGestalt/AAIdrive/commits/main/app/src/main/java/me/hufman/androidautoidrive/music) and definitely after any Spotify-specific changes on [December 22nd](https://github.com/BimmerGestalt/AAIdrive/commits/main/app/src/main/java/me/hufman/androidautoidrive/music/spotify). Of course you should check what version you see in the Support tab, but those should be the expected versions.
My guess is that uninstalling and reinstalling resets some cache that Spotify provides (AAIdrive itself does not have any browse caching). The Play Store and Github versions have different signing keys, and perhaps Spotify is caching based on that key.
I wonder if they changed the name of the root directory? The [code](https://github.com/BimmerGestalt/AAIdrive/blob/8ed902470fe4d4dc0b64b3b6c2c7646b79988e02/app/src/main/java/me/hufman/androidautoidrive/music/controllers/SpotifyAppController.kt#L744) currently requests `default-cars`, which no longer appears in the [list of options](https://spotify.github.io/android-sdk/app-remote-lib/docs/constant-values.html#com.spotify.android.appremote.api.ContentApi.ContentType.AUTOMOTIVE). Trying out some of the new values (against my 8.5.72 Spotify version) has some interesting results:
  - `automotive` and `default` show the new Discovery style list for me that you see, so I wonder if requesting the old `default-cars` on your newer Spotify version is falling back to this option
  - `default-cars` shows the previous Recently Played, Library, and Browse options for me
  - `fitness` shows Recently Played and a folder of various curated workout playlists
  - `navigation` shows Recently Played, a Daily Drive playlist, a Songs to Sing in the Car playlist, and a Made for {user} folder of Daily Mixes
  - `sleep` has Recently Played and then a selection of other folders: Popular Sleep Playlists, Nature Sounds, Ambient Sleep Sounds, and ASMR
  - `wake` has Recently Played and a selection of other folders: Rise and Shine, Lazy Mornings, Right side of the bed, and Morning Workout
I think Spotify has removed this `default-cars` root directory from the new version, and so we'll have to hardcode the desired entries in the root. In my browse, the `default-cars` returned the entries [com.spotify.recently-played, com.spotify.your-library, com.spotify.browse], so it should be doable to slip those into the results (perhaps added to the `navigation` list.

**Comment by hufman** [comment]
Please try out [this test build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-spotify-automotive-mapbox-sentry-release.apk) of [this branch](https://github.com/BimmerGestalt/AAIdrive/tree/spotify-automotive). It works for me, and I just want confirmation that it works for you before I merge it!

**Comment by JutPie** [comment]
Can't test while in car, but in App for me it shows the "new" browsing menu.

![Screenshot_20220312-214914_AAIdrive](https://user-images.githubusercontent.com/92263103/158034609-bb71a3a1-a9e4-4d8e-a9d9-21c6d4b62cdd.jpg)

**Comment by hufman** [comment]
Perfect, thank you so much!

**Comment by KdiKomunismo** [comment]
I'm also trying without the car, but it works like a charm
![Screenshot_2022-03-13-00-17-14-706_me hufman androidautoidrive](https://user-images.githubusercontent.com/78843133/158038346-1037b080-8420-4fdf-99f5-1fd2ab538238.jpg)

**Comment by hufman** [comment]
Excellent! It's now merged to the main Github build, and so I'll let it sit for a few days to get translated before pushing it out the store.
