### ISSUE TITLE
Radarbot calls my phone

### ISSUE THREAD

**Issue by Lostnode3000** [BimmerGestalt/AAIdrive#554]
Hi,
Since BMW Navi doesn't have speed camera alert I have used radarbot for alerts only.
This worked great as I use my Samsung watch for the notifications and therefore don't need the phone to be visible.

But ever since I started to use AAIdrive Radarbot starts a hands-free call from my phone to my phone (calls my number) when ever there's a speed cam. 

I'm not sure if the call is triggered from the car or from the phone. But it's just as if I made a call using handsfree.

If I end the call it starts a new one emediatly and this repeats until I've passed the camera.

Very strange and extremely annoying.

I really like BMWs Navi but do need something to alert me about cameras, so for now I use Waze in parallell.

Is there a logical reason for this and is there a get around? Something else I can use for speed camera alert?.

**Comment by hufman** [comment]
That's quite a puzzle! AAIdrive doesn't set up any phone calls or anything like that, and the Reading Out of Phone Notifications relies on the car's TTS support as opposed to using a Bluetooth phone call.
Is it just coincidence? Perhaps Radarbot updated to add this feature right around the same time as when you started using AAIdrive; does it still do it even if AAIdrive isn't connected? You can Force Stop AAIdrive and it will stay disconnected until the next time you open the app or until MyBMW next reconnects to the car (if Notification support is enabled).

**Comment by Lostnode3000** [comment]
Well, you certanly are right!
With both AAIdrive and myBMW apps forced off Radarbot still calls me.
So something probably happen to Radarbot app in some upgrade since this has not always been the case.

Since Radarbot  seems to be a popular app I'm surprised to not find any information from other users though.

I'll continue to investigate...

**Comment by JutPie** [comment]
I don't use Radarbot but in Germany there is a similar App BlitzerPlus. In this App it is possible to change the Bluetooth Audio Profile. With A2DP I get the Radar Warnings with the "normal" Audio Context and with Profile HFP the App sends a call / simulate an audio call and use this way to play Audio. Perhaps this can help you.

**Comment by Lostnode3000** [comment]
> I don't use Radarbot but in Germany there is a similar App BlitzerPlus. In this App it is possible to change the Bluetooth Audio Profile. With A2DP I get the Radar Warnings with the "normal" Audio Context and with Profile HFP the App sends a call / simulate an audio call and use this way to play Audio. Perhaps this can help you.

Thanks for the tip. But unfortunately I can not find any similar options I Radarbot. I'll keep trying alternatives...

**Comment by hufman** [comment]
I believe this is good to close, it sounds like a car interaction with Radarbot and not related to AAIdrive. Hopefully the Radarbot team can figure it out with you!
