### ISSUE TITLE
Overall Spotify library is missing

### ISSUE THREAD

**Issue by MioSto** [BimmerGestalt/AAIdrive#559]
Hi everyone

First of all: THANK YOU!! I stumbled across this app in a forum and am so happy that I can finally use Spotify in my car again. It is fantastic!

It seems there was an update in the app (and there was also an update on my S21 phone). Yesterday, it was not possible to "allow access to search library" which was probably due to changed settings in energy saving. Once I changed back, the library access was back and I noticed some great new short cuts (personal playlists, podcasts etc.) - I do like those. Unfortunately, the overall view of the library is gone. I cannot see the downloaded or "marked" albums anymore; I only see playlists, podcasts, some recommendations etc. In my humble opinion this is THE key feature. Any chance this is coming back or need I change something?

Again: thanks a lot for this app. It is great!

**Comment by hufman** [comment]
Good morning! I'm glad you enjoy the browse feature, it's one of my favorite aspects!
It sounds like your Spotify updated to version 8.7 and you are encountering #549. What version are you running? I added a workaround in version 1.3.2-85-4891cd2, and the Play Store Beta Test build and the Github nightly build include this fix. I'm getting close to releasing version 1.4 as the main build, and this fix will be included there too!

**Comment by jagerx9** [comment]
Seeing the same thing here. It's basically reading the new Spotify "browse" page which btw is incredibly annoying if you just want to get to your music (thanks Spotify).  So it's not on AAIDrives end and is a Spotify problem. Still probably needs a workaround unfortunately

**Comment by hufman** [comment]
Indeed, thank you for the confirmation! The workaround is implemented in code and is available in the nightly builds and in the Google Play Beta program.

**Comment by jagerx9** [comment]
Grateful as always!

> Indeed, thank you for the confirmation! The workaround is implemented in code and is available in the nightly builds and in the Google Play Beta program.

**Comment by MioSto** [comment]
Hi hufman
Sorry for my late response. The messages went into the spam-box...
I am using version 1.3.2-34-bd04b8e and Spotifiy version 8.7.18.1138.
Correct, I am having the same issues as #549. It shows the "Start" menu instead of the "library". The start menu is ok if there are both options, but if you can't switch the start menu is useless because I then cannot find safed albums or artists via the search function. Strangely, it is not all the time. I have not yet figured out when it happens. Maybe if Spotify is alreday active before I'm starting the car.

**Comment by hufman** [comment]
Version 1.4 has been released and should include a workaround, do you still experience the missing Library?
