### ISSUE TITLE
Suggestion: Add geolocation bias to places search

### ISSUE THREAD

**Issue by bogdan-calapod** [BimmerGestalt/AAIdrive#569]
Hey there,

The custom Mapbox implementation works great, but one thing that I'm having a bit of a hard time with is the fact that, when searching, destinations in location thousands of kilometers away from me show up, making it hard to filter out the ones close to me that I'm actually interested into.

From what I've researched I've found that [mapbox can bias the search results to a certain region](https://docs.mapbox.com/help/tutorials/local-search-geocoding-api/). I'm thinking that adding a toggle to bias the search results to the location of the user (+ a certain range, let's say 100km) would go a long way to improving the search result functionality (and also reducing the API calls maybe, due to fewer erroneus searches ?)

Alternatively,  I'm thinking that pasting a Google Maps URL somewhere and extracting the GPS coordinates from that would also work, but maybe I should make a separate issue with this

Thanks for a great app!

**Comment by bogdan-calapod** [comment]
> In fact, the code is shared and you could actually paste a Google Maps link right into the Navigation search box and it will work too.

Ah, I didn't know that - nicem will come in handy. Does pasting Google Maps links to the "Favorite Destinations" input work as well ?

> If you have a (free) Mapbox account, can you play around in the [api playground](https://docs.mapbox.com/playground/geocoding/) to see if their search api provides the expected results there? I believe I'm sending the right parameters, and the app shows the closest Starbucks for me, so I'm not sure why it's not behaving as expected for you.

I'll play around with it - for me for certain searches it is retrieving one or two POIs close to me, then something way over in Bangladesh. Maybe it's not finding anything in between and falling back on that ?

**Comment by hufman** [comment]
Indeed, the favorite places are just strings and should work, though ugly!
I can't guarantee the search quality of this service, I apologize 😬

**Comment by bogdan-calapod** [comment]
Okay, then I think we can close this issue :D
