### ISSUE TITLE
Missing text description in bmw id6

### ISSUE THREAD

**Issue by ccotyc** [BimmerGestalt/AAIdrive#572]
![20220510_163202](https://user-images.githubusercontent.com/95678665/167811161-7a813db4-d5e3-4fba-9cb7-937f5c668007.jpg)

**Comment by ccotyc** [comment]
The last 2 are Screen Mirroring and Maps ...

**Comment by hufman** [comment]
That is a limitation of the protocol, unfortunately. The app must log in to the car with previous BMW apps and using those previous apps' icon and text resources. The Map and Screen Mirroring apps are using the old Samsung SmartThings app, and the label is hardcoded to say SmartThings if the app's text resources were sent to the car.
