### ISSUE TITLE
Can't permit Spotify library permissions with Gmaps build

### ISSUE THREAD

**Issue by fame4k** [BimmerGestalt/AAIdrive#574]
Hey. 👋 First of all, thanks for the App, I love it. 

Okay, heres my problem, I compiled myself a Google Maps build, everything works fine with it. The only thing that's not working as it should is Spotify.

I'm unable to give AAI permissions to search through my Spotify library, whenever I try to I get the following error:
`E/SpotifyAppController: Failed to connect to Spotify Remote: com.spotify.protocol.error.SpotifyAppRemoteException: Result was not delivered on time.
`

Everything worked fine with the Play Store & GitHub versions, so I don't really know what's wrong.

-APKs used from [README.md](https://github.com/BimmerGestalt/AAIdrive/tree/main/external)
-Spotify API key is set
-URL redirect is: me.hufman.androidautoidrive://spotify_callback
-SHA1 Fingerprint should be right & package name is: me.hufman.androidautoidrive 

I hope you can help me! :)

![grafik](https://user-images.githubusercontent.com/53906409/168609946-35b3d845-9ea7-497c-831b-6113b02bddcc.png)

**Comment by fame4k** [comment]
Hey! Thanks for the quick answer! 👍 

I don't know why but everything works without any issue now, I didn't change anything, weird.
Maybe it takes some time to update when you enter a new Client ID/SHA1 Fingerprint.

**Comment by hufman** [comment]
Very good, I'm glad that it's working :)
