### ISSUE TITLE
Navigation Map resolution issue

### ISSUE THREAD

**Issue by ilross02** [BimmerGestalt/AAIdrive#580]
The fullscreen resolution of the mapbox is the following:

Display res: 480x800
![Screenshot_20220530-142815](https://user-images.githubusercontent.com/85498763/170992635-f0db7542-e68e-4dbc-b9d4-c6e96e7a6a6c.jpg)
![PXL_20220530_122752120](https://user-images.githubusercontent.com/85498763/170992643-2edf3b59-3525-4cf0-a800-47456405f22d.jpg)

What to do to make it fill the empty right and bottom sides?

Thank you!

**Comment by hufman** [comment]
Can you turn on Advanced Settings and send me the hmi.display-width and hmi.display-height information from the Car Information tab? EntryEvo infotainment lies a little bit about the screen size, and we have previously seen it lie about the 1440x540 screen being called 1280x480. It looks like yours is saying it's 800x480 but clearly it's bigger.

**Comment by ilross02** [comment]
![Screenshot_20220531-001104__01](https://user-images.githubusercontent.com/85498763/171063678-eee9c22c-6f9a-4678-b987-36a96fa25f80.jpg)

These?

**Comment by hufman** [comment]
Try [this test build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-bmw_xl_small-mapbox-sentry-release.apk). I'm not sure if there are any EntryEvo systems that are actually 800x480, which won't work properly with this version  :/

**Comment by ilross02** [comment]
Well that's beautiful!
The map application started with the Widescreen mode turned off, and the map was a left-aligned square (with the same height but little bit more than an half of the widescreen width). Once turned widescreen on, it displayed like in the photo I shared. And no, my iDrive doesn't let me splitscreen.

Before quitting, a question that doesn't concern this problem: I read from other topics that is possible to replace the mapbox with google maps, I just didn't understand how to do this. Actually that's not so important and I can stay with mapbox, but it was just better for "speedcameras" (if they could not be implemented in the mapbox app in the future).

Thank you so much for what you do!

**Comment by hufman** [comment]
Please try [this latest branch build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-bmw_xl_small-mapbox-sentry-release.apk)
It should remove the Widescreen option from the car interface and should add a note to the phone screen saying widescreen is not supported by the car. After your confirmation, I'll merge it to the main build!

**Comment by ilross02** [comment]
I confirm that now there's no widescreen option, and the map works well fitting the screen ;)

**Comment by hufman** [comment]
This is merged to main as [c830e48](https://github.com/BimmerGestalt/AAIdrive/commit/c830e48f29139efcf5e1471fc1bba9f2ccb21c8f), and gradually rolling out to the Play Store beta users

**Comment by gkcngk** [comment]
> Can you turn on Advanced Settings and send me the hmi.display-width and hmi.display-height information from the Car Information tab? EntryEvo infotainment lies a little bit about the screen size, and we have previously seen it lie about the 1440x540 screen being called 1280x480. It looks like yours is saying it's 800x480 but clearly it's bigger.

Thank you so much for developing and sharing this app with the public. It is a great addition to the factory-built functions. It seems I've encountered similar issues to the OP of this ticket. The map and screen mirroring don't expand to the entire screen. A similar issue occurs with split screens tool.

I have attached some photos and screenshots of my app version and BMW head unit version.

Could you shed some light on how I might fix this? 

![SmartSelect_20221112_221438_Settings](https://user-images.githubusercontent.com/96928780/201471699-06567516-b49e-4c0b-9c7c-42d676f3fb1f.jpg)
![SmartSelect_20221112_171218_AAIdrive](https://user-images.githubusercontent.com/96928780/201471701-89db2416-8b3e-47b9-936e-9f0572203f06.jpg)
![SmartSelect_20221112_221316_Gallery](https://user-images.githubusercontent.com/96928780/201471702-34ceacb0-755b-4736-b8ff-c76727a6ec10.jpg)
![SmartSelect_20221112_221239_Gallery](https://user-images.githubusercontent.com/96928780/201471703-a9977862-4b87-4fec-8ff1-e462c1d633e6.jpg)
