### ISSUE TITLE
Spotify disappeared

### ISSUE THREAD

**Issue by dimakaob** [BimmerGestalt/AAIdrive#582]
Hello! 
Is it just me or not? 
Yesterday Spotify and other music players suddenly disappeared. 
I see Screen Mirror add-on, but no Spotify. 

It worked fine until then. 
App ver. is 1.4, downloaded from Play market.

**Comment by dimakaob** [comment]
Hi! If it helps. 
I've cleaned all the app data, and then set it up again. Works fine so far. 

But that is the first time i see such a bug.

**Comment by hufman** [comment]
If it happens again, I'd like to know if it reconnected when you open the app's phone interface.

**Comment by dimakaob** [comment]
You mean if the status is connected or not?

ср, 8 июн. 2022 г., 08:13 Walter Huf ***@***.***>:

**Comment by hufman** [comment]
That would be good to know, too. I also want to know if Android background-kills AAIdrive (perhaps for memory reasons), and then whether the app connects back to the car when AAIdrive is opened on the phone.
