### ISSUE TITLE
AAI does not correctly recognize MyBMW after app restart

### ISSUE THREAD

**Issue by daniel1v** [BimmerGestalt/AAIdrive#589]
Aaidrive does not recognize the MyBMW app, when I force close and reopen it or when I reboot my phone. Instead of showing "ready to connect to BMW", it suggests to install the bmw or mini app. After closing and reopening again, the issue is resolved most of the time. 

Maybe this could lead to connection issues, if AAI is not always aware, that the bmw app is installed?

I am using Android 12 on Google Pixel and have granted all permissions to AAI and deactivated battery optimization

**Comment by hufman** [comment]
I haven't seen this, I wonder why that's happening! The connection issues can be confirmed by whether the Apps checkbox in the car gets filled in but AAIdrive doesn't connect automatically.

**Comment by hufman** [comment]
I found a bug in the display update logic that shows whether MyBMW is installed and [fixed it](https://github.com/BimmerGestalt/AAIdrive/commit/42e095a718ceba3188b47a23c2cf7305db3ffad6) in the [latest build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-main-mapbox-sentry-release.apk), with help from #694.
