### ISSUE TITLE
Only the events from the phone calendar are visible

### ISSUE THREAD

**Issue by wdata68** [BimmerGestalt/AAIdrive#590]
Hi, is that how it's  supposed to be?
The application itself can see all the connected calendars (see the screenshot), but the events are listed only from the phone calendar.

![Screenshot_20220625-132655_AAIdrive](https://user-images.githubusercontent.com/74700302/175769838-e6797056-0811-4b91-acbc-eb36efb5e354.jpg)

**Comment by hufman** [comment]
AAIdrive uses the central Android calendar sharing system, and by default only shows events that are on calendars that are marked as as visible in the system calendar settings. The event color is meant to show what calendar is providing your test event, which I'm not seeing in the list for some reason. Some calendar apps may have their own visibility settings, which AAIdrive does not know about.
If it's not possible to mark the calendars as visible, you can enable Advanced Settings and tell it to show all events ignoring visibility.

**Comment by wdata68** [comment]
@hufman thank you for the advice. That was exactly my concern as all the calendars are marked as visible, and in the system calendar a can see all the events. But it definetely could be some Samsung calendar application peculiarity. 
I've enabled the advanced settings but I can't see anything related to the calendars visibility though. Could it be becase I use the Google Play version? Unfortunately I cannot install the apks on my company owned phone.
Thank you again for your great application.

**Comment by hufman** [comment]
Enabling Advanced Settings in the Settings tab will make a new checkbox appear on the Calendar tab with the option to show events from hidden calendars.

**Comment by wdata68** [comment]
Ah, so it's called "hidden calendars". Well, I've seen it, tried it, but it didn't make any difference for me.

**Comment by hufman** [comment]
That's a shame! I guess if your calendar app doesn't want other apps to view the events, there's nothing that AAIdrive can do.
