### ISSUE TITLE
Aaidrive not working after July Update 

### ISSUE THREAD

**Issue by dlmarien** [BimmerGestalt/AAIdrive#592]
Apps option in idrive doesnt stay connected after July Update. Pixel 6, Android 12 July Patch

**Comment by dlmarien** [comment]
Meant to add that the app says "Waiting for connection to car"

**Comment by bogdan-calapod** [comment]
Did you try clearing app data ? AAIdrive works fine for me

**Comment by dlmarien** [comment]
Hi Walter,

Thanks for the quick reply. No, connecteddrive sub is still active (vehicle
is only 2 years old and subs are good for 3 years). Yes, the App box is
checked off. The last update to MyBMW was approx 2 weeks ago. My issue
started the day after the July Android patch.

No worries I guess. Thanks for taking the time to respond though.

Dave

**Comment by dlmarien** [comment]
Hi Walter,

Thanks for the prompt reply.

Yes, my connecteddrive is still subscribed. My vehicle is only 2 years old.
Yes, the App box is checked off in idrive. The MyBMW app was updated in
June 29th (Canada) but my issue started after the July 5th Android patch
update (19meg).

In any case, guess I'm stuck. Thanks anyway Walter.

Back to using BT lol!

Dave

**Comment by bogdan-calapod** [comment]
Have you tried reinstalling AAIdrive ?  Does the AAIdrive show any status in the sidebar when you open it ?

**Comment by dlmarien** [comment]
I was about to post an update...I reinstalled MyBMW and now it's working
again...

Sorry for the trouble, thanks for all the responses

Dave

**Comment by hufman** [comment]
Glad that helped!
