### ISSUE TITLE
Spotify freezing

### ISSUE THREAD

**Issue by Esco54** [BimmerGestalt/AAIdrive#593]
I'm using the AAIdrive on ID5 since 3 days but there is this freezing problem when using Spotify.
You can find and start Spotify from the media menu in ID5 but sometimes when you click to skip a song it freezes for 10 seconds.
The seconds in the display are freezing and the song doesn't jump to the requested next one.
After 10 seconds it skips to the next song automatically... : (
Thanks for the help!

**Comment by hufman** [comment]
I've heard of this symptom happening when the AAIdrive app is suspended by the phone for being in the background. Does the car interface become responsive again if you open AAIdrive's phone interface? You should be able to dig around in the phone's background execution limits to allow AAIdrive to run in the background.

**Comment by Esco54** [comment]
Hallo,

First of all thank you for all the improvements you made in the AAIdrive app :)
I’m connecting my phone on ID5 in a 7 series G11 2016 and YT Music works but can’t search into the folders?

Met vriendelijke groeten,
Kurt Car Company

Laat je passie voor rijden tot leven komen met een prachtige tweedehands BMW van dé BMW-specialist!
Elke BMW in onze collectie is zorgvuldig geselecteerd en ondergaat strenge inspecties om ervoor te zorgen dat alleen de hoogste kwaliteit voertuigen onze showroom verlaten.

***@***.***
Kurt Car Company
BMW Specialist
Kasteelstraat 22
9140 Temse
GSM : +32.489.287.099
www.kurtcarcompany.be<http://www.kurtcarcompany.be/>


***@***.***

Van: Walter Huf ***@***.***>
Verzonden: zondag 17 juli 2022 21:58
Aan: BimmerGestalt/AAIdrive ***@***.***>
CC: Esco54 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [BimmerGestalt/AAIdrive] Spotify freezing (Issue #593)


I've heard of this symptom happening when the AAIdrive app is suspended by the phone for being in the background. Does the car interface become responsive again if you open AAIdrive's phone interface? You should be able to dig around in the phone's background execution limits to allow AAIdrive to run in the background.

**Comment by hufman** [comment]
YTMusic doesn't allow AAIdrive to browse the library, please reach out to Google to request that they change the policy.
