### ISSUE TITLE
EV route planning apps support please?

### ISSUE THREAD

**Issue by idesignstuff** [BimmerGestalt/AAIdrive#594]
Plug share and ABRP (a better route planner) are two popular apps for EV drivers. Integrations for their waypoints or turn-by-turn directions would be much appreciated.

**Comment by hufman** [comment]
There aren't any plans to add extra data layers to the Mapbox map. However, standard Android Navigation intents will be handled by the car's navigation or by AAIdrive's navigation, so just click the Navigate button within Plugshare.
