### ISSUE TITLE
Spotify and map issues on ID5

### ISSUE THREAD

**Issue by markoreg** [BimmerGestalt/AAIdrive#596]
1. I was not able to change the media source via idrive while running the Spotify app. Clicking on Media button i could see the sources for a moment, and then switched back to Spotify app. I was only able to chage the media source via steering media toggle button. 

2. Custom map is not on fullscreen, but is like 4/5 of the screen

**Comment by hufman** [comment]
1. This behavior is how the car's Media button behaves normally, such as with the built-in Radio and Bluetooth media sources. The only difference is that the interface lags enough for you to see the list of Media sources before it continues into the app. Tilt the idrive controller to the left to get back to the list, or delve into the Media menu from the Home screen, or select from the Apps list within AAIdrive's music screen.

2. What idrive model do you have? EntryEvo does not provide the correct screen dimensions and AAIdrive should have a workaround for it, but what do you have? Can you share a picture of what it looks like?

**Comment by hufman** [comment]
The steering wheel buttons don't change media sources, I'm curious what you mean. The steering wheel buttons only control the playlist shown in the HUD.
What dimension does your screen say (hmi.display-width hmi.display-height), under the Advanced Car Information? The code has [special handling](https://github.com/BimmerGestalt/IDriveConnectKit/blob/main/src/main/java/io/bimmergestalt/idriveconnectkit/RHMIDimensions.kt#L37) for 1280 and 800 widths, but isn't being triggered for your car.
Remote services are not planned, MyBMW's ConnectedDrive subscription already provides this and various 3rd party apps can be used too.

**Comment by hufman** [comment]
Yes, the behavior about switching the media source is the normal behavior of the car. If you are in the Radio, the Media button will bring up a little tiny popup menu but you can tilt the controller left to get out to the main Media menu and pick all the media sources.
I'm not sure why the map isn't behaving properly, the car data looks like it should use the extra handling for EntryEvo 800px wide.

**Comment by markoreg** [comment]
About the map resolution, if I can help somehow just give me instructions
on what to do and what info do you need.

**Comment by hufman** [comment]
You could experiment with [this earlier debug build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-custom_dimensions-mapbox-nonalytics-release.apk) that adds custom map size options to the Map tab. I'd be curious to know what size fits your car best.

**Comment by markoreg** [comment]
I'm using the custom map now with the latest version. It works fine on
fullscreen.

**Comment by markoreg** [comment]
It was the version before the latest which had a broken map view. It was
fine after the update.
Now i'm experiencing 2 different issues:
- the phone Samsung S10+ was freezing while it was connected to the car
with AAIdrive (solved after app reinstall)
- notification screen is opening randomly automatically (experienced
today). I had to turn off the notification in the AAIdrive at the end.

**Comment by hufman** [comment]
Neat, glad it works better for you!
I haven't experienced those issues, what notification is it showing? I know there used to be a thing where the Outlook Appointment notification would popup as the minutes keep counting down, but Outlook fixed that a while ago. You should open a new issue about that bug, if it's a serious problem.

**Comment by markoreg** [comment]
I'll test it a bit more, and will opet the issue if it appears again.
Actually, it was not some specific notification, but the notifications
settings on the idrive.
