### ISSUE TITLE
Entries on main menu without text?

### ISSUE THREAD

**Issue by jmvaz** [BimmerGestalt/AAIdrive#597]
Hi guys,
Just tried today the app, and it works fine for some features, but I'm struggling with empty string on the main menu. Any ideas?
How can I provide logs?
![IMG_20220727_223150](https://user-images.githubusercontent.com/19754068/181377553-529e2bb8-10cb-4202-812a-8faf75da80b1.jpg)

Thanks,

**Comment by bogdan-calapod** [comment]
Hey - from what I understand from hufman's answers in other threads, that's a limitation of the current BMW API. If you hit it it will show you that it is a supporting application for readout purposes, if I remember correctly.

**Comment by hufman** [comment]
That is correct! It is impossible to change the name or icon of those main menu entries, or even change what menu they show up in. (The music app icons are a different menu entry type and can't contain an application.)
I'm using the old News app for its TTS capability, and so the icon would say "News" if I were to transfer the text pack to the car.
The book icon above is an SDK component and doesn't actually have a title by itself.
The circle is the Samsung Smartthings app, and it would say Smartthings if I enabled the text label for it.

To change these entries, BMW would need to give me new certs that include a sha256 hash of a new icon or text pack, so we are stuck with these icons.
