### ISSUE TITLE
Unable to connect via Bluetooth 

### ISSUE THREAD

**Issue by Webrits123** [BimmerGestalt/AAIdrive#601]
Hi,

I installed MyBMW app and AAI, set everything up but it will only connect and show the apps on my IDrive if I use a USB cable.
AAI just states "waiting on connection to car".
I've tried reinstalling the apps, toggling the Bluetooth on/off and have even updated the idrive via USB.
Car is a 2015 F30 LCI. Phone is a Pixel 5.
Help...!!

Cheers
Paul

**Comment by hufman** [comment]
According to [this list](https://www.bimmer-tech.net/blog/item/54-bmw-cic-nbt-nbtevo), the 2015 F30 has ID4 (which only supports USB). Does your car have the Bluetooth Apps option? It should look like this:
https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res-facets/tips/drawable/pic_btapp_bmw.jpg

Without this option, your car only supports USB apps connection.

**Comment by Webrits123** [comment]
Hi Hufman,

Yes, it is ID4. I thought with me having the enhanced Bluetooth option it would Bluetooth the apps..Shame....
Thanks

**Comment by hufman** [comment]
It seems that Enhanced Bluetooth means it has [music over Bluetooth](https://www.bimmer-tech.net/blog/item/56-bmw-enhanced-bluetooth).
