### ISSUE TITLE
Spotify issues

### ISSUE THREAD

**Issue by Nomexx112** [BimmerGestalt/AAIdrive#602]
When I'm using Spotify and change to the playlist wich i currently use its not possible to change the song. Somehow when i choose a random song in the list its like using the "next Song" Key. After a few attempts the connection freeze.

**Comment by hufman** [comment]
Hmmm I haven't experienced this.. Can you replicate it with the mini player that comes up when you tap the Spotify icon in the AAIdrive phone interface? Can you share a video of what you are experiencing?

**Comment by ismailrei** [comment]
I have the same problem in my bmw F39, after updating Aaidrive to the latest version.

**Comment by Nomexx112** [comment]
I tried to reproduce the issue. Unfortunately the freeze does not occur. But in my video (sorry for the bad quality) its shown that it always skips to the first song in the list. 

https://user-images.githubusercontent.com/111524749/188310483-aa855022-8cc9-449f-8b63-153ef47306b4.mp4

**Comment by hufman** [comment]
Is this only in the Liked Songs playlist? That playlist is treated specially in Spotify and ignores the song index we ask for, so AAIdrive creates a cloned playlist called AAIDRIVE_LIKED_SONGS and tries to play songs from there, if AAIdrive has Spotify Search permissions. Can you check in your Spotify client that this playlist is created?
I don't know what would be causing any freeze.

**Comment by Nomexx112** [comment]
I have the cloned Playlist in my Spotify Client

**Comment by Nomexx112** [comment]
But im not able to select the playlist in the car.

**Comment by hufman** [comment]
Unfortunately I can't reproduce this issue you are experiencing... Try a different music app (Musicolet or Youtube Music work well) to see if it's just a Spotify problem.
Do you have Spotify Premium? I think Free accounts have some limitations that I [haven't built support for yet](https://github.com/BimmerGestalt/AAIdrive/issues/388).

**Comment by Nomexx112** [comment]
I only use Spotify and i have a premium subscription

**Comment by Vasmares** [comment]
I had the same iusse.
This seems to be gone with yesterdays nightly build.

much more stable and way faster.

@hufman is there anything you recently changed ?

**Comment by hufman** [comment]
No, I haven't changed anything in the Spotify connection, though the Spotify app has updated and perhaps has fixed itself. I'm glad to hear it's working better!
