### ISSUE TITLE
Add Waze?

### ISSUE THREAD

**Issue by mfisher224** [BimmerGestalt/AAIdrive#61]
Would make for a great addition.

**Comment by c-radu** [comment]
My main issue with idrive (my car have NBT) is the missing of Waze or Google maps. Is very annoying to relay only on Bmw maps, that get updated just once in a few months (NBT case), when those maps alternatives are updated in real time and for free. If you can add support for Waze or Google maps, will be excelent.

**Comment by bogdan-calapod** [comment]
Linking this to #131 so it doesn't go stale

**Comment by hufman** [comment]
For the purpose of showing a map in the car if the car doesn't come with one, AAIdrive now provides a custom map based on Mapbox (until version 1.4 is released, it's linked from the README or available through the beta test program in the Play Store). As for Google Maps or Waze, it's impossible to embed them directly in AAIdrive, but the [Screen Mirroring addon](https://github.com/BimmerGestalt/IDriveConnectAddons/releases/tag/latest_build) provides a way to view those apps in the IDrive screen.
That is about as much as can be done, unfortunately!
