### ISSUE TITLE
Libreria spotify non disponibile

### ISSUE THREAD

**Issue by Lex1982** [BimmerGestalt/AAIdrive#612]
Buongiorno...
Sulla mia vettura non riesco ad attivare la navigazione con la libreria di Spotify..
Se premo su "concedi" non succede nulla

Allego screen shot

![Screenshot_20220909-110645_AAIdrive](https://user-images.githubusercontent.com/113173654/189314709-ec7cf62e-9f86-4af6-a643-553cc9b784af.jpg)

**Comment by hufman** [comment]
AAIdrive uses the Spotify SDK to control and browse Spotify. However, this SDK refuses to control any modded Spotify versions. You must use the official Spotify version, not a modded version.

**Comment by rareuns** [comment]
The issue can also be related to Spotify that is in the "not connected" mode in its parameters. Re-establishung the connection immediately solves rhe issue
