### ISSUE TITLE
Id4 with WiFi updated to id5 app over bluetooth problem. 

### ISSUE THREAD

**Issue by SaxMachine** [BimmerGestalt/AAIdrive#615]
Hi, 
I have recently updated my ID4++ to id5.
Apple carplay is working fine so the antenna wifi and Bluetooth are ok. 
![IMG_20220917_185140.jpg](https://user-images.githubusercontent.com/24545950/190868809-788f85a4-2c2b-4fab-8942-540088f7db99.jpg)
Unfortunately apps over bluetooth still not working, if I check the advanced settings on connecction I see the option: 
Apps over bluetooth are supported.
Any ideas? 
![IMG_20220917_191749.jpg](https://user-images.githubusercontent.com/24545950/190868920-0a2c8005-86ed-4b92-beb6-aea354174c8a.jpg)
I have connection only via USB.

**Comment by hufman** [comment]
Congrats on your ID5 upgrade!
The AAIdrive checkbox you've circled shows that your ID5 is properly announcing the serial port over Bluetooth which is needed for the apps connection.
What does your car say when you go into the Mobile Devices into your phone? It should show, besides Phone and Media, an Apps option. If this is missing, then you will need to add an FSC code to enable it or enable the BMW ConnectedDrive subscription for your new headunit. I'm not sure which is more feasible for your upgrade.

**Comment by SaxMachine** [comment]
It is showing only media and phone.
What do you mean BMW ConnectedDrive?
I have tried to see on esys and two option for ConnectedDrive are enabled. Do you think that i have to add the 6NR code?
![Remote_APPS](https://user-images.githubusercontent.com/24545950/190889911-4d115065-5383-4190-b936-422e877acdcc.JPG)
![Connected_Drive](https://user-images.githubusercontent.com/24545950/190889912-a0651e7d-9c2c-4d97-8b11-215c113432bc.JPG)

**Comment by hufman** [comment]
I was not aware that ID4 could be upgraded to ID5, only that ID5 could be changed to the ID6 theme.
I am unfamiliar with E-SYS or coding options, so you're on your own there! If USB Apps are working, then I guess the 6NR code is still enabled. I found a coding description list for HU_NBT2 suggesting there is a code named TELEFON_TELEMATIK_ONLINE/A4A_WIRELESS_ANDROID, which sounds very promising.

**Comment by SaxMachine** [comment]
> 
6NR is for BMW, I think that in Mini is different. 
Anyway, A4A_WIRELESS_ANDROID is already set to aktiv :-( 
I will investigate more thoroughly. 
Thanks for your work, it's a really great opportunity for android users.

**Comment by SaxMachine** [comment]
Ok issue resolved. 
I have delete mini app and aaidrive, delete all phone from my nbt and now I have all apps. Yeahhh!
![IMG_20220927_115408.jpg](https://user-images.githubusercontent.com/24545950/192496268-1ba79965-3115-4b04-82fb-5678daa91801.jpg)
![IMG_20220927_115252.jpg](https://user-images.githubusercontent.com/24545950/192496302-ebd048e7-972c-4d47-9e16-ff7c24f78c40.jpg)

**Comment by hufman** [comment]
That's great to hear!
