### ISSUE TITLE
es una pasada pero le falta actualizar 

### ISSUE THREAD

**Issue by ivanG30** [BimmerGestalt/AAIdrive#620]
Se me conecto solo una vez y no logro volver a enlazar la con mi bmw g30 pero es una pasada de app lo mejor q he visto pero me fumciono durante un dia solo me gusto tanto pr yo utilizo youtubmusic i con esta app logro q apareciera en el menu de mi bmw i app de radio tambien ,no se porque pero no se me vuelve a enlazar

**Comment by hufman** [comment]
Does your car or the BMW app show the Apps connection as active? Those pieces are required for AAIdrive to work.
