### ISSUE TITLE
Connessione con altra vettura BMW impossibile

### ISSUE THREAD

**Issue by Lex1982** [BimmerGestalt/AAIdrive#621]
Buongiorno..
L'App funziona benissimo.
Ho però un problema.
Quando cerco di connettere via bluetooth lo smartphone ad un altra BMW è impossibile la connessione.
Per poterlo connettere devo disinstallare l'app.

Grazie

**Comment by hufman** [comment]
The app does not care whether you are connecting to the same car or a different car. However, I believe the MyBMW app is pickier, requiring that the cars be in your account. Does MyBMW show that the Apps connection is active, and does your car's Bluetooth menu show the Apps connection is active?

**Comment by Lex1982** [comment]
my BMW app has nothing to do with it ... in fact, before installing AAIdrive I had no problems.  If I delete the AAIdrive app everything will work again.  it would seem that the AAIdrive app is going to interfere I don't know how.BASSANI ALESSIO
-------- Messaggio originale --------Da: Walter Huf ***@***.***> Data: 07/10/22  17:44  (GMT+01:00) A: BimmerGestalt/AAIdrive ***@***.***> Cc: Lex1982 ***@***.***>, Author ***@***.***> Oggetto: Re: [BimmerGestalt/AAIdrive] Connessione con altra vettura BMW impossibile (Issue #621) 
The app does not care whether you are connecting to the same car or a different car. However, I believe the MyBMW app is pickier, requiring that the cars be in your account. Does MyBMW show that the Apps connection is active, and does your car's Bluetooth menu show the Apps connection is active?

**Comment by hufman** [comment]
Without AAIdrive installed, what functionality do you see in your car? As far as I know, BMW doesn't provide any apps functionality anymore; do you see a new feature that I haven't heard about?
