### ISSUE TITLE
No cover shown, apps disconnected after a short while

### ISSUE THREAD

**Issue by JCzopik** [BimmerGestalt/AAIdrive#623]
After a recent software update in my BMW the connection with Android Galasy S22 Ultra has got much worse as before.
Previoulsy the cover where shown and the connection with the apps was stable. Now after few minutes the music player disconnects and my car tells me, that my telephone is just connected for calling, but the app connection is deselected and cannot be activated again. After having the car restarted, it works for a while...
Which settings in Android might be affected?

**Comment by JCzopik** [comment]
In the meantime I have removed all connections in the car and in the phone, restarted the phone and connected again.
Now the connection seems to be stable, but still no cover is shown. However, this is only in the right part of the splitscreen. If I switch to media view in the main part of the screen, the cover is shown. Strange indeed.
My car software is:
TB-007.039.008
MB-007.039.008
Any help?

**Comment by hufman** [comment]
The MyBMW app is responsible for activating the Apps connection in the car, and has traditionally been unreliable. I'm sorry to hear that it sounds like it got worse!
The lack of cover art in the splitscreen view sounds like AAIdrive is running in the legacy Audioplayer mode instead of the new Spotify mode. Is your phone connected over USB instead of Bluetooth? AAIdrive's UI should have a checkbox about Global Coverart, with an explanation for why it didn't enable it.

**Comment by JCzopik** [comment]
Dear Walter

Many thanks for your response.
I do not use spotify, only the Poweramp player.
AAidrive shows me, that the car does not support global cover art (if I remember the message correctly).
However, as I wrote on Github, when I show media on the main screen instead of the map, cover is shown.
Crazy…

Best regards and thanks again
Jerzy

Mit freundlichen Grüßen
Kind regards
Z poważaniem
Dipl.-Ing. Jerzy Czopik
Feldbrandweg 22
D-44339 Dortmund

Tel.            +49 231 801645
Fax            +49 231 801653
Mobil       +49 173 3516611
E-Mail:     ***@***.******@***.***>
                   ***@***.******@***.***>

Von: Walter Huf ***@***.***>
Gesendet: Donnerstag, 20. Oktober 2022 16:01
An: BimmerGestalt/AAIdrive ***@***.***>
Cc: Jerzy Czopik ***@***.***>; Author ***@***.***>
Betreff: Re: [BimmerGestalt/AAIdrive] No cover shown, apps disconnected after a short while (Issue #623)


The MyBMW app is responsible for activating the Apps connection in the car, and has traditionally been unreliable. I'm sorry to hear that it sounds like it got worse!
The lack of cover art in the splitscreen view sounds like AAIdrive is running in the legacy Audioplayer mode instead of the new Spotify mode. Is your phone connected over USB instead of Bluetooth? AAIdrive's UI should have a checkbox about Global Coverart, with an explanation for why it didn't enable it.

**Comment by hufman** [comment]
Yes that sounds right, when you open the Media app, it has a dedicated image widget to display the cover art. However, if AAIdrive is connected in Spotify mode, then there is an extra image widget to display the cover art on the home screen and in the sidebar. This Spotify mode is (by default) automatically enabled if Spotify is installed on the phone, even if you aren't using it, and if the Apps connection is running over Bluetooth. Again, AAIdrive will tell the reason for why it didn't connect as Spotify.

**Comment by JCzopik** [comment]
Now all is clear.
I have uninstalled spotify from my phone recently.
Many thanks for pointing me into right direction.
I reinstall spotify and test again soon.

Kindest regards & have a nice day
Jerzy

Von: Walter Huf ***@***.***>
Gesendet: Donnerstag, 20. Oktober 2022 16:25
An: BimmerGestalt/AAIdrive ***@***.***>
Cc: Jerzy Czopik ***@***.***>; Author ***@***.***>
Betreff: Re: [BimmerGestalt/AAIdrive] No cover shown, apps disconnected after a short while (Issue #623)


Yes that sounds right, when you open the Media app, it has a dedicated image widget to display the cover art. However, if AAIdrive is connected in Spotify mode, then there is an extra image widget to display the cover art on the home screen and in the sidebar. This Spotify mode is (by default) automatically enabled if Spotify is installed on the phone, even if you aren't using it, and if the Apps connection is running over Bluetooth. Again, AAIdrive will tell the reason for why it didn't connect as Spotify.

**Comment by hufman** [comment]
Ah yep, that would do it!

**Comment by JCzopik** [comment]
HI

Many thanks again. After reinstalling Spotify all works again as expected.

Best regards
Jerzy

Von: Walter Huf ***@***.***>
Gesendet: Donnerstag, 20. Oktober 2022 16:44
An: BimmerGestalt/AAIdrive ***@***.***>
Cc: Jerzy Czopik ***@***.***>; Author ***@***.***>
Betreff: Re: [BimmerGestalt/AAIdrive] No cover shown, apps disconnected after a short while (Issue #623)


Closed #623<https://github.com/BimmerGestalt/AAIdrive/issues/623> as completed.

**Comment by JCzopik** [comment]
Sorry for reopening here.
Now even though I can see icons (Spotify is installed), the app crashes/closes after a short while.
The connection behaves like this:

- Phone connects to the car
- After a while the Poweramp (my music app) starts playing
- For a short while I can use forward or reverse button
- After doing so the icon and the status bar of the song freeze and Poweramp continues to play
- I cannot affect the played songs anymore
- After a while music stops
- Reconnecting to Poweramp is impossible, the car states, that the function is currently unavailable
- On the phone I have seen a message "BMW Scrobbler has caused a problem"
- I uninstalled all add-ons from AAIdrive
- Deleted phone in the car, deleted car in the phone, reconnected
- All to no avail, after a while no function

Can you help again? Thanks a bunch

**Comment by JCzopik** [comment]
And it seems all the issues started after I updated AAIdrive on November 7th...

**Comment by hufman** [comment]
Unfortunately I haven't experienced this, please try checking the power saving and background execution options for MyBMW and AAIdrive.

**Comment by JCzopik** [comment]
Hi Walter

Many thanks for coming back to me.
Both apps are excluded from power saving.
It is really strange, as it started to happen only after the latest update.

I haven’t changed anything in the car or in the settings of my mobile.
Do you mean, uninstalling all BMW related apps and installing them again would help? Is there any way to clean uninstall the apps, removing all traces of them from the phone?

Kindest regards and many thanks
Jerzy

Mit freundlichen Grüßen
Kind regards
Z poważaniem
Dipl.-Ing. Jerzy Czopik
Feldbrandweg 22
D-44339 Dortmund

Tel.            +49 231 801645
Fax            +49 231 801653
Mobil       +49 173 3516611
E-Mail:     ***@***.******@***.***>
                   ***@***.******@***.***>

Von: Walter Huf ***@***.***>
Gesendet: Mittwoch, 23. November 2022 19:26
An: BimmerGestalt/AAIdrive ***@***.***>
Cc: Jerzy Czopik ***@***.***>; Author ***@***.***>
Betreff: Re: [BimmerGestalt/AAIdrive] No cover shown, apps disconnected after a short while (Issue #623)


Unfortunately I haven't experienced this, please try checking the power saving and background execution options for MyBMW and AAIdrive.

**Comment by hufman** [comment]
The only update on November 7th was to add Bluetooth permission support for Android 12 and to add a faster screen update method. Please try reverting to the stable version instead of the beta version to see if that helps.

I don't mean uninstalling BMW apps will help. If anything, it'll reset Samsung's view of what apps you use recently and might keep them in memory longer, I think there's a 3 day timer after which Samsung starts closing apps more aggressively.

Does the Apps checkbox in your car still show as connected? If this clears itself, that means MyBMW isn't able to keep the heartbeat going with the car and is something that AAIdrive can not help with.

**Comment by JCzopik** [comment]
Hi

Thanks for this update.
How do I revert to non-beta?
It looks like the app option in car is still kept.
I am abroad now, so I will check during the weekend.

Best regards from Cracow in Poland
Jerzy

Von: Walter Huf ***@***.***>
Gesendet: Donnerstag, 24. November 2022 18:03
An: BimmerGestalt/AAIdrive ***@***.***>
Cc: Jerzy Czopik ***@***.***>; Author ***@***.***>
Betreff: Re: [BimmerGestalt/AAIdrive] No cover shown, apps disconnected after a short while (Issue #623)


The only update on November 7th was to add Bluetooth permission support for Android 12 and to add a faster screen update method. Please try reverting to the stable version instead of the beta version to see if that helps.

I don't mean uninstalling BMW apps will help. If anything, it'll reset Samsung's view of what apps you use recently and might keep them in memory longer, I think there's a 3 day timer after which Samsung starts closing apps more aggressively.

Does the Apps checkbox in your car still show as connected? If this clears itself, that means MyBMW isn't able to keep the heartbeat going with the car and is something that AAIdrive can not help with.

**Comment by hufman** [comment]
When you navigate to the BimmerGestalt AAIdrive page in the App Store, it should show that you are a Beta Tester, and it should offer a button to Leave the beta testing program. After uninstalling and reinstalling, it will install the latest stable version from August.
However, uninstalling and reinstalling will also reset the phone's understanding of whether it should leave the app in the foreground or pause it in the background, which will confound the test. However, there are no new features in the beta, so you aren't going to miss anything by staying on the stable version.
