### ISSUE TITLE
Spotify "enable shuffle" not working from iDrive controls

### ISSUE THREAD

**Issue by HaivanJV** [BimmerGestalt/AAIdrive#625]
I noticed that I cannot enable/disable shuffling anymore, when inside the Spotify app from the iDrive.
One possible reason is the new "smart shuffle" feature. When Spotify App (on the phone) is playing, selecting "shuffle" from the song view screen pops up a selection menu. There you can select normal and enhanced shuffle (screenshot attached).

1) do you experience the same limitation from the iDrive?
2) can the new feature be the cause of it?
3) if yes, can the iDrive control be defaulted to normal shuffle?

<img width="267" alt="image" src="https://user-images.githubusercontent.com/22883596/196882052-c4599a1e-e792-4e60-aa0b-3e92b101d8d2.png">

**Comment by hufman** [comment]
Hmmm it seems that my Spotify (freshly updated to version 8.7.76.359) does not have this feature, I checked while playing from an album and from a playlist.
AAIdrive uses the Spotify API to [setShuffle(true/false)](https://github.com/BimmerGestalt/AAIdrive/blob/22633db1666dbfd32559a3117543263fe833cf65/app/src/main/java/me/hufman/androidautoidrive/music/controllers/SpotifyAppController.kt#L724), and so it would be up to Spotify to handle this command appropriately. The [current API docs](https://spotify.github.io/android-sdk/app-remote-lib/docs/com/spotify/android/appremote/api/PlayerApi.html#setShuffle-boolean-) don't indicate that they've enhanced the shuffle command, however.

**Comment by HaivanJV** [comment]
most probably this is behind an a/b test or only released on a regional basis. Please let me know whether you encounter the same issue in the future

**Comment by 6i6i** [comment]
Same problem for here.

**Comment by DominikS66** [comment]
The Problem appeared betreten Spotify Version 8.7.70.553 (working) and Version 8.7.72.546

**Comment by hufman** [comment]
Good news! My Spotify no longer lets me disable Shuffle from the car interface, but I can enable shuffle. The UI doesn't show whether shuffle or repeat are enabled.
Now that I can reproduce the problem, I might be able to make progress! Or it might just be a bug report on Spotify's API, I can't promise a fix yet :)

**Comment by JollyJumper88** [comment]
I also cannot disable shuffle

**Comment by DominikS66** [comment]
here some screenshots.
1. Tool bar icon
the tool bar icon is always showing shuffle not activated, even if the state of shuffling is changed on the smartphone.
![20221226_135353](https://user-images.githubusercontent.com/81849700/210202276-adfd40d7-6f9a-4379-8fc2-2b2b1941356d.jpg)
Toggling shuffle from here switches shuffling on in Spotify. The called function toggleshuffle uses the inverted actual state - as the state is (by error) disabled the function can only enable shuffle.

2. Custom action menu
Inside this menu, the state of shuffling is always shown correct. When you change shuffling in Spotify on teh smartphone, the correct state of shuffling is shown here:
![20221226_135555](https://user-images.githubusercontent.com/81849700/210202564-1cd65e43-1b88-4f26-8f0e-bee3049a68b5.jpg)
(shuffling disabled by smartphone app)
![20221226_135824](https://user-images.githubusercontent.com/81849700/210202620-8151cacc-6b94-4ac1-b69c-8ab0b611107a.jpg)
(shuffling enabled by smartphone app)
Strange thing: Inside the custom action menu it is NOT possible to change shuffling state (neither enable nor disable shuffling), although the same function toggleshuffling is used.
@hufman i didn't dug deep inside the source code yet, but maybe you create two different objects from spotify api, one for toolbar and one for custom action menu ? Maybe this is the reason for this strange behavior. BTW, I tested Spotify shuffle toggle API call here outside of the app: https://developer.spotify.com/console/put-shuffle/ and it worked correct.




3.

**Comment by hufman** [comment]
Thank you for investigating!
I added some debug statements and indeed, Spotify's SDK is now always returning isShuffle:false even though my Spotify version doesn't have Smart Shuffle enabled, so I [raised an issue against the SDK](https://github.com/spotify/android-sdk/issues/337). The official forum [even has a thread about it](https://community.spotify.com/t5/Spotify-for-Developers/SDK-fails-to-provide-proper-isShuffling-repeatMode-values/m-p/5473102), cataloguing what versions are affected.

The Custom Actions menu is combined from the Spotify SDK code (Repeat and Like) and the generic music controller which is only accessible if the user has granted control over all running music apps. The shuffle option in that menu is provided by this generic music controller, and AAIdrive is unable to parse it to drive the main toolbar entry.

**Comment by hufman** [comment]
I randomly tried this today and it seemed to work well (Spotify version 8.8.12.545). Can other people confirm that it works for them?

**Comment by HaivanJV** [comment]
Updated Spotify and tried it. It works for me as well!

**Comment by hufman** [comment]
Excellent, thanks!
