### ISSUE TITLE
Not working with Android 13

### ISSUE THREAD

**Issue by Jasdeep18** [BimmerGestalt/AAIdrive#631]
Hi; I recently updated the software on my S22 Ultra to Android 13 and Spotify no longer displays on the idrive. I can see the phone still connects to the car via the AAIdrive app and no settings are changed in the app as far as I can see. Does anyone have any ideas?

**Comment by hufman** [comment]
Thank you for the bug report! You say that AAIdrive shows that it is connected to the car but not add any of the Connected Apps? Or do you still get Notifications and Calendar? Does it crash at all? What version of AAIdrive are you running?
Can you pull an `adb logcat`, perhaps there are some errors that might hold more clues.

**Comment by bogdan-calapod** [comment]
I just received the Android 13 update (Galaxy S21), currently downloading. Will get back with feedback as soon as I get to test it.

**Comment by Jasdeep18** [comment]
Thank you for your response.

Happy to pull an adb location if it will help but will need some guidance.

**Comment by hufman** [comment]
By installing Android Studio and the Android Platform SDK, you should be able to get easy access to your phone's Logcat system by running `adb logcat`. I'd be very curious to see if there are any crash messages when it tries to show the notification, which I hear Android 13 has added limits to.
Please also check AAIdrive's Permissions, perhaps there is a Notifications option that you can enable.
I haven't seen any new crashes come through the analytics, have you enabled crash reporting to automatically report crashes for me to look at?

**Comment by bogdan-calapod** [comment]
Happy to report that everything seems to be in order on my end - music, screen mirroring, etc.

**Comment by earmellin** [comment]
Just for info: I've also installed One Ui 5 (Android 13) on my S22 Ultra (Exynos) and I had no problems connecting with AAidrive (I'm using the last sentry build)

**Comment by Jasdeep18** [comment]
I am now able to access Spotify sometimes however it does freeze quite
often. Doesn't let me skip or the play time freezes.

**Comment by hufman** [comment]
Check the app's background execution limits, that symptom sounds like AAIdrive (or perhaps MyBMW) is put to sleep because the screen is off and so it can't handle input from the car.
