### ISSUE TITLE
NBTevo ID5 map and screen mirroring don't expand to the entire screen

### ISSUE THREAD

**Issue by gkcngk** [BimmerGestalt/AAIdrive#632]
> Can you turn on Advanced Settings and send me the hmi.display-width and hmi.display-height information from the Car Information tab? EntryEvo infotainment lies a little bit about the screen size, and we have previously seen it lie about the 1440x540 screen being called 1280x480. It looks like yours is saying it's 800x480 but clearly it's bigger.

Hi hufman,

Thank you so much for developing and sharing this app with the public. It is a great addition to the factory-built functions. It seems I've encountered similar issues to the OP of this ticket. The map and screen mirroring don't expand to the entire screen. A similar issue occurs with split screens too.

I have attached some photos and screenshots of my app version and BMW head unit version. 
My phone is a Samsung Galaxy S21+
Car is BMW F30

Could you shed some light on how I might fix this? 

![SmartSelect_20221112_221438_Settings](https://user-images.githubusercontent.com/96928780/201471699-06567516-b49e-4c0b-9c7c-42d676f3fb1f.jpg)
![SmartSelect_20221112_171218_AAIdrive](https://user-images.githubusercontent.com/96928780/201471701-89db2416-8b3e-47b9-936e-9f0572203f06.jpg)
![SmartSelect_20221112_221316_Gallery](https://user-images.githubusercontent.com/96928780/201471702-34ceacb0-755b-4736-b8ff-c76727a6ec10.jpg)
![SmartSelect_20221112_221239_Gallery](https://user-images.githubusercontent.com/96928780/201471703-a9977862-4b87-4fec-8ff1-e462c1d633e6.jpg)

_Originally posted by @gkcngk in https://github.com/BimmerGestalt/AAIdrive/issues/580#issuecomment-1312458084_

**Comment by hufman** [comment]
It's hard to say. Have you modified your IDrive to have a different screen? Some replacements have the big 1440x540 screen but IDrive only reports 1280x480 to the apps. You could experiment with [this earlier debug build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-custom_dimensions-mapbox-nonalytics-release.apk) that adds custom map size options to the Map tab. I'd be curious to know what size fits your car best.

**Comment by DrTermi** [comment]
[screen_mirror-debug (6).zip](https://github.com/BimmerGestalt/AAIdrive/files/9995288/screen_mirror-debug.6.zip)
Hey i had the same problem as you but only with the screen mirror app. My idrive screen was also 1440x540 so i build a new apk and it works great for me. You can try this apk and tell us the result.

**Comment by gkcngk** [comment]
> 
Thank you for your reply hufman.

All of the components in this car were factory installed and came with the car. I have not modified my IDrive to have a different screen. 
Btw: At the time the car was built 2016, BMW was about to upgrade their default idrive, but I'm not sure this has anything to do with the incorrect resolution reported to the app.

I'd like to test the debug version that adds custom map size options to the Map tab and report back. But when I try to install Android using the APK, I receive the following error message.

![SmartSelect_20221113_101455_Package installer](https://user-images.githubusercontent.com/96928780/201498467-eabd10d0-6d98-459a-93ec-01b74fdac631.jpg)

To make sure it was not a corrupted file during downloading, I have tried downloading three times and uninstalled the AAIDRIVE I installed from the Google Play Store. It won't let me install.

 Could you please check the file? Thanks

**Comment by Katana1234** [comment]
same here... this is what my system reports:
![Screenshot_20221230-165324~2](https://user-images.githubusercontent.com/14016387/210405228-14eec6d2-8633-48c2-9ba2-1fcbbad40ecd.png)

**Comment by galenzhao** [comment]
for screen mirroring,
you can test this:
https://github.com/BimmerGestalt/IDriveConnectAddons/issues/14#issuecomment-1543340996
with custom dime
