### ISSUE TITLE
Advanced Vehicle Info App

### ISSUE THREAD

**Issue by Katana1234** [BimmerGestalt/AAIdrive#653]
Hi there,

I wanted to show a few values on the IDrive system that you're not able to see by default.
So i did some modifications (super quick and dirty!), mainly to the ReadoutApp, to get what i wanted.
This is the result:
![image](https://user-images.githubusercontent.com/14016387/210399672-96d273b2-4c8f-4590-b4d3-140a0b32f6ef.png)

Wouldn't it be nice to properly implement a screen like this? :)
My understanding of this whole project is sooooo bad so i guess i am not the right one to do this properly.
I mostly achieved my goal by copy+paste and trial+error ;)
But for any dev being more involved into this project it should be a easy task.
I also don't know about the graphical capabilities of the system. I simply used the RHMI list.

In theory the output of the screen could be configurable in the main app. (Which values and where to place them + update interval of the cds data)
Please let me know if i can help out any further.

**Comment by berseker** [comment]
nice! I also recall some similar concepts requests which i collect here below for any possible futher improvements!

https://github.com/BimmerGestalt/IDriveConnectAddons/issues/5
https://github.com/BimmerGestalt/AAIdrive/issues/175

**Comment by hufman** [comment]
That looks so good! Congrats on figuring it out without any help!
Your approach of using a List is the correct one. There aren't very strong graphical capabilities in the system, the closest being manually sending over PNGs to take the place of some of the table cells. It would also be possible to add an AM App Icon to the Car Information menu in the car, as another entry point besides the unlabeled entryButton in the OnlineServices menu.

Do you imagine it should stay in the Readout app? I was planning for such a detailed view to be a separate addon app, but that would add an extra unlabeled icon to the car. I also have been unsure of how to build the UI to configure the displayed data. A first version could simply show a static list, easily enough.

Would you like to contribute a Pull Request, or may I copy code from your branch and add some polish?

**Comment by 6i6i** [comment]
Very nice. I also tried to implement such feature but I wasn't able to. I would very appreciate it if it could get integrated into AAIDrive (or within a extra application).

Thank you

**Comment by ogakul** [comment]
Any updates on this?

**Comment by hufman** [comment]
I've been busy with other projects and haven't had time to look into this.

**Comment by ogakul** [comment]
@Katana1234 can you maybe describe how you achieved the menu in the screenshot? this would be enough for my needs. 

If it's a self compiled APK maybe just share it here?

**Comment by Katana1234** [comment]
@ogakul I already posted all my code changes necessary to show this menu + my objections why not to use this code above ;-)

**Comment by hufman** [comment]
I've posted a [test build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-car_info_flow-mapbox-sentry-release.apk) for this [feature branch](https://github.com/BimmerGestalt/AAIdrive/tree/car_info_flow), try it out!

**Comment by HaivanJV** [comment]
Nice! I tested it and it seems to be working fine
<img width="353" alt="image" src="https://user-images.githubusercontent.com/22883596/221404698-8fcd5520-3953-4c88-bd8d-6fd6285e021a.png">


Do you plan to add an icon and a title to the "app" in the idrive? or is it not much possible?
I can see that the Mapbox navi doesn't have a title

**Comment by berseker** [comment]
> Nice! I tested it and it seems to be working fine <img alt="image" width="353" src="https://user-images.githubusercontent.com/22883596/221404698-8fcd5520-3953-4c88-bd8d-6fd6285e021a.png">
> 
> Do you plan to add an icon and a title to the "app" in the idrive? or is it not much possible? I can see that the Mapbox navi doesn't have a title

0°C oil & 255°C battery seems a bit off :D  anyway I quickly tested it and it works, even if I have to test it more deeply in the next days and i'll let have my feedback on this

**Comment by HaivanJV** [comment]
I had my car off, and that's what AAiDrive displays on the car info screen.
When on, I have the correct oil temp.

I am not sure about the Battery though. It is fixed at 255C no matter when. I also wonder how did I not fry inside :D

**Comment by hufman** [comment]
Thanks for the early feedback! In some places I have the code reject obvious bad data, I guess I need to add that for battery temp :)
I can't change the app icon, but I plan on adding a shortcut icon like the Notifications app.

**Comment by hufman** [comment]
Added an app icon to the Vehicle Info screen of the car:
![image](https://user-images.githubusercontent.com/1592375/221454699-6d624949-cfcb-417b-8a26-91347e478e0d.png)

**Comment by HaivanJV** [comment]
thanks! this looks pretty cool, also that it's within the My Car menu!
I also noticed that you removed the battery temp info and added the Gear info.
One thing that remained in the interface was the gap (empty cell) where the Batt temp was.

Do you know what the HVAC temp is?

**Comment by 6i6i** [comment]
Great work @hufman . That's really nice.

**Comment by Katana1234** [comment]
> thanks! this looks pretty cool, also that it's within the My Car menu! I also noticed that you removed the battery temp info and added the Gear info. One thing that remained in the interface was the gap (empty cell) where the Batt temp was.
> 
> Do you know what the HVAC temp is?

@HaivanJV HVAC stands for Heat Ventilation and Air Condition. This value represents the temperature of the heat exchanger and is more or less the temperature of the air comming out of the air vents. (I assume!)

**Comment by Katana1234** [comment]
@hufman Nice implemenatation! Thank you very much for taking your time on this! I also like your concept of having multiple categories :)
In theory the layout of the categories, rows and column could be configurable within the app. But i'm already super happy with this solution and everything that follows is just cosmetics!

Side note: The clutch value seems to be a state  instead of a percentage value. At least for my car with an automatic gearbox.
Values:
3 -> "Open / Idle?" -> This value is returned while gear P is engaged
2 -> "Uncoupled" -> This value is returned while a gear is engaged but the torque converter is uncoupled (when accellerating from standing still)
1 -> ??? -> not yet seen
0 -> "Coupled" -> This value is returned while a gear is engaged and the torque converter is coupled (typically while driving)

**Comment by hufman** [comment]
Thank you! I'm pleased with how it's shaping up, after I got over the motivational cliff to add a new data pipeline to the app :)
The Battery Temp only shows a value if it's lower than 255C. If nobody sees any valid data for this field, it's easy enough to remove.
I wasn't sure what the Clutch field would show, the CDS API just calls it clutchPedal.position, just like acceleratorPedal.position, so I guessed :) Similarly, the brakePedal in my car only goes from 10-25, somehow haha.

**Comment by Katana1234** [comment]
I guess battery temperature will only work for electric cars. 
Maybe we can determine if a car is electric when engine.electricVehicleMode returns a value. just guessing... :)

And i guess clutchPedal.position works different between manual and automatic gearboxes. BMW engineers are traditionally reusing properties in different ways for different configurations :D
We can look into this in a later step. In theory we have the engine.info.gearboxType to determine what gearbox the car is equipped with. We'll probably have to compare some infos of different cars. but this is already too much for this GitHub issue :)

**Comment by hufman** [comment]
My Mini EV does have a battery temp there, it seems! I fixed a crash-on-disconnect I was seeing in analytics and merged it to the main branch, and will probably push it to the beta app store users after a week for translations to roll in.

**Comment by hufman** [comment]
@Katana1234  please experiment with the code and come up with more screens of data that you'd like to see :) I don't want to build a configuration system, but would accept ideas for how to organize the data into pre-built screens.

**Comment by Vinsvens** [comment]
First of all, thank you for the great effort made to create this app, which allows us to obtain new features in our cars.
Would it be possible to add the following data point to CDSMetrics: driving.acceleration {longitudinal= , lateral= } ?

I don't know if I'm wrong, but I think they are the different forces exerted on the car, when accelerating, braking or taking a curve in (m/s²), if we divide this value by 9.81 we could obtain the different G forces and display them on the screen.

It's just an idea and I don't know if it's correct.

Thank you.

**Comment by Vinsvens** [comment]
@hufman

**Comment by Katana1234** [comment]
@hufman Feel free to try my branch: https://github.com/Katana1234/AAIdrive/tree/car_info_data_selection

**Comment by hufman** [comment]
Very cool! I [posted a branch](https://github.com/BimmerGestalt/AAIdrive/tree/carinfo_more) with your Driving Details updates and the Windows screen. However, isn't the GPS information is already available elsewhere in the car, like in one of the side panels? I'm reluctant to add more work for the translators than necessary :) I'm considering hiding the Windows and maybe GPS behind the Advanced Settings toggle, and then I can justify not translating them.

**Comment by Katana1234** [comment]
@hufman Nice refactoring, thanks :) Yes the GPS info is kind of redundant, but you will not be able to see all of this infos in one place within the IDRIVE system. And the altitude is inaccessible in IDRIVE.

Did you take a look at my brake interpretations? The brake value is not a percentage value. It is a bit coded state:
https://github.com/Katana1234/AAIdrive/blob/bf259b1a284b956077e62676a21e53247b50505f/app/src/main/java/me/hufman/androidautoidrive/cds/CDSMetrics.kt#L201

I also added a interpretation for the clutch values, at least for automatic gearboxes. Otherwise the original number will be returned:
https://github.com/Katana1234/AAIdrive/blob/bf259b1a284b956077e62676a21e53247b50505f/app/src/main/java/me/hufman/androidautoidrive/cds/CDSMetrics.kt#L236

**Comment by hufman** [comment]
Yes I saw the brake and clutch values. I feel my car has more of a smooth gradient for brake values than a bitfield would indicate, so I didn't want to commit to that interpretation and thus the strings, if they were incorrect. I should display them as binary in my car to see how it looks. As a rough approximation I suppose those labels would be more useful than the current arbitrary number. My car is electric so I don't know how the values correlate to a gas car.

**Comment by Katana1234** [comment]
Feel free to try your brakeContact values here:
https://docs.google.com/spreadsheets/d/10FfyFMfW5VGKQGMyOlp4iCyeXoOleGbB5na0-ZFpMX8/edit?usp=sharing

This way you can validate my "interpratation" easily :)

![Uploading image.png…]()

**Comment by hufman** [comment]
Indeed, I see those values too, I'll code them up.

**Comment by hufman** [comment]
I updated [my branch](https://github.com/BimmerGestalt/AAIdrive/tree/carinfo_more) with these changes, what do you think? Any last ideas before I merge it to the main branch?

**Comment by Katana1234** [comment]
@hufman I didn't check the compiled version, but the values selected in the code looks good to me :)

**Comment by berseker** [comment]
dear @hufman , i tried this test branch. the only misreading I have to highlight is the sunroof one, since I do not have one :D

![image](https://user-images.githubusercontent.com/1159431/233156479-b2a4ac7b-28d3-490d-8e41-cb58a56a595e.png)

**Comment by hufman** [comment]
@berseker please try the latest build from the Readme, which should include a fix for your sunroof!

**Comment by berseker** [comment]
![image](https://user-images.githubusercontent.com/1159431/236009760-932f9bea-b915-4610-9c54-7d76e58f2267.png)
@hufman  now seems fine
