### ISSUE TITLE
Soundausgabe bestimmen

### ISSUE THREAD

**Issue by Yankie01** [BimmerGestalt/AAIdrive#654]
Spotify Sound ok
Google Maps und Blitzerapp unterbrechen den Sound von Spotify.
Vorschlag: Soundausgabe für jede App selber bestimmen.

**Comment by hufman** [comment]
AAIdrive can not control the sound output of the phone, and relies entirely on Android to send music through Bluetooth to the car. You'll have to manually configure your phone to disable audio notifications to prevent them from interrupting music playback.
