### ISSUE TITLE
Map Driving direction

### ISSUE THREAD

**Issue by pitum1** [BimmerGestalt/AAIdrive#659]
The view of map show strange direction not center with sign of car, bur overall it's very nice. Great Job!
Please improve!
Thank You

**Comment by hufman** [comment]
The map is offset slightly to show more of the map in front of the direction of travel.
This combines poorly with a bug some people have where the car doesn't tell AAIdrive the correct direction: https://github.com/BimmerGestalt/AAIdrive/issues/624 Please follow that bug, which is probably what you are encountering.
