### ISSUE TITLE
BMW 530i G30 Ldac question

### ISSUE THREAD

**Issue by JPersson77** [BimmerGestalt/AAIdrive#661]
Apologies in advance since I will be abusing the issues tracker since maybe I can get some answer here. But first let me express my gratitude for the app - it is a lifesaver!!

I was under the impression that I should be able to use the ldac bluetooth codec to connect to my car (bmw 530i g30) but in developer options of my samsung note20 ultra i can only select aac or sbc. And enable/disable HD audio. I cannot change resolution / bitrate as options beyong 16/44.1 is greyed out. Anyone has ldac working??

**Comment by hufman** [comment]
That's interesting, where did you find out this information? Doing a quick search, it appears that the only references are a some people recommending a [Bluetooth receiver that supports LDAC](https://www.amazon.com/Firefly-Bluetooth-Receiver-Smallest-Streaming/dp/B01HDO66NK), and [someone's Developer Settings](https://x3.xbimmers.com/forums/showpost.php?s=675d5efb63dd62a4bb76628c1d363b39&p=24850613&postcount=7) that has an LDAC-specific option enabled.

On my phone while connected to my Mini F56, I only see the options for SBC (the default mediocre-quality option) and AAC. I did notice my new phone sounded very compressed until I disabled HD Audio, perhaps that might help you?

**Comment by JPersson77** [comment]
Hi there, I wish I had more information, but my impressions were based on the same info as was linked by you. From your response I understand that it's not to be expected for LDAC to work. 

Yeah I think the sound is decent, but as you say a bit compressed (to my ears) which is why I started looking for what codec was actually used. I tried disabling HD audio but it just seemed to not work as there was no 1-second drop-out of the sound, as there is when switching between sbc and aac. I will try it again basically, but I have no idea what 'HD audio' refers to in this case. 

I appreciate the response and thanks again for the app. It is really needed!

**Comment by LACNR** [comment]
Could it been removed with an Android Version? On my S8 I can select serveral Bluetooth Codecs LDAC is one of them, addiotionally I can specifically adjust which LDAC-Play-Quality should be used.

**Comment by JPersson77** [comment]
@LACNR I think LDAC is supported by android 13 as far as I know. It is interesting that you have it working. What idrive version and car model are you sporting?

**Comment by Bushido1992** [comment]
The Smartphone automatic Choose the Best avaible codec. As example if you had a cheat bluetooth box it usually uses the SBC Codec. If you have a high Quality Box, then automatic (if Supports) the Best avaibled codec is used by system.

The Idrive has HD-Audio but no ldac Support. The phone maybe Supports it... But the idrive definitly not
