### ISSUE TITLE
App keeps reconnecting

### ISSUE THREAD

**Issue by Vasmares** [BimmerGestalt/AAIdrive#663]
Hi,

I have seen that there were some issues raised the last weeks about some connection issues.
Since ~3 weeks I also have troubles.

The App initially connects, stays connected for a few seconds, then disconnects.
Then after a few seconds it tries again. This happens in a loop.

I have attached a video.

@hufman Has anything happend that you know of ?

https://user-images.githubusercontent.com/10863304/217666740-53390805-0752-43ab-80c5-8503c1f3a3c4.mp4

**Comment by hufman** [comment]
I usually see that when MyBMW is connected over USB.
What does the car's connection status show? I would expect the Apps checkbox to keep checking and unchecking, showing MyBMW is having troubles staying connected.

**Comment by Vasmares** [comment]
As most of the time: Update is the best defence.
I updated to yesterdays nightly build of 1.4.1 and everything is working perfectly again..

sorry to have bothered you ._.
