### ISSUE TITLE
Tracks skipped when using "Now Playing" and selecting a new track (HUD)

### ISSUE THREAD

**Issue by Vasmares** [BimmerGestalt/AAIdrive#666]
Hi,

when selecting another track from the "now playing" list of tracks (of the current playlist for example), the wrong track is selected.

You can either just select "nächster" (next) and it will select the next track (works)
![20230211_013518](https://user-images.githubusercontent.com/10863304/218252195-846b1c05-14bd-420f-9d94-858dfe83ce97.jpg)

Or you can skip some tracks ahead and select the track you want. 
![20230211_013552](https://user-images.githubusercontent.com/10863304/218252244-b57d2a91-6518-45f3-9a73-8b4149605dcd.jpg)

When doing so, not the selected track is chosen, but some even further ahead.

Example:

I am on track 1, now go down the list and select track 5 and confirm my selecton. For some reason it selects track 8.
 (I use the arrows and OK button on my streering wheel)
 
 This only happens to me when I am choosing a new track from the list in my head up display.
 This same option in the center screen seems to work just fine.
 
 Any Idea ?

**Comment by hufman** [comment]
Are you using Spotify? There used to be [a bug](https://github.com/BimmerGestalt/AAIdrive/issues/291) where tracks in the Spotify playlist that aren't playable would still show up in the list and be counted in `skipToIndex`, but the Spotify app itself doesn't count them and so it would act as an offset when skipping to a track. It looks like it was [fixed](https://github.com/BimmerGestalt/AAIdrive/pull/579) for playlists that are fetched through the web api, but I forget if all playlists go through that api or just some of them.

You mention different behavior between the HUD playlist and the Now Playing screen in the center console. I have not experienced this, but they are technically different code paths and could behave differently I suppose.

**Comment by Vasmares** [comment]
I have to correct myself.

I does work. Just not always.

After upgrading to 1.4.1, I checked this all again.
Now it seems that it does work as intended. The correct track is selected.

Although, sometimes the selection does not work at all.
I can select a new track from the list and press "OK" on the steering wheel, and nothing happens.
Only the "next track" option works.

Also HUD and Instrumets screen work the same. No issue here.

So it either works fine, or not at all.
Any Ideas ?

**Comment by hufman** [comment]
The command to skip to a certain index of a queue is sent directly to the actual music app, and it's up to that app to process it appropriately. Some apps are buggy (Spotify's Liked Tracks and Artist Radio are the main examples), but it works in most other apps I've tried.
