### ISSUE TITLE
"next track" is not refocused after track selection (HUD)

### ISSUE THREAD

**Issue by Vasmares** [BimmerGestalt/AAIdrive#667]
Hi,

when selecting a new track in my HUD, the focus is not updated.
The "checked" icon is moved to the next track, as it should, but the list does not "move"
![20230211_013559](https://user-images.githubusercontent.com/10863304/218252629-7df732fc-d9df-49ba-80a1-45448399859d.jpg)

Normally the list visually moves up / down one entry, to center the current track, but also so the highlight stays on the "next" control so one could skip though the songs by just pressing "ok", and not having to select "down" and then "ok".

I know the explaining is poor...
Do you get what I mean ?

**Comment by Vasmares** [comment]
However, this works perfectly fine in the instruments display.
It also seems to be faster than the HUD

Any Ideas ?

![20230211_151354](https://user-images.githubusercontent.com/10863304/218262801-01e83f95-d7c0-4a8b-98e0-2934bea90c4e.jpg)

**Comment by hufman** [comment]
The display of this playlist is handled by the car, AAIdrive just sends the full playlist with a checkmark index and the car decides how to update the display.

**Comment by Vasmares** [comment]
I have to correct myself.

I does work. Just not always.

After upgrading to 1.4.1, I checked this all again.
Now it seems that it does work as intended. The correct track is selected.

Although, sometimes the selection does not work at all.
I can select a new track from the list and press "OK" on the steering wheel, and nothing happens.
Only the "next track" option works.

So it either works fine, or not at all.
Any Ideas ?

**Comment by Vasmares** [comment]
Ah ok.
I tested this a bit more and found out that it works "sometimes"
most of the time the selection is working as intended.

Sometimes the movement of the list does not work properly.

But as you say, this is handled by the car ?

**Comment by hufman** [comment]
Yes, AAIdrive only [sends a list of tracks](https://github.com/BimmerGestalt/AAIdrive/blob/59eff043ea01227a7553e28578526ca5ea56cb47/app/src/main/java/me/hufman/androidautoidrive/carapp/music/GlobalMetadata.kt#L94-L139) and the car is responsible for displaying it in the HUD or the Instrument Cluster. I don't know the timing of when it actually updates in the car after the app sends the data.
The HUD screen is not meant to be displayed for long, and it focuses properly after the screen disappears and is shown again.
