### ISSUE TITLE
connection problem on UI5.1

### ISSUE THREAD

**Issue by unlive74** [BimmerGestalt/AAIdrive#673]
Yesterday, a new firmware with UI5.1 arrived on my Samsung galaxy s22 and new bugs arrived with it. When turning off and on spotify on the car panel, the connection is broken and it is not restored until you start aaid (1.4-48-dec15a8) on the phone.

**Comment by hufman** [comment]
It's hard to say, what connection is broken specifically? Do you still see the Apps checkbox in the car?

**Comment by unlive74** [comment]
Maybe the [error report](https://drive.google.com/file/d/1ZoJoenb6vHHASmPAbgOVWRnzpvCvnnNv/view?usp=sharing) that the android generates will help?

**Comment by Bushido1992** [comment]
i have a s22 Ultra too (OneUI 5.1) with the latest beta on Playstore and have no problems. the app still wirks fine without any problems

**Comment by hufman** [comment]
Thank you for that debug log! It looks like both AAIdrive and MyBMW are blocked from showing a notification, which might block them from continuing to run in the background. The log shows that AAIdrive receives a timeout from the car after a while and shuts down, so check that MyBMW is still active (both in MyBMW and in the car).

**Comment by unlive74** [comment]
@hufman yes, it's true, notifications are turned off, but it's been like that for more than a year and everything worked fine before updating the phone's firmware.  ok, today I will try to turn on notifications and test it.  maybe it's some specific problem with my entryevo id5?..

**Comment by sfortis** [comment]
I've the same problem with the new oneui5.1. At some point the application is killed an tells me that "the app was paused in the background while connected to the car". BTW the app is excluded from battery optimization  (battery --> unrestricted). What the hell is Samsung doing???

**Comment by unlive74** [comment]
Turning on notifications didn't help.  I reinstalled mybmw and aaid (cleared data and cache) and it seems to have helped.  2 hours on the road - while it seems to be working.  I'll watch for a while and let you know.

**Comment by hufman** [comment]
I've heard that Samsung will keep newly installed apps in memory longer, and it may come back after a few days. The dontkillmyapp website hasn't been updated for newer Samsung versions, so information is hard to find. [This forum post](https://r1.community.samsung.com/t5/galaxy-z/auto-optimization/m-p/20204129/highlight/true#M3872) sounds like the Auto Optimization feature is always on in the latest version, but maybe the tips there will be enough?

**Comment by sfortis** [comment]
I'll try this option to keep the AAdrive open on task switcher.

![image](https://user-images.githubusercontent.com/15342157/219703990-f732fb89-094f-4e56-b79d-cf60add583b0.png)

**Comment by Bushido1992** [comment]
You need to Set MyBMW and AAIdrive to NEVER SLEEPING APPS to run in background. I have no problems on UI 5.1.

Goto Settings> battery and device care> battery>background usage Limit>never sleeping apps!

Screenshot_20230217_171409_Device care](https://user-images.githubusercontent.com/18252895/219706593-a1dad45f-4617-417a-9aa8-b527379a77da.jpg)

**Comment by unlive74** [comment]
summary: it's bad. android kills aaid (at the same time mybmw remains in memory). both applications are added to sleepless in android settings. what to do?

**Comment by Bushido1992** [comment]
Do you have other apps installed to "save" battery...maybe this apps kill them?

My settings;
Never sleeped apps > Spotify, AAIdrive, MyBMW

Both apps are "Optimised" (hold app icon, tap info button, choose Battery). optionally you can try to choose there "Unrestricted".

Reminder; When you goto recently open apps and close all, then MyBMW / AAIdrive is killed too.

As i said. no problems on OneUI 5.1. Only when i close all apps, then i must start MyBMW and AAIdrive that it connects to the Car. But after connect it runs without problems in the background

**Comment by unlive74** [comment]
> Both apps are "Optimised" (hold app icon, tap info button, choose Battery). optionally you can try to choose there "Unrestricted".
@Bushido1992 thanks for the tip - I tried adding apps to "never sleeped" but that didn't help. After I made them "Unrestricted" yesterday, they don't get killed
