### ISSUE TITLE
Not connecting automatically 

### ISSUE THREAD

**Issue by Philipmulkens** [BimmerGestalt/AAIdrive#674]
Since a couple of weeks I need to open aaidrive app on my phone in order to connect to the car's idrive. No battery saving functions enabled on the phone. Any solutions for this?

**Comment by hufman** [comment]
As part of updating to support recent Android versions, the app now requires explicit permission to wake up in response to Bluetooth connections. There should be a permission box in AAIdrive asking for that, does that not show up?

**Comment by Philipmulkens** [comment]
Yes, thank you. I misunderstood the option so it wasn't enabled.
Now it works just fine.

Op vr 17 feb. 2023 03:21 schreef Walter Huf ***@***.***>:

**Comment by hufman** [comment]
I'm glad it works for you!
