### ISSUE TITLE
iDrive freezing since new android update

### ISSUE THREAD

**Issue by 22Dragos** [BimmerGestalt/AAIdrive#678]
Quite a recent issue a have experienced for a few weeks since I've updated my android software. iDrive keeps freezing for a few minutes, music keeps playing then it disconnects and can't connect back under any circumstances with the AAIdrive to my car

Maybe a new update will fix this issue

**Comment by hufman** [comment]
It sounds like MyBMW is stopping in the background, do you see the Apps checkbox stay checked in the car? Do you see the MyBMW and AAIdrive notifications running? Perhaps the update changed the battery optimization settings and you may need to set them again.

**Comment by 22Dragos** [comment]
It random checks and unchecks, I checked the battery optimization settings and it's ok on unrestricted, the AAIdrive app runs in the background all the time but the connection keeps droping after a few minutes I use the app. Music keeps playing but when I try to switch the song nothing happens and when I open my phone to switch it from there it disconnects, the app saying that I need to turn car apps on even if they are on. I thought the update had something to do with that, the recent update they had for android 13. Had problems with the connection random dropping before the update too, but they were rare and just ignored them and connected back, now it's up to the point I can't even use the AAIdrive under any circumstances 
 
  Pe mie., mar. 1, 2023 la 6:44, Walter ***@***.***> a scris:   


It sounds like MyBMW is stopping in the background, do you see the Apps checkbox stay checked in the car? Do you see the MyBMW and AAIdrive notifications running? Perhaps the update changed the battery optimization settings and you may need to set them again.

**Comment by hufman** [comment]
It sounds like MyBMW isn't keeping the connection open to the car (Apps checkbox keeps unchecking). The car is sending a heartbeat to MyBMW and MyBMW isn't responding in time (about 30seconds of timeout) and so the car indicates that the connection has closed. This would also explain why the car interface appears unresponsive: MyBMW isn't proxying the commands from the car to AAIdrive, and MyBMW isn't proxying the screen updates from AAIdrive to the car.
Please check all the places that the phone vendor might hide Battery Optimization settings to make sure MyBMW can stay running. You could also try uninstalling and reinstalling MyBMW and AAIdrive, which might help for a few days before the phone starts "optimizing" app usage again.

**Comment by 22Dragos** [comment]
Looks like giving unrestricted to MyBMW too seems to help, no connection dropped since I've done that. Thanks for your help ! 
 
  Pe joi, mar. 2, 2023 la 17:40, Walter ***@***.***> a scris:   


It sounds like MyBMW isn't keeping the connection open to the car (Apps checkbox keeps unchecking). The car is sending a heartbeat to MyBMW and MyBMW isn't responding in time (about 30seconds of timeout) and so the car indicates that the connection has closed. This would also explain why the car interface appears unresponsive: MyBMW isn't proxying the commands from the car to AAIdrive, and MyBMW isn't proxying the screen updates from AAIdrive to the car.
Please check all the places that the phone vendor might hide Battery Optimization settings to make sure MyBMW can stay running. You could also try uninstalling and reinstalling MyBMW and AAIdrive, which might help for a few days before the phone starts "optimizing" app usage again.

**Comment by hufman** [comment]
Perfect, that's wonderful to hear! I don't know how to have AAIdrive detect and add a hint when MyBMW is shut down in the background =\
