### ISSUE TITLE
Crashing and buggy with Samsung s23 Ultra

### ISSUE THREAD

**Issue by NickB1772** [BimmerGestalt/AAIdrive#679]
Love this app, it's a brilliant work around for those using Android, and it worked brilliantly with my S22. However, since upgrading to the s23 ultra it's very hit and miss. The connection drops out regularly, I can't access Spotify even when it's showing on my dash (buttons won't work), and often Spotify content shows as 'empty'. It also freezes. I've reinstalled the app, and reconnected my phone to the car but it's still not behaving

**Comment by Bushido1992** [comment]
Sounds like bmw / spotify app is close in background. Check your app settings.

Set MY BMW/aaidrive/Spotify to "unrestricted"( hold app icon, tap info button, choose Battery, then choose  "Unrestricted" to the 3 Apps and test again.

**Comment by hufman** [comment]
Someone with a [S22 encountered a similar problem](https://github.com/BimmerGestalt/AAIdrive/issues/673#issuecomment-1435986798) after upgrading to UI5.1, please try their tips to set the MyBMW and AAIdrive battery usage to Unrestricted.
Please also check that the car continues showing the Apps checkbox as checked (meaning MyBMW is still connected to the car) and that both MyBMW and AAIdrive's notifications are showing.

**Comment by NickB1772** [comment]
> 

Hi, thanks for this. All three are on unrestricted battery, so not sure why I'm getting the problem

**Comment by NickB1772** [comment]
> 

Hi, yes all on unrestricted and all notifications are showing. The car is still showing apps checked

**Comment by dimakaob** [comment]
Hello there! 
Galaxy S23 Plus. 
Same problems. 
All the battery settings set to never kill, unrestricted etc. 
One UI 5.1 is not the reason, because my previos S21 Ultra with One UI 5.1 worked fine.

**Comment by hufman** [comment]
I'm sorry to hear that! There aren't any ways that AAIdrive and MyBMW can stay in memory beyond running a Foreground Service notification (and even asking the user to exempt battery optimizations is somewhat against the Play Store rules), so hopefully other Samsung users can come up with a workaround!

**Comment by dimakaob** [comment]
Well, today for about 2 hours everything was fine. I set to "unrestricted"
both apps. Not just aaidrive.
Keep watching =)

пт, 10 мар. 2023 г., 20:17 Walter Huf ***@***.***>:

**Comment by Bushido1992** [comment]
if set Apps to unrestricted / never sleeping not work, then another app (not Samsung) must kill them to run in background.

The last Thing you can do is check if aaidrive/my bmw is already excluded on memory settings;
Settings>Battery and device care > Memory > excluded Apps

More you cannot Set. If the app then dont work it's not Phone / Samsung related

**Comment by simPod** [comment]
I had the same issue with S23 (the little one). 

- Disabled battery optim for AAI and MBMW
- also excluded from Memory care

Today I had no more issues (spotify stopped playing once so maybe I'll have to exclude that too, but connection was stable overall).

**Comment by Kelvfimer** [comment]
Hello 

I followed the steps provided here (battery unrestricted, allow notifications and memory care) and I'm still unable to make spotify app work. I have these screen and i can't change song, view the title etc it is like everythinf disable

The funny thing is if I go to notificacions section i can see the song, the álbum cover and change song.

Pls somebody can help me to set up spotify app? Thx
![20230408_191625](https://user-images.githubusercontent.com/85133404/231585732-7b5941d5-5e12-4f25-886e-2dd3bc89fdf4.jpg)
![20230408_191652](https://user-images.githubusercontent.com/85133404/231585807-58ea873a-5bd4-4127-ac6a-6f421e56856e.jpg)

**Comment by hufman** [comment]
Do other aspects of AAIdrive function properly? If Samsung is pausing the app in the background, the menu handler to open the app from the car's main menu wouldn't function, and the Notifications and Calendar apps wouldn't update either.
Do other music apps work?

**Comment by Kelvfimer** [comment]
Whatsapp Notifications works and if I go to the book icon (that contains all notifications) and open the spotify notification the cover of the album and the name of the song is there, besides I can change the song from there. However using the spotify app doesn't work. Other functionality such as detailed vehicle info works too.

**Comment by hufman** [comment]
Does the app connection to Spotify work? Try tapping Spotify from the Music tab of the phone interface to test it.

**Comment by Kelvfimer** [comment]
Yes it does work. The funny thing is the app from notifications works.

So if I go to notifications, click on the book and click on the spotify notification it works.

![Uploading 20230414_180230.jpg…]()
![Uploading 20230414_180241.jpg…]()
![Uploading 20230414_180247.jpg…]()

**Comment by Kelvfimer** [comment]
Yes it does work. The music sounds woth spotify app or bluetooth. But when getting the spotify app I get the images shown. The funny thing is the app from notifications works.

So if I go to notifications, click on the book and click on the spotify notification it works

![20230414_180230](https://user-images.githubusercontent.com/85133404/232114788-4e859a35-d1e0-4e97-a997-389d31a14e96.jpg)
![20230414_180241](https://user-images.githubusercontent.com/85133404/232114863-60b6d9f2-c6fd-44b6-ad9b-19bef3f3a525.jpg)
![20230414_180247](https://user-images.githubusercontent.com/85133404/232114889-cc153e34-c2bf-4e98-b3f4-93e69b21135f.jpg)
