### ISSUE TITLE
bluetooth disconnection

### ISSUE THREAD

**Issue by GIGIO71** [BimmerGestalt/AAIdrive#684]
using spotify with bluetooth and the app mini keeps disconnecting then reconnecting, i use it with galaxy s20fe,

**Comment by hufman** [comment]
You should check that the Mini app has all the various background execution limits and battery optimizations disabled, people have experienced disconnections with S22 and S23 after upgrading to UI5.1: #679

**Comment by spofali** [comment]
I also started to have the disconnection after updating to UI5.1. same story with my wife's phone. Check all the permissions and all looks good

**Comment by hufman** [comment]
What do you mean by "disconnection"? Does the entire Bluetooth connection disconnect, does the Apps icon get unchecked from the car, or does the Apps icon stay checked while AAIdrive shuts down unexpectedly? If MyBMW/Mini is paused in the background, the Apps heartbeat will be missed and the car will disconnect the Apps icon, which is my guess for what's happening.

**Comment by spofali** [comment]
Ok... I played with the permissions. The battery optimization needs to be set to unrestricted instead of optimized for both apps - MyBMW and AAI - and then it doesn't fail. Tried this for more than 8 hrs journey and works without any problems. battery life also not affected much.

**Comment by hufman** [comment]
Glad to hear it worked for you!
