### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by Mikkooooo** [BimmerGestalt/AAIdrive#685]
Hi, I‘ve installed and I can‘t hear any sound on my BMW F15.
All other  features are working properly.
I can only hear sound (from Deezer, Jet…..) on my android handy ( Android 9 ).
Where is my issue ?
Regards, Frank

**Comment by hufman** [comment]
AAIdrive does not change how your phone sends music to your car. Is your phone paired with your car over Bluetooth and able to play music through your car's Bluetooth music connection?

**Comment by hufman** [comment]
Thank you for the compliment!
Unfortunately, that support would have to be enabled on Deezer's side. Please reach out to the Deezer support team and request that they let AAIdrive connect to their MediaBrowserService to fully control their app.

**Comment by Mikkooooo** [comment]
Thanks again Walter,
is Spotify fully supported - also for the head up display ?

Walter Huf ***@***.***> schrieb am Di., 21. März 2023, 04:21:

**Comment by hufman** [comment]
Yes, Spotify support was built specially because Spotify provides a local control API.

**Comment by Mikkooooo** [comment]
Many thanks again Walter,
I've just tried Spotify and it works
very good.
I'm on ID4++ and sometimes ist's a little bit difficult to connect.
Then I open the AIIdrive App manually at first and after that I put in the
USB cable and let the Classic Connect App v.1.8  connect to my car.
I'll do some more testing this weekend and after that I'll donate
your very useful work !!!
Frank


Walter Huf ***@***.***> schrieb am Do., 23. März 2023, 03:51:

**Comment by hufman** [comment]
Oh ID4 doesn't support music app playlists in the Heads Up Display, sorry about that!

**Comment by Mikkooooo** [comment]
Walter,
My HUD ist working ok with Spotify.
I can see and control the playlists.
Maybe it isn't ID4. I'll loock into the
AIIdrive app.



Walter Huf ***@***.***> schrieb am Do., 23. März 2023, 16:19:

**Comment by Mikkooooo** [comment]
Thanks Walter,
you were right, HUD doesn*t run properly with ID4++.
The music titles are confused in my HUD, after switching MODE to radio and back solves the issue sometimes but not always.
That's a pity but I can live with that.
One another question:
I've also installed HASS and Screen mirror.
In the menu they have the same icon - a circle icon both the same one.
Is it possible to give them different icons ?
What's about HomeAssistant icon or so ?
Another thing I've noticed ist the car's position in MAPS : I see an arrow that has the wrong orientation. Can I change it to an dot instead an arrow ?

**Comment by hufman** [comment]
No, it's impossible to change the main app icon or text, it can only show or hide the icon and text.
The map doesn't support showing only a dot, I don't know why the car would give a wrong answer for the compass bearing. It sounds like the same issue that was reported in #624

**Comment by hufman** [comment]
Please try the new beta build in the Play Store to check what compass direction the car reports through the new Car Info screen.

**Comment by efiopas88** [comment]
Having same issue with No sound. F06 id4++

**Comment by hufman** [comment]
What music source is your car listening to? With ID4, you need to select your phone's Bluetooth connection.

**Comment by efiopas88** [comment]
Hi, thanks for reply, got the sound by turning Spotify in the apps and switching to Bluetooth, but then im getting my cars player on the screen instead of Spotify screen with art etc...

**Comment by Mikkooooo** [comment]
There are two Players in the Display
one for Spotify and another only for BT.
Choose the one for Spoitify
