### ISSUE TITLE
Stable in Mini F56 ID5

### ISSUE THREAD

**Issue by markjcw** [BimmerGestalt/AAIdrive#686]
Thanks to the developer for this great app.. 

Just some info for S23 Ultra owners.. AAidrive app and my Mini app are both unrestricted.. also I have told the phone to not kill these apps in backround via adding them to excluded apps in memory section.

App has been stable ever since and just works.. also no detrimental effect on battery.

Thanks again for a superb app.

**Comment by hufman** [comment]
That's great to hear!
Can you take some screenshots of your phone settings to help other people know where to find these options, and can you post instructions in the [Discussions tab](https://github.com/BimmerGestalt/AAIdrive/discussions)?

**Comment by markjcw** [comment]
> That's great to hear!
> Can you take some screenshots of your phone settings to help other people know where to find these options, and can you post instructions in the [Discussions tab](https://github.com/BimmerGestalt/AAIdrive/discussions)?

Ok will do thanks.

**Comment by hufman** [comment]
Would you still be able to post screenshots about how you enabled the apps to stay connected? There are still reports of Samsung S23 users having troubles with the car connection.

**Comment by hufman** [comment]
Thank you so much! I saw the post and moved it to the top of the Discussions tab.
