### ISSUE TITLE
API33 Required On September 2023

### ISSUE THREAD

**Issue by hufman** [BimmerGestalt/AAIdrive#687]
Per [the timeline](https://support.google.com/googleplay/android-developer/answer/11926878), and [migration guide](https://developer.android.com/about/versions/13/behavior-changes-13).
The big change is the Foreground Notification requires a permission. There's already a [branch](https://github.com/BimmerGestalt/AAIdrive/tree/api33) with changes to test. I'm not actually sure if the notification permission denial actually affects the background service execution, or just affects visibility. It would be great if it didn't affect functionality, so that it doesn't need to be a checkbox during the initial wizard and can show up later.
I'm also unsure about the [wording](https://github.com/BimmerGestalt/AAIdrive/commit/7a095b6ffcb088a1e944c2830a14865bffe40180#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103R84).

[Test build available here](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-api33-mapbox-sentry-release.apk)

**Comment by bogdan-calapod** [comment]
> Access to show a service notification to stay running while connected to the car

Would something like this work ? 

> Allow service to stay running when connected to car (shows a permanent notification while connected)

**Comment by hufman** [comment]
The problem is that I'm not sure if it's actually required, so I don't know how firm to make the language!

**Comment by hufman** [comment]
Samsung OneUI6 will be based on Android 14, and there are [reports](https://www.sammobile.com/news/samsung-android-14-one-ui-6-0-update-kill-background-apps-less-frequently/) that it will stop killing apps that target Android 14 (API34). Upgrading AAIdrive will help only a little, since MyBMW will also need to target Android 14.

**Comment by hufman** [comment]
Spotify [posted a new SDK version](https://developer.spotify.com/blog/2023-07-06-new-android-sdk-version) to add support for this new API level.
