### ISSUE TITLE
Latest Beta Version Depends on My BMW from US

### ISSUE THREAD

**Issue by my-ix** [BimmerGestalt/AAIdrive#694]
Hi, I am from Malaysia and have My BMW application installed to be proxy for this application to run, unfortunately, it keeps on asking to install My BMW from Play Store which opens other country which I am not able to download, I suspect it's US

**Comment by hufman** [comment]
Nothing in AAIdrive's MyBMW detection should have changed in the last year or so. Can you share the Play Store link or the package name of your installed MyBMW application, perhaps AAIdrive isn't detecting it properly?
AAIdrive only links to the US version because it thinks your phone is US, by default it links to the European version.

**Comment by my-ix** [comment]
Hi,

It's within your mobile application, clicking will try to open https://play.google.com/store/apps/details?id=de.bmw.connected.mobile20.na

Even I already have installed:
https://play.google.com/store/apps/details?id=de.bmw.connected.mobile20.row

I am not sure what's the difference between .na and .row

**Comment by my-ix** [comment]
Hi,

I am able to install both MyBMW and MINI app, but not Supra app due to country restriction similar with the link to install MyBMW within your app.

Even when I have both of them installed, your app still require me to install the different country's MyBMW.

**Comment by my-ix** [comment]
> That's the difference (North America vs Rest Of World). I'm puzzled, because AAIdrive has many more European users than American users and you are only the second person to notice a problem. What version of MyBMW do you have? I see 3.3.1 in the store, and the same version in America.

Both of those links are pointing to the same version which is 3.3.1

**Comment by galenzhao** [comment]
does it support Chinese ver？
our app is：de.bmw.connected.mobile20.cn

**Comment by hufman** [comment]
If AAIdrive says it can connect to any car (even Mini), it has found the security service and will work with your MyBMW connection. Does it say it is ready to connect to Mini with the Mini app installed?

**Comment by hufman** [comment]
AAIdrive does not know about the Chinese version, thank you for the pointer! It should be easy enough to add support for it.
Until then, you should install (perhaps manually) the US or European version of MyBMW/Mini/Supra app to get the security service (and AAIdrive should say it is ready to connect), and then AAIdrive _should_ connect through the Chinese MyBMW's connection to the car.

**Comment by galenzhao** [comment]
Hi, the app seems has some problem on bmwapp detection.
I installed the following apps, downloaded from external readme.md.

1|ruby:/ $ pm list packages|grep bmw
package:de.bmw.connected.mobile20.cn
package:de.bmw.connected.mobile20.na
package:de.bmw.connected.mobile20.row
package:de.bmw.connected.na
ruby:/ $

But aaidrive can not detect it sometimes.

**Comment by galenzhao** [comment]
![Screenshot_2023-05-04-10-42-50-948_me hufman androidautoidrive](https://user-images.githubusercontent.com/3184101/236099985-7657ec4b-a279-4472-a414-fd5caacc2651.jpg)

**Comment by galenzhao** [comment]
> > That's the difference (North America vs Rest Of World). I'm puzzled, because AAIdrive has many more European users than American users and you are only the second person to notice a problem. What version of MyBMW do you have? I see 3.3.1 in the store, and the same version in America.
> 
> Both of those links are pointing to the same version which is 3.3.1

Could you check your phone settings.
Maybe you set your location to US.

I checked aaidrive code. It using system settings to determine which bmw app should installed,and it maybe not same region with gplay.

**Comment by hufman** [comment]
Thanks for making me test it out and helping find the bug! AAIdrive was never updating the BMW installation status in the UI after the initial draw, even after the async connection happened.
Please test [the latest build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-main-mapbox-sentry-release.apk) which should fix this, and also add support for the Chinese MyBMW app.

**Comment by hufman** [comment]
AAIdrive picks the US version if [the phone's locale is set to US](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/java/me/hufman/androidautoidrive/phoneui/controllers/DependencyInfoController.kt#L9), otherwise it defaults to the Rest of World version. What locale is your phone set to?

**Comment by my-ix** [comment]
Hi,

I don't have any problem installing any application, I set my phone to use US as locale, and country is Malaysia.

I suggest the application to just check any of My BMW installed, why in the first place what to lock that?

**Comment by hufman** [comment]
AAIdrive does check if any MyBMW is installed, and as of the latest build (and the latest Play Store beta) it will even properly show that it found it. The connection logic still worked, even though the UI was prompting to install MyBMW, but now it will know that it's already installed and not prompt.
