### ISSUE TITLE
No connection to BMW idrive6 

### ISSUE THREAD

**Issue by Japiootje** [BimmerGestalt/AAIdrive#722]
Goodmorning, installed mybmw and aaidrive, I don't have a good connection with idrive6 screen. I don't see the appstore on my screen.

**Comment by hufman** [comment]
Good morning, there is no app store to show in idrive.
Does your BMW have the App checkbox under the mobile devices section? This should show up if you have an active BMW Connected subscription.

**Comment by Japiootje** [comment]
Goodmorning,

Sorry, I meant apps instead of appstore, this had to do with the automatic
wordchoice on my Phone. What I mean is that I can't see for instance the
library of Spotify. I don't see rhe checkbox in the list you mention.
Kind regards,

Jaap Drenth

Op zo 16 jul. 2023 18:26 schreef Walter Huf ***@***.***>:

**Comment by Japiootje** [comment]
Van: Jaap Drenth ***@***.***> 
Verzonden: maandag 17 juli 2023 21:26
Aan: ***@***.***
Onderwerp: No connection to BMW idrive6 (Issue #722)

 

Thank you for your swift reply. As soon as I have the time I will contact the dealer, I still have a subscription till 15 juni 2024. This is what I see on my screens. 

 

Kin,

 

Jaap Drenth

**Comment by hufman** [comment]
Picture attachments don't make it through email, you must attach directly in GitHub.

**Comment by Japiootje** [comment]
Sorry about that!

Op di 18 jul. 2023 08:23 schreef Walter Huf ***@***.***>:

**Comment by Japiootje** [comment]
This is what I see

![IMG_0123](https://github.com/BimmerGestalt/AAIdrive/assets/139671917/325d3431-ab7c-40fc-ae44-f8ae1fe6fb10)
![IMG_0122](https://github.com/BimmerGestalt/AAIdrive/assets/139671917/cb1cb92b-4eea-4cc4-8448-b664b465be9b)
![IMG_0121](https://github.com/BimmerGestalt/AAIdrive/assets/139671917/3a2295a5-88ba-4fe2-80dc-a936b4891bbf)
![IMG_0119](https://github.com/BimmerGestalt/AAIdrive/assets/139671917/558cb710-72ab-40a7-9347-3bb640acaa64)
![IMG_0120](https://github.com/BimmerGestalt/AAIdrive/assets/139671917/7dcd1b01-3f1f-4f69-ab36-d76d8973b34f)

**Comment by hufman** [comment]
[This discussion](https://github.com/BimmerGestalt/AAIdrive/discussions/675) suggests that there are levels of subscription, and the base level might not be enough, but it might be different in your region. My Mini app has [a Device Connection section](https://github.com/BimmerGestalt/AAIdrive/issues/639#issuecomment-1354098471) that shows whether the car is connected, does your BMW app show that section too?

**Comment by Japiootje** [comment]
![image](https://github.com/BimmerGestalt/AAIdrive/assets/139671917/1d33b164-583c-4ad9-a8fe-7100fd0c2c7f)

**Comment by hufman** [comment]
I don't see a matching Device Connection option in your MyBMW interface, it looks like it only shows the Remote History (Remote-geschiedenis) option. What subscription options do you have? [This comment](https://github.com/BimmerGestalt/AAIdrive/discussions/675#discussioncomment-5211221) suggests you need a subscription that includes Traffic and Weather options for the car.

**Comment by Japiootje** [comment]
But I do have for instance Flickr, Wheather, Wiki local.
![IMG_0121](https://github.com/BimmerGestalt/AAIdrive/assets/139671917/0d907ffe-c7b6-46af-aaa6-27ca71b293be)
 have

**Comment by Japiootje** [comment]
Ok, thanks for the reply.  I overheard BMW employees telling eachother that
BMW has some issues with some Samsung models.  Bit thank again for your
help.

Kind regards,

Jaap Drenth

Op wo 19 jul. 2023 16:55 schreef Walter Huf ***@***.***>:

**Comment by Japiootje** [comment]
Finally got it working, hurray!!

**Comment by hufman** [comment]
Glad to hear!
