### ISSUE TITLE
? Detailed vehicle information

### ISSUE THREAD

**Issue by Dephead2004** [BimmerGestalt/AAIdrive#726]
Good day. As per the title and photo in discussion section, I have a ? At the start of the title page when displayed in the iDrive.

The logo show s up correctly under my vehicle though.

Any thoughts?

**Comment by hufman** [comment]
AAIdrive reuses existing BMW application resources, and the new Car Information app uses a resource set that is especially restricted. The title page widget you indicate is a button, and it holds a single text model to set the label. For some reason, any text that is put in this label field is prefixed by the ? character, as you see. I don't know why this is, and so I don't know how to change it.

**Comment by Dephead2004** [comment]
Thanks for the clarity. You're working magic with limited resources on a proprietary OS. What's one little ? It matters not.
