### ISSUE TITLE
Karaoke / Lyrics Plugin

### ISSUE THREAD

**Issue by berseker** [BimmerGestalt/AAIdrive#739]
Hi Just wanted to drop an idea for a possibile plugin.. would It be possibile to implement such a plugin to make some long group trips a bit more fun :) something even simple that search lyrics of the current running Song/artist and shows It on the screen

Thanks again for this jem of an app :)

**Comment by hufman** [comment]
That would be fun, but I was unable to think of a timed lyrics source that would be free and reliable to use and accurate when searching from the song metadata.

**Comment by berseker** [comment]
https://robwu.nl/lyricshere/#config this Chrome extension uses plenty of lyrics sources, idk If they are all free or not but It could be worth checking out ;)

**Comment by HaivanJV** [comment]
What about the Spotify embedded lyrics viewer?
https://support.spotify.com/us/article/lyrics/

**Comment by hufman** [comment]
LyricsHere's lyrics are not likely to be timed, unfortunately, based on the sources they list.
Spotify's lyrics seem to not be provided through [their api](https://developer.spotify.com/documentation/web-api/reference/get-track).

**Comment by berseker** [comment]
https://github.com/akashrchandran/spotify-lyrics-api would this be useful?

**Comment by hufman** [comment]
Thank you for that link. It would be helpful, either as a backend proxy or for reimplementation in Kotlin.

However, I've decided that this feature can't be provided by AAIdrive. Spotify could get annoyed about poking their unofficial API and ban the API key, disabling all Spotify features for AAIdrive. The feature itself would be very distracting, and it's not good to enable such distracted driving.
I'm sorry, but I can't build this feature into AAIdrive.
