### ISSUE TITLE
Pause music when listening to WhatsApp Voice Message

### ISSUE THREAD

**Issue by berseker** [BimmerGestalt/AAIdrive#740]
I have the same comment/request described here

https://community.spotify.com/t5/Android/Android-Music-Pause-music-when-listening-to-WhatsApp-Voice/td-p/4784135

 Is there a way to implement such a feature in AAidrive regardless of the app currently selected for playing music? Or It would be impossible to "intercept" that on the phone an user started listening of an arrived audio message?

Thank you

**Comment by hufman** [comment]
I do not believe it's possible to detect when WhatsApp is playing a voice message, if it isn't already participating in the normal Android method to quiet the music.

**Comment by berseker** [comment]
hi hufman, i use again this old thread to change a bit a possible request.. could it be possible to allow playing of a received voice message from the car?  usually when you receive a voice message in whatsapp, a notification appears but it is not possible to open that message except taking the smarthphone, and pushing the play button in it... 

it could be a nice additional touch to this great app :D

thank you

**Comment by hufman** [comment]
No, it is almost certainly impossible that WhatsApp allows other apps on the phone to retrieve voice messages.
