### ISSUE TITLE
Push FM Radio station logo?

### ISSUE THREAD

**Issue by Labje82** [BimmerGestalt/AAIdrive#743]
I am very happy with AAIdrive. works fantastic! I have one request to make AAIdrive 100% complete 😃

Is it possible to interpret the radio station name (as ID) in AAIdrive and based on that send a radio station logo back to the NBT Evo?

Is this functionality that can be added? It then would be nice to have the user functionality in AAIdrive to create and edit a database with radio names and associated logos to do the mapping.

**Comment by hufman** [comment]
Most internet radio apps already provide coverart, which is shown by AAIdrive. What do you find is missing?
If you mean, read the FM radio information and send a cover art to the car, this is impossible. Whichever app in the car that is playing music (Bluetooth, FM Radio, AAIdrive), has control over the music metadata, including coverart, so AAIdrive can not show extra information while the FM Radio is playing.
