### ISSUE TITLE
Cannot connect iD6 - missing APP box

### ISSUE THREAD

**Issue by Nikpanigada** [BimmerGestalt/AAIdrive#744]
Goodmorning, I cannot connect to the car because the app asks for allow my telephone to use apps in the car menu. The problem is that i have connected drive service and i cannot see this option. That's what i see:
![inbound4638881855105072280](https://github.com/BimmerGestalt/AAIdrive/assets/149329675/4a01082b-1666-4e39-b411-f1852516e601)

**Comment by Nikpanigada** [comment]
![inbound9179186461639850904](https://github.com/BimmerGestalt/AAIdrive/assets/149329675/012c0905-e987-4c19-a99a-429372892553)
![inbound2514080057631174702](https://github.com/BimmerGestalt/AAIdrive/assets/149329675/ce48c63d-79a9-4197-a40b-ecec1dfd2264)

**Comment by hufman** [comment]
Unfortunately, this is up to your BMW. Try asking the dealer services about why your ConnectedDrive subscription isn't activating the feature in the car. Try unpairing in the car, and then seeing if the pairing menu offers to connect for Apps or just Music.
