### ISSUE TITLE
Google Pixel 8 AAI Drive Mini F56

### ISSUE THREAD

**Issue by Olre1** [BimmerGestalt/AAIdrive#745]
Google Pixel 8 AAI with Mini F56 the app does not establish a connection to the car.

Normal Bluetooth connection works but no apps appear

Everything works with the Galaxy s23

does anyone have any advice

**Comment by hufman** [comment]
Does the car show the Apps checkbox as filled in, and does the Mini app show the Apps connection as successful? That is a prerequisite for AAIdrive to connect.

**Comment by Olre1** [comment]
No, the apps are no longer displayed.  since Google's November update

**Comment by hufman** [comment]
Try unpairing the phone and pairing in the car again with the Apps option. If the Apps pairing option doesn't exist, try checking your ConnectedDrive subscription or asking the dealer for assistance.

**Comment by Olre1** [comment]
The AAI drive app does not establish a connection with the Google Pixel 8. it occurred after Google's November update. Before the update it worked. Everything works with the Samsung galaxy s23. I'll probably have to wait until this is fixed with an update for the Google Pixel 8. Best regards
