### ISSUE TITLE
 Cannot Grant Permissions for Spotify

### ISSUE THREAD

**Issue by bmodda** [BimmerGestalt/AAIdrive#746]
I am an avid user of AAIdrive and have used it with many phones - old and new. My issue is with the use of a Unihertz Titan phone that runs on android 10. The AAIdrive app installs ok. The issue is with Spotify permissions. If i click on Control over active music apps i can select an option but when i return to the previous screen the checkbox has no tick. In addition when I click the Ability to browse your spotify library GRANT button, nothing happens. This renders the app unusable.

All apps are fully updated, set to run in the background and no battery optimisations

I would be grateful for some insight and hopefully a solution.

**Comment by hufman** [comment]
Hmmm not sure why the Active Music Apps / Notification Permission isn't working. The Browse Spotify permission requires calling out to the Spotify app, which also should work fine. I see that phone has the relatively older Android 11 version, so it should be well-tested, but perhaps it has some unique security restrictions?

**Comment by bmodda** [comment]
its actually android 10. is this handset too old and incompatible with aaidrive.

**Comment by hufman** [comment]
Not at all, AAIdrive is available down to Android 6. If possible, could you share a logcat dump? It might have some clues about what is being restricted, especially from the system side.

**Comment by bmodda** [comment]
Thank you for your interest. Your original hunch was correct. There was an option in the settings to block apps that was buried under layers of menu. Spotify was blocked for some strange reason. All now okay.

**Comment by hufman** [comment]
That's great to hear!
