### ISSUE TITLE
Detailed Vehicle Info - items disappeared after reinstall of AAIdrive app

### ISSUE THREAD

**Issue by duholino** [BimmerGestalt/AAIdrive#747]
Hi everyone.

Long time lurker, first time posting.

In the last month I had a connection problem with my 2019 F31 with iDrive5 and had to uninstall and reinstall the app. Clearing data somehow didn't fix the problem.

I reinstalled the app and noticed that some entries from the iDrive5 "Detailed vehicle info" menu went missing. I'm not sure exactly what it was but I remember I had and entry named "Windows" where it showed all of my windows status and also roof window, how much % was it open, if it was tilted etc.
Also in the Driving details entry which I still have, there were more data entries, for example it showed the mode of the automatic transmission if it was Coupled, Uncoupled, Coasting, etc.

All of these entries are gone I cannot bring them back. I don't know what I did the first time I installed the app a year or more ago.

Is there an addon I must install, a mod somewhere or was it simply removed from the app between updates?

![driving info](https://github.com/BimmerGestalt/AAIdrive/assets/151583995/6ea544ab-695c-4673-ab66-c72a7427d8c4)

**Comment by hufman** [comment]
Those extra options are enabled if you enable Show Advanced Settings under the Settings tab. This way I don't need to have all those strings translated, since I'm unsure what half of the car data means :)
