### ISSUE TITLE
Strange behaviour 

### ISSUE THREAD

**Issue by Luke5019** [BimmerGestalt/AAIdrive#748]
Sometimes I can't search my Spotify playlists, I don't change anything but turning the car off and on again fixes it?

Anyone shed some light on this?

**Comment by hufman** [comment]
I think I've heard of a similar bug that occurs when AAIdrive tries to connect to Spotify while the phone does not have internet access, so Spotify is unable to confirm the AAIdrive API key.
I don't believe there's any workaround for that, besides switching AAIdrive to a different music and back to Spotify, after your phone has cell connectivity.

**Comment by Luke5019** [comment]
Ahh okay that would make sense since I don't have signal where I park. Would enabling soundcloud & then switching between the two work?
