### ISSUE TITLE
Heads up: is it compatible ? is there any api for it ?

### ISSUE THREAD

**Issue by Chuckame** [BimmerGestalt/AAIdrive#750]
Hey,
kotlin/java/flutter here, is the heads-up display showing map directions (or other data like speed limits, distances, etc) while using google maps or other navigation apps? 
If not, is there any known api that I can help with to implement it ?

**Comment by hufman** [comment]
Unfortunately, as far as I know, the HUD has no API access beyond the music playlist functionality :(

**Comment by Chuckame** [comment]
Sad to have cars tso closed 😭

And what about direct access to the OBD, did you do some reverse engineering or have you got some knowledge/project about it?

**Comment by Chuckame** [comment]
I've found this doc about hud: https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://ia801005.us.archive.org/11/items/BMWTechnicalTrainingDocuments/ST402%2520Body%2520Electronics%2520III/15b%2520E70%2520Head-up%2520Display.pdf&ved=2ahUKEwiVrLCctu-CAxWqUqQEHXqsAMoQFnoECBgQAQ&usg=AOvVaw0dJUb3h6PynSytjzore_aV

Apparently the navigation instructions are going through the kcan bus

**Comment by hufman** [comment]
That was a fun read, thanks!
I haven't done any OBD reverse engineering or investigation, AAIdrive interacts with a much higher-level API that doesn't provide very much access to the car itself.
