### ISSUE TITLE
Idrive6 connection issues

### ISSUE THREAD

**Issue by Sflaguy** [BimmerGestalt/AAIdrive#755]
Hello and thank you for all you do. I have a 2018 X3 with idrive6. I recently got an X1 for myself and gave the X3 to my wife. I have a Samsung flip and have never had any issues getting everything to work with either car. My wife has a Samsung S23 and for some reason I cannot get aaidrive to recognize connected drive is subscribed to. I have tried uninstalling and reinstalling both aa8driveand connected drive. I have tried clearing the cache of both apps. Please give me some guidance on how I can get aaidrive to work in the 2018 X3 idrive6 with my wife's Samsung S23. Thanks so much!!

**Comment by hufman** [comment]
I'm glad you are enjoying it!
The Samsung S23 has notorious bugs about background app execution, can you try some of these hints to allow AAIdrive and MyBMW to run in the background and connect to the car? https://github.com/BimmerGestalt/AAIdrive/discussions/709

**Comment by Sflaguy** [comment]
Thanks for your fast reply. I'll make the changes to my wife's phone when I get home. I really appreciate your prompt attention!

**Comment by Sflaguy** [comment]
Okay. My wife's phone now has the aaidrive and mybmw apps excluded but the phone still doesn't connect. Any other suggestions?  This is so frustrating.

**Comment by hufman** [comment]
What does the connection status say? Does the car show the Apps icon and it's just never filling in? What connection status does AAIdrive show? Are you connecting over USB or Bluetooth?

**Comment by raza974** [comment]
Hello, i've got the same issue with my X1 F48.
I cant connect my Google pixel 7 anymore.
On the Aii drive Aps , i cant click  on the connect section and show the application menu on my screen.
It worked very well until the moment where i brought my car to the service at my bmw dealer.

**Comment by Sflaguy** [comment]
The aai drive app recognizes the Bluetooth connection but indicated it is waiting for connected drive to be subscribed to. The connection icons never indicate any activity. There aren't any apps that appear in connected drive.

**Comment by lubo13** [comment]
Hi, I cannot connect through the apps with Samsung S23 Ultra.

When I've tried to connect through APPS in the device connection, it always showed me 'Start apps if necessary', then the car connects with the phone through Bluetooth, but in the connected device I do not see apps checkbox how is here -> https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res-facets/tips/drawable/pic_btapp_bmw.jpg

I am logged in MyBMW app and in the car as well.

Could you give me some hints, please?

**Comment by Sflaguy** [comment]
With Christmas I got busy. The apps selection is not available on the radio.

**Comment by hufman** [comment]
If the Apps checkbox is not available in the car, that needs to be resolved first. Is Apps an option when pairing the phone?

**Comment by Sflaguy** [comment]
Not that I've seen. I am subscribed to connected services through BMW though.

**Comment by hufman** [comment]
To be clear, AAIdrive doesn't use the Location permission unless the Custom Map is configured to use phone location instead of car location, but maybe Samsung needs it for some reason.

**Comment by lubo13** [comment]
Most probably you are right, I didn't test them one by one and just allowed for all of them.

**Comment by Sflaguy** [comment]
I'm at work now but I'll try it on my wife's S23 and x3 tomorrow. Thanks for the info.

**Comment by Evanalfredd** [comment]
> Hi, I cannot connect through the apps with Samsung S23 Ultra.
> 
> When I've tried to connect through iDrive 6 APPS in the device connection, it always showed me 'Start apps if necessary', then the car connects with the phone through Bluetooth, but in the connected device I do not see apps checkbox how is here -> https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res-facets/tips/drawable/pic_btapp_bmw.jpg
> 
> I am logged in MyBMW app and in the car as well.
> 
> @hufman Could you give me some hints, please?

I too am having the same issue but for the s23 ultra and idrive 6. I got vehicle apps but no apps option for my phone. It's like it doesn't even register my phone... I NEED HELP PLEASE! 🙏

**Comment by hufman** [comment]
Check that you have the Apps option when pairing a new mobile device. If you don't have the Apps option, you need to activate the required ConnectedDrive subscription. If you do have the Apps option there, then you need to grant MyBMW access to connect to local devices and run in the background.
