### ISSUE TITLE
Unable to Connect to Vehicle

### ISSUE THREAD

**Issue by thetwo4** [BimmerGestalt/AAIdrive#757]
Currently can't find my car. First time trying to set up. Here are some of the screens I'm seeing...
![Screenshot_20240107_151945_AAIdrive](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/8ff2d343-cf8e-4269-966f-ee0ac1f2f211)
![Screenshot_20240107_151938_AAIdrive](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/1612336a-35f7-495e-b7c4-db05fc1226b8)
![Screenshot_20240107_151935_AAIdrive](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/90bbf70f-1dba-4a8b-9270-df562e898009)
![Screenshot_20240107_151929_AAIdrive](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/cc067ca7-68cb-41de-ba27-f80363b6711d)

**Comment by thetwo4** [comment]
My idrive screen shows the following apps:
![20240107_152112](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/bf091a0e-482a-4c43-ad84-d13ba8970fc8)

**Comment by hufman** [comment]
Please check the car's mobile device menu, does it provide an Apps option? It should look like the following: https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res-facets/tips/drawable/pic_btapp_bmw.jpg
If the Apps option is missing, please check the ConnectedDrive subscription. Once the Apps option shows up and MyBMW successfully connects and shows a tick box, then AAIdrive will be able to connect.

**Comment by thetwo4** [comment]
This is what I see. ConnectedDrive is active/subscribed. 

I can see the Apps tickbox when I go to add a device, but when my device is added I get this screen.

![20240107_220049](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/d02379dc-b390-4780-85ce-22e24995e938)

**Comment by hufman** [comment]
Hmmm I'm not sure how the car decides to add the Apps entry or not, during the pairing process.
Can you try unpairing, and then keeping the MyBMW app open while pairing the phone again?

**Comment by thetwo4** [comment]
Still no luck. Anything else I can try?
![20240108_160037](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/2a6cc953-139e-436d-ba25-6c7948e71ca7)
![20240108_160050](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/3755320b-567b-437a-8df7-1de793e30726)

**Comment by thetwo4** [comment]
Update: the box now shows up for my phone, but no luck with clicking. When I click, I get "Connecting...Start app if necessary."

![20240108_161831](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/95359fc5-d30d-4587-a78c-ff904ab90c6b)
![20240108_161837](https://github.com/BimmerGestalt/AAIdrive/assets/52980088/1ab1aaa8-004c-4d16-8dfd-d9276848a3a0)

**Comment by hufman** [comment]
Very good!
So clicking that button in the car just enables the car's Bluetooth to listen to connections from MyBMW, and usually stays enabled across restarts (Apps over USB sometimes confuses this).
Now that the car is ready to receive connections, try opening MyBMW and it should connect after a bit. Once connected, try opening AAIdrive and it should see the car connection and add its apps.
After confirming that it works manually, then you just need to set up Samsung to allow the apps to start in the background.

**Comment by thetwo4** [comment]
Looks like we got action! Thanks for this!!
