### ISSUE TITLE
Functionality lost when phone goes to sleep.

### ISSUE THREAD

**Issue by thetwo4** [BimmerGestalt/AAIdrive#758]
Spotify boots perfectly when starting the vehicle. After about 3 minutes, music continues to play, but screen info freezes and I lose the ability to control the app unless I wake up my phone. Seems like I lose control when my phone goes to sleep.

**Comment by hufman** [comment]
Samsung is particularly aggressive about background app execution restrictions, and so you must [apply custom settings](https://github.com/BimmerGestalt/AAIdrive/discussions/709) to allow MyBMW and AAIdrive to run with the screen off.

**Comment by thetwo4** [comment]
Set this up as directed. Still been having issues. Power saving mode off as well. Any other options?

**Comment by hufman** [comment]
The only advice I can give is that both MyBMW and AAIdrive need to be configured to not pause when in the background, and every phone model has different ways to do this. Samsung is the trickiest and most popular, so it has its own article, but many other phones have similar aggressive strategies.
