### ISSUE TITLE
AU 2023 mini clubman and samsung G z5 fold, wont connect to AAIdrive

### ISSUE THREAD

**Issue by dawaterson** [BimmerGestalt/AAIdrive#759]
Hi everyone,

On my fourth Mini. Still got other 2 at home.
Just took delivery of one of the last AU Clubmans, no more for Australia.
Latest ver AAIdrive installed on Mbl Ph, logged into mini connect on Ph,
Mbl Ph connected to Car's bluetooth. AAIdrive continually days waiting for connection to mini.

Why is this so?
Is there something diff with Aussie model's or ver of software?
I have read all the doc seen all the pics n vids, my car does not do any of the connection or show icons  in mini connected on infotainment system.

Please help

Cheers
DW

**Comment by hufman** [comment]
From what I've heard, there isn't anything peculiar to the connection process of Australian cars, just that they are hardcoded to lock the screen out while the car is in motion.
In your Mobile Devices menu, do you see the option to pair for Apps, or just Carplay and Phone and Music?
https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res-facets/tips/drawable/pic_btapp_mini.jpg

**Comment by dawaterson** [comment]
Hi, sorry, late to reply.I have been trying everything.In mbl on mini connected it shows just Carplay and Phone and Music.NO Apps icon.
What do i do now> AAIDrive still cannot connect to my mini.??
Regards 

David Waterson

David A WATERSON




CPSU National Section Secretary Aviation & ASA Delegate QLD.




mbl +61 458119777




 

    On Friday, 19 January 2024 at 02:24:59 am AEST, Walter Huf ***@***.***> wrote:  
 
 


From what I've heard, there isn't anything peculiar to the connection process of Australian cars, just that they are hardcoded to lock the screen out while the car is in motion.
In your Mobile Devices menu, do you see the option to pair for Apps, or just Carplay and Phone and Music?
https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res-facets/tips/drawable/pic_btapp_mini.jpg

**Comment by hufman** [comment]
I'm not sure, I thought all the latest gen Minis included Mini Connected feature from the factory, but perhaps yours doesn't? Unlike BMW where it's a subscription, Mini seems to have it as a factory option, but different regions may be different. You should talk to the dealer about how to get the Apps feature added, if possible.

**Comment by dawaterson** [comment]
Hi,
I have confirmed all my mini connected apps etc are now active subscriptions till 2027. In mini connected there are weather, wiki n news apps now.
I am now more frustrated than ever, as no one here has worked with a Sep 2023 cooper S clubman. N getting Tue software to work. Also there are question over whether the mmi prime interface unit would work. Hoping someone has some ideas. LlCheers
Dave W

Sent from Yahoo Mail on Android 
 
  On Wed, 24 Jan 2024 at 4:26, Walter ***@***.***> wrote:   


I'm not sure, I thought all the latest gen Minis included Mini Connected feature from the factory, but perhaps yours doesn't? Unlike BMW where it's a subscription, Mini seems to have it as a factory option, but different regions may be different. You should talk to the dealer about how to get the Apps feature added, if possible.

**Comment by hufman** [comment]
Were the subscriptions not active before? The car seems to have noticed the subscriptions by unlocking the various internal apps, try unpairing and re-pairing, maybe it shows the Apps option now.
I've never used the MMI addon box, the app works directly with the native BMW system.

**Comment by dawaterson** [comment]
Hi, 
deleted mbl from mini connected in car, re added it via bluetooth.. Also did uninstall reinstall AAIDrive. No change.Cant send pics, are too big. How can I get some pics of car info screen to you?Also not when I tried to use USB and set that as preferred. It still didn't work.
Cheers
Dave W


Sent from Yahoo Mail on Android 
 
  On Thu, 25 Jan 2024 at 4:52, Walter ***@***.***> wrote:   


Were the subscriptions not active before? The car seems to have noticed the subscriptions by unlocking the various internal apps, try unpairing and re-pairing, maybe it shows the Apps option now.
I've never used the MMI addon box, the app works directly with the native BMW system.

**Comment by hufman** [comment]
GitHub doesn't let you email pictures, you'd have to attach in the website.
AAIdrive has no influence on Mini's connection to the car or your car's Apps icon. You must get the Apps icon to show up first, then get the Mini app to connect to the car and fill in the Apps checkbox, and then you can install AAIdrive and it will access the car connection. I can only refer you to the dealer to try to get it working, I don't know the specifics of how a car decides to show the Apps icon or not.

**Comment by dawaterson** [comment]
Hi,Some success,
I have found it was an app permissions problem with mini app n AAIDrive. I now have connection and apps on mini connected idrive from smartphone.Still have a problem where clicking on the Apps.in mini infotainment screen and nothing happens they dont open up.
Almost there.Cheers
Dave W

Sent from Yahoo Mail on Android 
 
  On Thu, 25 Jan 2024 at 16:41, Walter ***@***.***> wrote:   


GitHub doesn't let you email pictures, you'd have to attach in the website.
AAIdrive has no influence on Mini's connection to the car or your car's Apps icon. You must get the Apps icon to show up first, then get the Mini app to connect to the car and fill in the Apps checkbox, and then you can install AAIdrive and it will access the car connection. I can only refer you to the dealer to try to get it working, I don't know the specifics of how a car decides to show the Apps icon or not.
