### ISSUE TITLE
HVAC and EVAC

### ISSUE THREAD

**Issue by Dephead2004** [BimmerGestalt/AAIdrive#765]
Hi Hufman,
Is it possible that the latest update has removed  HVAC and EVAC readouts from iDrive? The sensors are both still working (see photos)
![Screenshot_20240211_122501_AAIdrive](https://github.com/BimmerGestalt/AAIdrive/assets/139343381/1d78905d-9ac9-4bc6-ab82-e7ec3777eb3d)
![20240211_122623](https://github.com/BimmerGestalt/AAIdrive/assets/139343381/5460be6c-b05f-46da-867f-6404e41cbeab)
![20240210_115059](https://github.com/BimmerGestalt/AAIdrive/assets/139343381/8728614c-8f31-4d92-9369-b4919e903125)
With the readouts was 10 .2.24 without was 11.2.24

By the way, have sent you some "coffees". Thank you muchly.

**Comment by hufman** [comment]
Yes indeed, it was [removed](https://github.com/BimmerGestalt/AAIdrive/commit/399868bbf1fb63115995b1bc1e76d05ab211605a) because it's too detailed for the first page of this data view and it's unclear what these temperatures actually mean. To view them now, enable Advanced Settings to show more data categories and go to the Air Condition Info tab.

**Comment by Dephead2004** [comment]
Thanks Walter,

 

I only ask because I changed the battery yesterday too and thought I might have broken the aircon!

 

I did have advanced settings enabled in AAiDrive under settings. It says try connecting to a car by TCP tunnel. Is this what I am to do ?

 

Perhaps you mean that there are advanced settings in iDrive?

 

I cannot see the Air Conditioning info tab.

Many thanks

 

Martin

**Comment by Dephead2004** [comment]
I have been in the car now and see what i need to do to click on ?(detailed
Vehicle Info). Then lots more detail is generated. Superb
Thanks

**Comment by hufman** [comment]
Precisely correct, just having the Advanced Settings box enabled will add extra options to those Car Information tabs.
