### ISSUE TITLE
Waze

### ISSUE THREAD

**Issue by Losfritos** [BimmerGestalt/AAIdrive#768]
Bonjour , déjà merci pour ce logiciel qui est vraiment top !
J'aurai voulu savoir si il y aura un jour waze de disponible par cette application ? Merci

**Comment by hufman** [comment]
Unfortunately, AAIdrive is unable to embed other apps to be shown in the car. The existing map functionality is implemented by building a custom map view on an internal AAIdrive window that is shown in the car, which allows AAIdrive to send commands to the map and screenshot it without asking permission every time.
In comparison, the [screen mirroring addon](https://github.com/BimmerGestalt/IDriveConnectAddons/releases/tag/latest_build) requires asking permission every connection, keeping the screen on, and can't send input to the other app. Android Auto itself has special access to certain apps, but those apps only give access to AA by specific package name and app signatures.
