### ISSUE TITLE
Geen verbinding met aaidrive

### ISSUE THREAD

**Issue by Rienfloot** [BimmerGestalt/AAIdrive#770]
Met de oude auto had ik verbinding tot oktober 2023(bmw m2 2017)
Dit is te zien in de app bij voertuig gegevens.
Met de nieuwe auto (bmw m2 2020) krijg in,geen verbinding met de aaidrive.
Contact maken met de my bmw app was /is op beide auto's geen probleem.
Ik kan de oude auto ook niet verwijderen uit de aaidrive app,al diverse keren de app verwijderd .
Zonder resultaat. 

Is hier een oplossing voor?

**Comment by hufman** [comment]
I'd like to know more about the connection details to the car. Just registering the car in MyBMW isn't enough, does the connection actually fill in the checkbox in the car? If MyBMW is connecting properly, AAIdrive will see the proxy and connect to the car, and update the stored information with the new car data.
![image](https://github.com/BimmerGestalt/AAIdrive/assets/1592375/0b37f2d0-7869-4ff5-b38b-5cf4686e7e0d)
