### ISSUE TITLE
No visible queue on HUD/6WB cluster. 

### ISSUE THREAD

**Issue by TBGR** [BimmerGestalt/AAIdrive#775]
So I recently upgraded to a 2014 F10 with factory NBT. After coding in the apps functionality the app itself works as expected - I can do everything with Spotify, the API is authorized, the queue/browsing works perfectly except for the queue on the HUD/cluster - I get only the name of the current song and the Next/Previous arrows. From what I understand in previous discussions/pull requests/commits it should be functional. Trying it with a Premium account running on an old Galaxy S6 edge, tried it both offline and online since the phone has no SIM in it.

**Comment by hufman** [comment]
Unfortunately iDrive 4 does not support Apps populating the HUD playlist. AAIdrive is sending the data, but it just doesn't show. It seems to be exclusive to iDrive 5/6.
