### ISSUE TITLE
Yandex Music Albom Cover polyscreen

### ISSUE THREAD

**Issue by Ren-Z4** [BimmerGestalt/AAIdrive#776]
Hello!
When playing Yandex Music(YouTube), the cover art is displayed only inside the application and is not displayed on the side screen. Can this be configured or does it need to be fixed in the application?

![PXL_20240318_091418114](https://github.com/BimmerGestalt/AAIdrive/assets/163852855/033b2c9b-546f-4dd1-a0cf-6e027bcf65f5)
![PXL_20240318_091448178](https://github.com/BimmerGestalt/AAIdrive/assets/163852855/4b85121c-ca7a-45f8-a3ff-9ef55f516be7)
 ![PXL_20240318_091245006](https://github.com/BimmerGestalt/AAIdrive/assets/163852855/1d27f22e-dfa1-4e11-bbc4-38aeb34dc853)
![PXL_20240318_091245006~2](https://github.com/BimmerGestalt/AAIdrive/assets/163852855/879d1c9e-cf22-4be8-ae99-0ea06feadcdb)

**Comment by hufman** [comment]
Thank you very much for the pictures!
This shows that AAIdrive is using the legacy audioplayer interface, instead of the ID5/6 audioaplayer which grants control over the global coverart. This is because AAIdrive relies on the BMW Spotify app to enable the new audioplayer interface. AAIdrive, by default, only enables the Spotify interface if the Spotify app is installed, because it adds a Spotify icon to the car which could be confusing if the phone doesn't actually have Spotify.

Under AAIdrive's Advanced Settings, you can find the option to always enable the Spotify interface, which will give you this additional Spotify icon and enable the new audioplayer interface.

**Comment by Ren-Z4** [comment]
> Thank you very much for the pictures! This shows that AAIdrive is using the legacy audioplayer interface, instead of the ID5/6 audioaplayer which grants control over the global coverart. This is because AAIdrive relies on the BMW Spotify app to enable the new audioplayer interface. AAIdrive, by default, only enables the Spotify interface if the Spotify app is installed, because it adds a Spotify icon to the car which could be confusing if the phone doesn't actually have Spotify.
> 
> Under AAIdrive's Advanced Settings, you can find the option to always enable the Spotify interface, which will give you this additional Spotify icon and enable the new audioplayer interface.

Thank you! It's really working. Cool!
![PXL_20240318_154248948](https://github.com/BimmerGestalt/AAIdrive/assets/163852855/71fb86f2-71af-4e1a-90ba-3fee74ab8d80)
![PXL_20240318_154322810](https://github.com/BimmerGestalt/AAIdrive/assets/163852855/a00daf85-a689-4648-8f88-f57bff8029e7)
![PXL_20240318_154356893](https://github.com/BimmerGestalt/AAIdrive/assets/163852855/89d86b68-5025-447a-81fb-e56c843003ff)

**Comment by hufman** [comment]
Glad to help!

**Comment by Esco54** [comment]
Hello Walter, I don't use Spotify but YTM on ID6. Should i play the music through the Spotify interface to access browsing music folders ?

**Comment by hufman** [comment]
Browsing folders depends on the music app providing access, and I don't believe YouTube Music has provided access. Entering AAIdrive through a different menu won't help.

**Comment by Esco54** [comment]
What is the advantage of using the Spotify interface?

**Comment by hufman** [comment]
The Audioplayer interface is from Connected Classic and has tighter spacing to match ID4, while the Spotify interface matches the music interfaces in ID5 and provides global coverart support.

**Comment by Esco54** [comment]
> The Audioplayer interface is from Connected Classic and has tighter spacing to match ID4, while the Spotify interface matches the music interfaces in ID5 and provides global coverart support.

Hey Waylter, I can't browse through folders in Spotify with ID5? Do i need to change some settings?

**Comment by hufman** [comment]
The music tab will show if you are missing some of the permissions. Make sure you aren't using a modded Spotify app, the API client won't work with mods.
