### ISSUE TITLE
Album cover not displayed 

### ISSUE THREAD

**Issue by Timkathy** [BimmerGestalt/AAIdrive#777]
On Spotify or BBC Sounds the album cover or radio show does not display. This is just recent occurrence. Hope you can help

**Comment by hufman** [comment]
Unfortunately, the cover art provided by the music app is not under AAIdrive's control. Make sure Spotify is properly logged in for browsing support, but there's nothing else to try.

**Comment by Timkathy** [comment]
Thanks for your reply.  The AAI drive has been brilliant for me but the
update in February has not carried through for me. Is there anything I can
do. My car is G30 ID5 version as per attached.
Thank you
Tim

**Comment by hufman** [comment]
Unfortunately there is nothing more that can be done, if the music apps do not allow access to the cover art.
