### ISSUE TITLE
Any problem with MyBMW 4.3.0?

### ISSUE THREAD

**Issue by MarcoLeo66** [BimmerGestalt/AAIdrive#779]
MyBmw 4.3.0 seems to be not compatible with AAIdrive anymore, have you had the same problem? Or is the new Samsung One Ui 6.1 the problem? It worked perfectly until last week.

**Comment by hufman** [comment]
I haven't heard any reports, my phone is running Mini 4.3.2 and works fine.

**Comment by MarcoLeo66** [comment]
Hi Walter, all is working now, after two days trying with no success (uninstall, install, reset iDrive phone list... again and again) today it is working and I do nothing to arrange it, just pick up the car and I find Simple Radio and Spotify icons on the screen.
Best regards.
