### ISSUE TITLE
Unable to connect to "Apps" on IDrive6 - Missing the "Apps" checkbox on IDrive with Pixel 8 connected via Bluetooth (works on my pre-upgrade Xperia J8210)

### ISSUE THREAD

**Issue by Yosh82** [BimmerGestalt/AAIdrive#780]
I've upgraded to a Pixel 8 and unable to get the "Apps" function to show on the Idrive for the Pixel 8 while connected via Bluetooth. It shows Phone, Bluetooth Audio and Contacts, but not the Apps checkbox (this still shows for my J8210 phone, but not on my new Pixel 8).

If I connect the Pixel 8 via USB, I do see the Apps checkbox, but no other options, which does then connect to AAIdrive.

As my old J8210 still works with AAIDrive on Bluetooth, this seems to be an issue with the application.

I've seen a few other similar posts but thought best to start one specifically for my issue. I will attach some images if needed.

I've cleared cache / data for My BMW and AAIDrive, and enabled devolper mode but didn't help.

Any help appreciated! Thanks in advance.

**Comment by EvilDorf** [comment]
Hey mate, i got pixel 7 with same issue, go to dev menu and force Bluetooth 1.3, and give all permissions to mybmw app, it fixes the problem.

**Comment by Yosh82** [comment]
> Hey mate, i got pixel 7 with same issue, go to dev menu and force Bluetooth 1.3, and give all permissions to mybmw app, it fixes the problem.

Hi mate, thanks for the response. I thought this may fix is as I know it's related to bluetooth. I set the MAP version of Bluetooth to 1.3 but no luck. I've also tried all of the versions of MAP and also AVRCP.

I've removed my J8210 from IDrive and can readd it with the apps fine. I checked the J8210 BT settings and they are AVRCP v1.6 and MAP v1.2 - Connects fine. Setting the same on the Pixel 8 doesn't work.

Tried the same config on the Pixel 8 and still not showing the Apps checkbox. I'll keep at it with some other setting later on and see if I can figure this out.

**Comment by EvilDorf** [comment]
Give all available permissions to mybmw app and disable power control, i am sure it will work, just did it today. Can give you screenshot of my phone settings, mb it will help, but it's in russian.

**Comment by Yosh82** [comment]
> Give all available permissions to mybmw app and disable power control, i am sure it will work, just did it today. Can give you screenshot of my phone settings, mb it will help, but it's in russian. Problem is not on phone itself, it's 14 android issue.

You beat me to it, I was just setting all permissions to the bmw app as I only allowed what I thought was needed before. Will test shortly and update here. Much appreciated EvilDorf.

**Comment by EvilDorf** [comment]
Happy to help. Please reply here when you get positive result to help ppl with same problem. :)

**Comment by Yosh82** [comment]
The issue was the permissions to the BMW app. I've disabled devoloper mode (so using the stock settings) and all is now working since allowing ALL permissions in the MyBMW app. Thanks again mate, have a great weekend!

**Comment by hufman** [comment]
Can you share some screenshots to help other people know what to set on their own phones?

**Comment by Yosh82** [comment]
> Can you share some screenshots to help other people know what to set on their own phones?

Sure. For clarity, I removed the AAIDdrive app, disabled devloper mode, reinstalled AAIdrive so I had a fresh install and no changes via Dev mode.

The only changes I made after this was allowing all permissions to the MyBMW app:

![Screenshot_20240405-172704](https://github.com/BimmerGestalt/AAIdrive/assets/106485860/35a4ebb7-2644-4bb1-bac6-95259315d13d)

Once I made these changes, the "App" checkbox appeared as expected in the IDrive pairing screen for the Pixel 8.

Hope this helps anyone else with the issue.

**Comment by Yosh82** [comment]
> Can you share some screenshots to help other people know what to set on their own phones?

> Can you share some screenshots to help other people know what to set on their own phones?

Sure. For clarity, I removed the AAIDdrive app, disabled devloper mode, reinstalled AAIdrive so I had a fresh install and no changes via Dev mode.

The only changes I made after this was allowing all permissions to the MyBMW app:
![image](https://github.com/BimmerGestalt/AAIdrive/assets/106485860/6f44ef2e-b7af-4879-8c7f-00fbee26b1d7)

Once I made these changes, the "App" checkbox appeared as expected in the IDrive pairing screen for the Pixel 8.

Hope this helps anyone else with the issue.

**Comment by LuxKeiwoker** [comment]
> > Can you share some screenshots to help other people know what to set on their own phones?
> 
> Sure. For clarity, I removed the AAIDdrive app, disabled devloper mode, reinstalled AAIdrive so I had a fresh install and no changes via Dev mode.
> 
> The only changes I made after this was allowing all permissions to the MyBMW app: ![image](https://private-user-images.githubusercontent.com/106485860/320076746-6f44ef2e-b7af-4879-8c7f-00fbee26b1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTY5ODgsIm5iZiI6MTcyNzg5NjY4OCwicGF0aCI6Ii8xMDY0ODU4NjAvMzIwMDc2NzQ2LTZmNDRlZjJlLWI3YWYtNDg3OS04YzdmLTAwZmJlZTI2YjFkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxOTE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWQ5YzYzODBhMGEwNWM3MDg2ZTRhNzljN2E1YmQwODUxY2QyN2M2NDcyZDBhNThlYWE2ZmFhYWE4MDc4YTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8RblT-k9hP3IgcdLTm7Ht8DYp5zoxlVDnP6HlzD10kM)
> 
> Once I made these changes, the "App" checkbox appeared as expected in the IDrive pairing screen for the Pixel 8.
> 
> Hope this helps anyone else with the issue.

This should be included in the readme of this GIT. I was pulling my hair for hours, as to why the App checkbox didn't appear in my car. Only after searching in closed issues i stumbled across this post which resolved my issue immediately!

**Comment by hufman** [comment]
@LuxKeiwoker You inspired me to check, and in fact it is possible for AAIdrive to check whether MyBMW has the Nearby Devices permission, for some reason.
I added a warning about this missing permission to the Overview and Connection tabs, which is currently available in [the latest build](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-main-mapbox-sentry-release.apk), and after waiting a week for translations to roll in and anyone testing for bugs, I'll push it to the Play store.
Thank you for helping improve the project!
