### ISSUE TITLE
Car information on Cars display

### ISSUE THREAD

**Issue by ImonKimon** [BimmerGestalt/AAIdrive#782]
Hello,

I don't see the Detailed Car information section in the id5 Menü. I have a f20 125d from 2017 with navigation professional.

In my father's f48 from 2018 with id6, the section is plopping up in the Vehicle menu of the idrive, after a few moments when the app is connected.

Someone knows if the problem is that I don't have id6, or is it possible to see that in both versions of the idrive system?

**Comment by hufman** [comment]
I apologize, I don't have an ID4 system to test on. I do remember that the icons that are created for the music apps and the fully labelled Phone Notifications and Car Information icons sometimes misbehave in ID4 and don't open the full apps.
You should look in the Connected Apps menu, which has a series of unlabelled icons. The labelled icons try to open these apps. Car Information is one of these, I believe it's the one without an icon.

**Comment by ImonKimon** [comment]
Hey,
i dont know why, but its working perfectly now.
Maybe you changed something in the last update?
Or the problem was that i didn't gave the permission to get the notifications in idrive from the app.
Car information is now showing up in the vehicle menu. 👍
Thanks

**Comment by hufman** [comment]
Glad to hear it!
