### ISSUE TITLE
Trying to setup AAIdrive with 2016 NBT Evo 

### ISSUE THREAD

**Issue by matt-pinder** [BimmerGestalt/AAIdrive#785]
I am trying to setup with my 2016 NBT Evo however running into the issue where the car says 'Install BMW Connected App' 

I have attached a few photos showing the app status. 
![WhatsApp Image 2024-05-08 at 17 31 10_90f0d645](https://github.com/BimmerGestalt/AAIdrive/assets/22836862/382b7a3e-d612-41d1-a9f3-68334c8409e7)
![WhatsApp Image 2024-05-08 at 17 31 10_e0e59311](https://github.com/BimmerGestalt/AAIdrive/assets/22836862/796952a5-f71b-4101-9645-ad3655d8b6ae)
![WhatsApp Image 2024-05-08 at 17 31 10_b99e6c27](https://github.com/BimmerGestalt/AAIdrive/assets/22836862/60e85d39-7eed-4ad7-8a25-015c3cb63f81)

**Comment by hufman** [comment]
Do you have MyBMW installed, and does it have all the permissions granted? MyBMW's USB support is flaky, so you might have better success installing BMW Connected 6.4 (not 6.5), or BMW Connected Classic.

**Comment by matt-pinder** [comment]
Found a solution to this, I installed the mini app, force stopped the mybmw app, connect to the car, when the popup appears, wait 3 seconds and click mybmw allow once and not granting it the permissions for open link. The app then appears to work.

Maybe an older MyBMW app is better but i was unable to find one

**Comment by hufman** [comment]
Glad you got it working!
