### ISSUE TITLE
Struggling with connectivity of AAIdrive with my new (Used) Mini

### ISSUE THREAD

**Issue by Whestie** [BimmerGestalt/AAIdrive#787]
So I purchased a 2020 Electric Mini yesterday and got the My Mini app and AAIdrive installed all ready to go.

The problem I'm facing is nothing seems to be speaking to each other.

So the My Mini app does connect with my car relatively okay, it gets all the info correct though if I send any commands to my car, such as locking it, it'll take at least 30 seconds before the car picks up the command.

If I access Mini Connection on the car, I can view my mobile devices, though it does actually show 2 instances of my phone, one with hands-free and media and then the other under the heading "available devices". If I choose this option I have an "Apps" option and then get presented with a screen that just states "Connecting... Start app if necessary."(https://i.imgur.com/MMAQYAv.jpg)

I'm not sure if I'm actually allowed to start any app or if this is strictly for Apple CarPlay and that's why it's even available but it's not smart enough to detect whether my is or isn't Apple. Annoyingly the car tells me to visit a page that doesn't work: https://www.mini.com/bluetooth and if I check the bluetooth compatibility site (https://www.mini.com/en_MS/home/mini-connectivity.html) and it says my car is all up to date software wise.

The Navigation also seems to be off, my address isn't recognised at all and my house is nearly 20 years old. I know I can pay for a nav update but I don't know what this entails and I don't want to fork out the money for something that might not work at all, especially when the compatibility site says my car is up to date, can someone shed some light on this for me maybe?

Regarding AAIdrive, this is a bit annoying because while [my app does connect to my car fine](https://i.imgur.com/HVTXRcO.jpg), my AAIdrive app [won't connect to my Mini app](https://i.imgur.com/LxA2WRS.jpg)for whatever reason. It just says to [make sure I'm logged in](https://i.imgur.com/TMPCRzS.jpg). Annoyingly there aren't too many resources online for this and I doubt a garage would help me so I'm putting the question to the only people I think might be able to help me.

Any help or advice would be hugely appreciated.

For clarity I've reset the bluetooth on my car twice and on my phone, I've logged out and removed the apps once over each too.

**Comment by daafisch** [comment]
I was having a similar issue trying to get AAIDrive setup where it would just say "make sure the mini app is logged in". Based on a suggestion in a closed issue I enabled all permissions for AAIDrive and Mini Connect. I also removed background battery restrictions for both, once I did this the AAIDrive app connected and it seems is good to go now. I'm able to see a bunch of apps in the media section. Fwiw, I have a 2019 F54
