### ISSUE TITLE
Apps Connection Not possible

### ISSUE THREAD

**Issue by CeKa92** [BimmerGestalt/AAIdrive#789]
No Apps Connection possible for me. 
Working right now with Xiaomi 14 with Android 14 and my BMW 4.5.2.
It is trying to Connect but nothing Happens. 
![IMG_20240523_215548](https://github.com/BimmerGestalt/AAIdrive/assets/157313606/0f94f1e3-e168-4554-9cd8-1da25d566f21)

**Comment by blocktrron** [comment]
I've had the same issue this morning when changing from a Pixel 4a (Android 13) to a Pixel 8a (Android 14). For me, disabling power-saving as well as granting all pemrissions on the MyBMW App fixed the issue as described here: https://github.com/BimmerGestalt/AAIdrive/issues/780#issuecomment-2040131607

**Comment by CeKa92** [comment]
> I've had the same issue this morning when changing from a Pixel 4a (Android 13) to a Pixel 8a (Android 14). For me, disabling power-saving as well as granting all pemrissions on the MyBMW App fixed the issue as described here: [#780 (comment)](https://github.com/BimmerGestalt/AAIdrive/issues/780#issuecomment-2040131607)

Thank you! I gave all permissions, now its working!

**Comment by CeKa92** [comment]
Worked with giving all permissions to my BMW
