### ISSUE TITLE
BMW 1 Series 2018 NBTEVO ID5/6

### ISSUE THREAD

**Issue by CraigyBMW1S** [BimmerGestalt/AAIdrive#790]
Followed the readme. and opened MyBMW and the AA app while car was running. It recognised the Bluetooth, but wouldn't connect to my car.

What am I doing wrong??

**Comment by hufman** [comment]
Good evening! Hard to say for certain what you are missing:
Does your car show the Apps option when pairing your phone? If not, you probably need to activate the ConnectedDrive subscription.
Have you granted MyBMW all of the available permissions, so it can communicate to the car over Bluetooth? MyBMW is the part that lights up the Apps checkbox in the car, and that needs to be working before AAIdrive will connect.

**Comment by CraigyBMW1S** [comment]
Thabk you for the reply, 

New phone, didn't check for permission access. I've changed that now.

Previously when connecting via Bluetooth (on media for music) I was given contacts, audio and a box for apps. I'm hoping I'll see this again.

Everything is fully updated now. 

 🤞

**Comment by hufman** [comment]
Sounds like it's working :)
