### ISSUE TITLE
Unable to list playlist and albums in Spotify. 

### ISSUE THREAD

**Issue by Wolfsbane1979** [BimmerGestalt/AAIdrive#794]
I have a BMW 520D (2018) iDrive5 i believe.

Until last week everything was working fine but now, i can no longer browse any playlists or albums i have in Spotify.

I have checked all the settings in AAIdrive and Spotify itself and nothing has changed so I have no idea what the issue is.

I can still play Spotify via AAIdrive but i have to control is via the phone which obviously isnt going to happen when im driving.

Any help would be greatly appreciated 

Sunil

**Comment by fame4k** [comment]
I have the exact same problem, everything was working fine until a few days ago.

BMW F20 (2018) iDrive5 (iD6 Lite UI)

**Comment by Wolfsbane1979** [comment]
Glad im not the only one. Thought i was going mad....

Its been doing my head in. Ive also disconnected and reconnected my phone to the car, still nothing.

**Comment by represiv** [comment]
Same issue for me as well. In the last few days, the Spotify library is always empty. I have tried to reauthenticate "Ability to browser your Spotify library" in the AAIdrive app, but without any change.

**Comment by Esco54** [comment]
Same here since this afternoon. This morning browsing was possible.

**Comment by hufman** [comment]
Very curious, thanks for letting me know!
Looking further, it looks like Spotify itself has changed, and is now returning exceptions when trying to browse the top level folder. Browsing a different folder seems to work perfectly.
I've posted to the [Spotify Developer Forum](https://community.spotify.com/t5/Spotify-for-Developers/Android-SDK-ContentAPI-getRecommendedContentItems-quot-default/m-p/6155169#M14272) and the [Spotify Android SDK](https://github.com/spotify/android-sdk/issues/365), hopefully they notice and fix it soon!
This is similar to when they broke the code to view the shuffle/repeat status a few years ago.

**Comment by Esco54** [comment]
Spotify library was working back properly this morning.

**Comment by Wolfsbane1979** [comment]
Checked this morning and its still the same.

@Esco54 Did you do anything different to get yours to work?

**Comment by Esco54** [comment]
@Wolfsbane1979 Not really. Disabled only one option that says something with IDrive 5 in the settings.

**Comment by Wolfsbane1979** [comment]
@Esco54 Any chance you could send a screen shot or description of what the setting is and where to find it on the AAiDrive app?

I can test it when i get to the car after work.

**Comment by r3dalk** [comment]
Hello! Just jumping in with the same issue, noticed it a couple days ago and today I confirmed it.
@Wolfsbane1979 I have found (I think I have at least) the setting that @Esco54  is mentioning. It's in the AAiDrive app, under "Settings", then you have to enable "Show Advanced Settings" and then appears an option that's "Always appear as Spotify app in IDrive5+". 
Haven't tested it myself, but will do this evening and update in case there's any relevant change!

**Comment by Wolfsbane1979** [comment]
@r3dalk Thanks for that mate, ill have a crack after work too. Hopefully it gets things working till they fix it properly in the background :-)

**Comment by hufman** [comment]
No, that Always Appear As Spotify setting does not affect browsing, and also doesn't affect people who have Spotify installed. For people who don't have Spotify installed, AAIdrive will add itself as the old Audioplayer app to the car, but this old app doesn't support global coverart and doesn't fit in with the rest of IDrive5's UI. With this option, AAIdrive will add itself as a Spotify app to enable global coverart, but the car will show a Spotify app when there is no Spotify installed.

You can test for browse support by tapping into AAIdrive's Music tab on the phone, and tapping Spotify, and then the Browse tab. This uses the same browse connection that the car would be using, but conveniently without a car.

What version and region of Spotify does everyone have? My 8.9.50.552 from the US does not have working browsing, currently.

**Comment by Wolfsbane1979** [comment]
@hufman Thanks for clarifying. Guess we will just have to wait until the issue is resolved. Any idea when that might be?

**Comment by Esco54** [comment]
Spotify is still working today. 
8.9.50.552 EU

**Comment by Esco54** [comment]
Just open the library...do not click on anything else and wait. After 2-3 seconds the library starts to unfold.

**Comment by r3dalk** [comment]
@hufman Spotify Browse/Search not working either, version 8.9.50.552 EU on a Samsung S23 Ultra

**Comment by cornkeys** [comment]
I am having the same problem. Is it possible Spotify had a recent update that is causing the problem?

**Comment by cornkeys** [comment]
Spotify updated last on June 18th

**Comment by dorrisdormouse** [comment]
I've been having the same issue for the last few days. I had thought it was android messing up permissions again, but testing in the spotify tool in android gave the same results as I saw in the car, and I played around making sure everything was authorised and that was all OK so I figure there must be some sort of api change. I've not really explored the apps code yet so I still need to get an understanding of how it works. I'll hopefully try and set up a test environment and also take a look at the spotify api's over the weekend.

**Comment by Wolfsbane1979** [comment]
@Esco54 I tried your approach, waited for an entire journey home (20mins) but it remained with an 'Empty' status.

@hufman  I've also noticed that recently, occasionally, when playing a playlist (From the phone), i am unable to browse to a manually selected track in that playlist from the car. All it does is start the current track again.

I too have version  8.9.50.552 EU.

**Comment by represiv** [comment]
After new Spotify app update 8.9.52.552, the Browsing is working again!

**Comment by hufman** [comment]
My phone also updated to 8.9.52.552 and browsing works again!

**Comment by r3dalk** [comment]
Yes! Same here, Spotify 8.9.52.552 EU working!

**Comment by Wolfsbane1979** [comment]
I can also confirm the browsing is working again.
Thanks team for your help :-)

**Comment by Wolfsbane1979** [comment]
@hufman Apologies but this issue is not fully resolved. Whilst the playlist and albums are now available to select there is another problem i am experiencing. If i load a playlist, i cannot select another track from that playlist via the car.. If I do, the first song starts again. This is the same with albums too. The only option i have is to select next.

Again, i can only pick a song i want via the phone, any attempt from car results in the above issue.

**Comment by hufman** [comment]
That is a separate issue, as you've opened in #797

**Comment by saya311** [comment]
i cant confirm it doesnt work to browsing in library, everything is connected but why it doenst work i cant see any spotify library
