### ISSUE TITLE
Particle filter info

### ISSUE THREAD

**Issue by benjaminkelenyi** [BimmerGestalt/AAIdrive#798]
Hello!

 Thanks for this nice work.

Is there any addon to display some information about particle filter?

Thanks,
Benjamin.

**Comment by hufman** [comment]
Unfortunately not, the available data that are possible are [listed here](https://bimmergestalt.github.io/BMWConnectedAnalysis/cds/), and I don't see anything about the filter status. You can use the [CDS Details Addon](https://github.com/BimmerGestalt/IDriveConnectAddons/releases/tag/latest_build) to view what data your car is currently showing.
