### ISSUE TITLE
aaidrive crashes since last update after a while

### ISSUE THREAD

**Issue by nextsux** [BimmerGestalt/AAIdrive#799]
Hello,

I've been using aaidrive happily for a long time without any issues. Since last week it disconnects from car in few minutes. Just restarting app works. After few tries I get notification that app stops working frequently.

I have app installed from gplay now, part of beta. I think start of problems can be connected to update in last week / few weeks. I'm currently on 1.4.2-57 from 1.7.2024.

Android 14, nothing phone 2

Is there a way I can provide more additional info?

**Comment by hufman** [comment]
Alternatively, you could uninstall the Play Store version and install the Sentry build [from Github](https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-main-mapbox-sentry-release.apk), which is the same version but with crash reporting built in. After enabling crash reporting under Settings, use the app as normal and I should get an email if any crashes happen.

**Comment by nextsux** [comment]
Sorry for the delay, I was on a vaccation. Sending you log via an email.

**Comment by hufman** [comment]
I tried adding some error handling, hopefully that helps!
