### ISSUE TITLE
Problem with connection to my BMW118i

### ISSUE THREAD

**Issue by LordVader15** [BimmerGestalt/AAIdrive#805]
Hello. I have tried to use the App but it always says that I have to Check If I am signed in  in the myBmw App. I have already tried to out of the App and sign in again but it does not fix the Problem.
Down Here you can See that everything should BE fine when I try to connect with my Car (Bluetooth and USB (I dont know whats the Problem there )). Also I am Sorry that it is in German. 
![Screenshot_20240729-195514](https://github.com/user-attachments/assets/5c9e8172-b960-4b4d-b977-e0a7a790adb7)
PS: I Hope someone could Help me. And I also Hope that you can forgive me for my mistakes in the Text above.

**Comment by hufman** [comment]
Check your car and make sure your mobile devices connection shows the Apps checkbox, and that MyBMW is successfully checking that box. MyBMW needs permission to connect to local devices and to run in the background in order to successfully connect to the car.
