### ISSUE TITLE
Apps loading but nothing happens 

### ISSUE THREAD

**Issue by BrettNosse** [BimmerGestalt/AAIdrive#806]
Hi, I have an Oppo with Android 14. 
 And a 2023 F56  the list of apps load, when you select one it flashes up App loading ...  But then nothing happens. 
Any ideas?
Thanks Brett

**Comment by hufman** [comment]
If the apps are added to the car, that's great! That means the connection is working.
If the apps don't respond when you select them, that means the phone apps are not allowed to run in the background. Another sign is that they start working when you turn on the phone screen and open either AAIdrive or MyBMW on the phone screen.
Make sure that both AAIdrive and MyBMW are allowed to run in the background.

**Comment by BrettNosse** [comment]
Thanks so much!
Brett
