### ISSUE TITLE
Spotify AAIDRIVE_LIKED_SONGS Not Updating 

### ISSUE THREAD

**Issue by Advrovr** [BimmerGestalt/AAIdrive#813]
First off, thanks so much to everyone involved in creating/maintaining this awesome project. 

The AAIDRIVE_LIKED_SONGS playlist stopped updating quite some time ago. Only had 47 songs on it vs about 85 on real Liked Songs playlist. 

I deleted it, hoping that might make it refresh or rebuild, but no luck. I restored the playlist and still no update.

Is it possible to force recreate the playlist? Or other actions to take to make it functional? Thanks. 

Pixel 7, Android 14
Spotify 8.9.68.456
AA Idrive  1.4.2-82-47cdbd4
BMW G30 Idrive 5

**Comment by hufman** [comment]
Apologies, this feature is sometimes buggy! Try clearing the data for AAIdrive and manually deleting the playlist. Make sure AAIdrive has access to Search Spotify, because that web API is used to manage the temporary playlists.

**Comment by Advrovr** [comment]
Finally got a chance to try your recommendation, and it worked!!  Thanks!
