### ISSUE TITLE
Grant screen recording permission 

### ISSUE THREAD

**Issue by CMSBMW** [BimmerGestalt/AAIdrive#815]
Hello,
I am using AAIdrive in F31 2018, on NBTEVO_ID5.
In the app I have addons Screen mirroring, and on the car idrive I have Screen Mirroring.
When I press Screen mirroring, getting text: Please open the phone app to grant screen recording permission.
I don't know where I have to grant screen recording permission.
I using Samsung A34, when I press Smart view (Mirror Screen) it is not possible to find car.
Please, if someone knows what I have to do to get Screen mirroring.

**Comment by CMSBMW** [comment]
Mobile device is Samsung A23

**Comment by hufman** [comment]
Clicking into AAIdrive, you'll find the Addons option in the left navigation menu. Within the Addons tab, you'll see the Screen Mirroring app that you installed. Tab that Screen Mirroring app to find some permission prompt buttons.
With Android 14, the app can't show a notification without asking first. After granting this permission, Screen Mirroring will show a notification to prompt for recording permission when you open the app in the car. You can also grant the recording permission here, and it will retain it for a few minutes until you get in the car.

**Comment by CMSBMW** [comment]
Hello,
Thanks for reply.
Attached is screenshot of the app.
When I press in iDrive, Screen mirroring I get this message.
I don't understand what I have to grant?!

Thanks.

**Comment by hufman** [comment]
Attachments dont work when replying to GitHub email, you must post them in the website.
You need to click Screen Mirroring in the AAIdrive phone UI to find the options.

**Comment by CMSBMW** [comment]
It works. Thanks a lot.
Great app.
