### ISSUE TITLE
Cant get Screen mirroring app or any app besides the assistants and notifications to work. 

### ISSUE THREAD

**Issue by crazyazz** [BimmerGestalt/AAIdrive#817]
All apps listed in BMW apps are greyed out except google assistant, alexia and the phone notifications. If I click on the greyed out apps like the two circles shown or audio app nothing happens. Any idea what could be wrong?

**Comment by hufman** [comment]
I don't know what you mean by Greyed Out or two circles.
The usual cause of the apps appearing to not respond is that the MyBMW app isn't allowed to run in the background.

**Comment by crazyazz** [comment]
Sorry for not being clear. The apps that are shown in the list under BMW APPS in the HU. The apps that run has icons and names that bright, the app listed that do nothing are a dull. There are two apps list that have no name and only a blue and green circle icon. There are also dull and dont do anything when clicked. 

Funny enough, I tried the BMW connected classic app, it crashes randomly but it included 4 of its own apps, these appeared in the app list on the HU but were also dull and did nothing when clicked. 

I checked to make sure the BMW phone app and AAIDRIVE had run and use battery in the background enabled and they did. 

Its strange how only the google and alexia assistants work, and the phone notifications work. These are the only apps that are brightly listed also.

**Comment by hufman** [comment]
I have no idea what you mean, I haven't seen such greyed-out text or labels.
Do you happen to be in Australia? I know Australia has restrictions about app usage while the car is in motion.

**Comment by crazyazz** [comment]
I am in Australia, that is crazy if its because of that! The car was in park , but I dont think the park brake was on. I will check again, if thats it I hope I can code that out.

**Comment by hufman** [comment]
I've heard it's hard to code out, let me know what you find out!

**Comment by crazyazz** [comment]
Thanks again for your help and making this cool app. Btw is it still in development or has it ended now?

**Comment by hufman** [comment]
AAIdrive is feature complete and unlikely to see new development, indeed. The requirements of BMW-signed resources outlines the limits of what can be built.

**Comment by crazyazz** [comment]
Ok.  How does the map function work? I enabled to use the mapbox maps but nothing seem to change. I'm a bit confused on how it works.

**Comment by hufman** [comment]
You will see a new icon show up in the Connected Apps section of your car. It renders a map on your phone and sends it to the car every frame, so it's not a great experience.

**Comment by crazyazz** [comment]
ok cool, can waze work as a bmw app?

**Comment by hufman** [comment]
No, Waze can not be used in the car because there isn't a (public) way to render or control Waze from another app.

**Comment by crazyazz** [comment]
Thanks for taking the time to answer my questions. 👍
