### ISSUE TITLE
AAI Drive connection issues

### ISSUE THREAD

**Issue by 221287** [BimmerGestalt/AAIdrive#822]
Hello,
The app is having connection issues: 
It doesn't show " detailed vehicle info" on the screen of my car like before and it's losing connection with the car more often. I tried to delete de phone and re- connect it with the car, ai deleted the app and installed it again on my phone. Also I deleted and installed again " My BMW " app and nothing. 
Can you help? 
Thank you.

**Comment by hufman** [comment]
The car connection is handled entirely by MyBMW, so make sure it has permissions to connect to local devices and run in the background.

**Comment by sicktim** [comment]
Depending on your versions, MyBMW app won't work for this purpose. I had to download the old BMW Connected app (version 6.4) manually (not on play store). The app doesn't have any functionality except making AAI drive work.

Context: ID4, samsung galaxy s23, AAI drive
