### ISSUE TITLE
Display Spotify Library not possible any more.

### ISSUE THREAD

**Issue by 6i6i** [BimmerGestalt/AAIdrive#824]
Spotify forced me to relogin in the application. After that AAIdrive is not possible to explore the Spotify library any more.
I already tried to reset Spotify and also reset AAIDrive but nothing helps. 
After pressing the button to "authorize" in AAIdrive a notification is shown from spotify, that a application is connecting, but the checkbox in AAIdrive is not enabled.
![photo_2024-09-25_10-35-00](https://github.com/user-attachments/assets/afe88653-3b59-4e7c-8944-6cc9c50c4b3d)

![photo_2024-09-25_10-35-18](https://github.com/user-attachments/assets/180ecb75-1d90-40dc-8772-53e9564c7a6d)

**Comment by 6i6i** [comment]
Okk...... today suddenly I got a new message screen in Spotify that I can allow AAIdrive to access it. I accepted it and after that the browsing is possible again.

**Comment by hufman** [comment]
I'm glad it worked out! AAIdrive uses the Spotify SDK to connect and control Spotify, and has little influence over how Spotify browse behaves.
