### ISSUE TITLE
Spotify delay/lag when navigating tracks

### ISSUE THREAD

**Issue by Wolfsbane1979** [BimmerGestalt/AAIdrive#826]
@hufman 

Ive noticed that recently there is a 3 - 5 second delay when navigating tracks on Spotify. There is also a audio lag between the track time and the audio.

BMW 520D (2018)
OnePlus 12R, Android 14
Spotify version 8.9.52.552

**Comment by hufman** [comment]
This sounds like Android is restricting background execution. You can check by whether the lag goes away when the phone screen is on and MyBMW or AAIdrive is in the foreground.
Make sure to allow MyBMW and AAIdrive to run in the background.

**Comment by Wolfsbane1979** [comment]
Thanks Walter, i've activated foreground and background running. Hopefully
this sorts the issue. Ill keep you posted.

**Comment by Wolfsbane1979** [comment]
Problem solved. No longer any delays. Thanks Walter.

**Comment by hufman** [comment]
Glad it works!

**Comment by hufman** [comment]
Good morning! Unfortunately YouTube Music does not provide any API to control it, so I can't implement the same custom control that I was able to build for Spotify.
Please reach out to the music app and request that they open up their MediaBrowserService for AAIdrive to connect and browse the library.

**Comment by Wolfsbane1979** [comment]
Hi Mate,

I've emailed Google and Youtube support with the ask.....fingers crossed!

Thanks
Sunil

**Comment by hufman** [comment]
A surprisingly warm reply, but I won't hold my breath :)
