### ISSUE TITLE
Idrive 6 - Samsung s24 - not connecting

### ISSUE THREAD

**Issue by Mr-Vandepotgerukt** [BimmerGestalt/AAIdrive#830]
Hi Hufman, first of all thank you for all your hard work and creating this great app. Unfortunately after switching to a samsung s 24 im not able to get a working connection anymore. Worked like a charm with a samsung a35 before. I have tried all the solution suggestions i could find. Like mentioned here https://github.com/BimmerGestalt/AAIdrive/discussions/709, tried reinstalling and reconnecting the apps (aaidrive and my bmw), sideloaded the old bmw connected app. 
Unfortunately no result. Bleutooth to car connects but the app box is abcent (only for s24 , retried s35  and iphone both have app connection. Any help would be highly appreciated.

**Comment by beer-matt** [comment]
Hi - I also have this combination (S24 Ultra+Idrive 6), and it can work but didn't initially; I had to manually enable permission(s) in AAIdrive/MyBMW (in AAIdrive I've enabled all, MyBMW may have needed to enable Nearby Devices/Location).

Good luck! 🤞

**Comment by hufman** [comment]
Yes, if the Apps checkbox is missing with the new phone, then you need to fix MyBMW. Usually this is due to needing permissions to run in the background and connect to Nearby Devices.
