### ISSUE TITLE
after updating the Head Unit, it's not possible anymore to enable aaidrive

### ISSUE THREAD

**Issue by paolomeraviglia** [BimmerGestalt/AAIdrive#832]
Hi there,
I have an NBT Evo (id5).
Before updating the headunit (software from 2017, now on latest release) I was able to use the app.
Now, my mobile is only seen for audio music or for phone calls by the Head Unit.
Am I missing something after the Head Unit's update in case? Anybody with the same issue with the latest idrive 5 version?

**Comment by TBGR** [comment]
If you do not have a Connected Drive subscription and the Apps option was added with a shady FSC it is possible that the update emoved the FSC. Not sure how it works, but apparently newer versions of ISTA can remove non legit FSCs as soon as you connect.

**Comment by paolomeraviglia** [comment]
I can confirm I have a valid connected drive subscription.
Car is stock and has never been programmed with fake FSCs

**Comment by paolomeraviglia** [comment]
Double checked on bmw store:

![Screenshot_2024-11-04-01-47-55-790_com android chrome](https://github.com/user-attachments/assets/d4de45c8-f791-4875-8c42-cc606847d7ba)
![Screenshot_2024-11-04-01-48-11-839_com android chrome](https://github.com/user-attachments/assets/20b33ea0-f937-4ce8-ab16-d5c29cd4321f)

**Comment by hufman** [comment]
I don't know what you mean by "Latest Release". How are there any updates for the headunit? Is it still IDrive4/5/6? IDrive 7+ don't support the Apps protocol.
The important thing is that MyBMW is able to connect to the car and [check the Apps box](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res-facets/tips/drawable/pic_btapp_bmw.jpg?raw=true).
When you ask the car to pair a phone, do you have the option to pair for Apps, or just Music? That indicates whether the car supports it and the subscription is activated.
If the phone is paired for Apps but no Apps show in the phone's menu, that means MyBMW isn't allowed to connect to the car. Make sure to grant it permissions to run in the background and connect to Nearby Devices.

**Comment by paolomeraviglia** [comment]
> I don't know what you mean by "Latest Release". How are there any updates for the headunit? Is it still IDrive4/5/6? IDrive 7+ don't support the Apps protocol. The important thing is that MyBMW is able to connect to the car and [check the Apps box](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/res-facets/tips/drawable/pic_btapp_bmw.jpg?raw=true). When you ask the car to pair a phone, do you have the option to pair for Apps, or just Music? That indicates whether the car supports it and the subscription is activated. If the phone is paired for Apps but no Apps show in the phone's menu, that means MyBMW isn't allowed to connect to the car. Make sure to grant it permissions to run in the background and connect to Nearby Devices.

Ok, no. I solved the thing, and it is not related to AAidrive. Will answer you, point by point:

- HeadUnit (from here HU) is an NBT_EVO non touchscreen with iDrive5. The original software, from 2016, have been by memory the "I" version. For further details, I would recommend to check all the stuff regarding i-Step updates via e-sys and so on
- The latest release for iDrive5 (and I think also iDrive6, but check please) should be the "Y" version, from 2023.
- After upgrading from one to an other version (so, from I to Y), the HU will reset itself. That means, if you have online services, you need to re-provision the HU after the procedure. To do that, on the HU, open the "ConnectedDrive" tile > click "option" button on the BMW joystick and from there "Update Software". After that, and a forced reboot (press 30+ seconds power on - off button), I solved my issue (so the phone option checkbox "App" reappeared again) and now I am able to pair the phone again.

short feedback: after upgrading to Y version, AAidrive seems to work really better (and consistently), while with I version sometimes it was disconnecting/dropping without reasons.
Sorry again for the unuseful issue.

**Comment by hufman** [comment]
That's fun to know! I know nothing about the software on the car itself, so hearing these details is definitely interesting. Thank you!
